import { defineConfig } from 'drizzle-kit';

// Schema in TypeScript, SQL migrations generated by drizzle-kit (DATABASE §1, §5).
export default defineConfig({
  dialect: 'sqlite',
  driver: 'expo',
  schema: './src/data/schema/tables.ts',
  out: './src/data/schema/migrations',
});
