#!/usr/bin/env python3
"""FINAL-DELIVERY CHART POLISH: take the four Dashboard chart corrections back out.

WHY A REVERSAL. A human reviewing the real workbook found the two year charts
bound to the whole 200-row reserved annual window, the tornado's value axis
automatic and at three decimals, and the histogram's twenty captions crowding
each other. The correction lives in the chart layer's own owners - the manifest
(spec/workbook.yaml), the Phase-8 chart projection (phase8_charts.py), the
builder (workbook_builder.py) and the manifest loader (spec_loader.py) - and
nowhere else: no VBA, no contract, no published value. Every control that pins
the manifest or the builder to an accepted tree keeps its claim the way the
declared VBA layers established it: taking the declared change back out must
reproduce the accepted bytes exactly, on both sides of the comparison.

THE FRAGMENTS ARE GENERATED FROM THE REAL DIFF against ebeae65, the head before
this correction, and applying them all must reproduce each file byte for byte.
All four files are LF.
"""

from __future__ import annotations

# The tree the reversal must reproduce: the head before the chart polish.
ACCEPTED_BEFORE_CHART_POLISH = "ebeae65"

# pccm-relative path -> why it changed.
DECLARED_CHART_POLISH_CHANGES = {
    "spec/workbook.yaml":
        "the annual bridge block declares the applied-year binding (sheet-scoped "
        "names cut at the stamped year count), the s-curve is titled Cumulative "
        "Cost Profile, the tornado declares a 0.10 value-axis step at two "
        "decimals and no bounds, the histogram prints every second caption "
        "(final-delivery chart polish)",
    "builder/pccm_builder/workbook_builder.py":
        "applied_year_bindings projects the names from the same year-count cell "
        "the bridge guard reads and writes them on the bridge sheet; the Dashboard "
        "charts plot bound references - each carrying the cache Excel writes for a "
        "name, without which Excel drops the category binding - a declared "
        "value-axis step and a declared label interval (final-delivery chart "
        "polish)",
    "builder/pccm_builder/phase8_charts.py":
        "the projection carries and validates the applied-year binding, the "
        "value-axis scale and the label interval (final-delivery chart polish)",
    "builder/pccm_builder/spec_loader.py":
        "the loader refuses an applied binding it cannot resolve, a value-axis "
        "bound, a scale that is not a step and an interval that is not a count "
        "(final-delivery chart polish)",
}

# (current fragment, accepted fragment), in file order.
_HUNKS: dict[str, tuple[tuple[str, str], ...]] = {'builder/pccm_builder/phase8_charts.py': (('    TORNADO_ELIGIBILITY_FIELD as '
                                            '_TORNADO_ELIGIBILITY_FIELD,\n'
                                            '    applied_year_bindings as _applied_year_bindings,\n'
                                            ')\n',
                                            '    TORNADO_ELIGIBILITY_FIELD as '
                                            '_TORNADO_ELIGIBILITY_FIELD,\n'
                                            ')\n'),
                                           ('def _bridge_blocks(charts: dict[str, Any], window: '
                                            'int,\n'
                                            '                   bindings: dict[str, dict[str, '
                                            'str]] | None) -> dict[str, Any]:\n',
                                            'def _bridge_blocks(charts: dict[str, Any], window: '
                                            'int) -> dict[str, Any]:\n'),
                                           ('                                   '
                                            'f":${column[\'column\']}${first + counts[name] - '
                                            '1}"),\n'
                                            '                         # CHART POLISH (final '
                                            'delivery). THE APPLIED-YEAR NAME\n'
                                            '                         # this column is plotted '
                                            'through, where the block\n'
                                            '                         # declares one: the '
                                            'sheet-scoped defined name, its\n'
                                            '                         # formula, and the extent '
                                            'cell it cuts at. The\n'
                                            '                         # `range` above stays the '
                                            'whole window the block\n'
                                            '                         # WRITES; the name is what a '
                                            'chart READS.\n'
                                            '                         "applied_binding": (\n'
                                            '                             '
                                            'dict(bindings[str(column["key"])])\n'
                                            '                             if (name == "annual" and '
                                            'bindings) else None)}\n',
                                            '                                   '
                                            'f":${column[\'column\']}${first + counts[name] - '
                                            '1}")}\n'),
                                           ('                        for column in '
                                            'block["columns"]],\n'
                                            '        }\n'
                                            '    if bindings:\n'
                                            '        out["annual"]["applied_binding"] = {\n'
                                            '            "name_prefix": '
                                            'str(bridge["annual"]["applied_binding"]["name_prefix"]),\n'
                                            '            "extent": '
                                            'str(bridge["annual"]["applied_binding"]["extent"]),\n'
                                            '            "extent_cell": '
                                            'next(iter(bindings.values()))["extent_cell"],\n'
                                            '            "window_rows": int(window),\n'
                                            '        }\n',
                                            '                        for column in '
                                            'block["columns"]],\n'
                                            '        }\n'),
                                           ('    bindings = _applied_year_bindings(charts, '
                                            'shell["results"], window)\n'
                                            '    blocks = _bridge_blocks(charts, window, '
                                            'bindings)\n',
                                            '    blocks = _bridge_blocks(charts, window)\n'),
                                           ('        columns = {column["key"]: column for column '
                                            'in block["columns"]}\n'
                                            '\n'
                                            '        # WHAT A CHART READS: the applied-year name '
                                            'where its block declares\n'
                                            '        # one, the whole window range otherwise. '
                                            '`window_range` is carried\n'
                                            '        # beside it so a control can see both what '
                                            'the block writes and what\n'
                                            '        # the chart is bound to - and refuse a chart '
                                            'bound to the whole window\n'
                                            '        # of a block that has a name for it.\n'
                                            '        def bound(key: str) -> dict[str, Any]:\n'
                                            '            column = columns[key]\n'
                                            '            binding = column.get("applied_binding")\n'
                                            '            return {\n'
                                            '                "key": key,\n'
                                            '                "range": binding["reference"] if '
                                            'binding else column["range"],\n'
                                            '                "window_range": column["range"],\n'
                                            '                "binding": binding["name"] if binding '
                                            'else None,\n'
                                            '            }\n'
                                            '\n'
                                            '        projected.append({\n',
                                            '        columns = {column["key"]: column for column '
                                            'in block["columns"]}\n'
                                            '        projected.append({\n'),
                                           ('            "categories": '
                                            'bound(str(chart["categories"])),\n'
                                            '            "series": '
                                            '[dict(bound(str(series["key"])), '
                                            'name=str(series["name"]))\n',
                                            '            "categories": {\n'
                                            '                "key": str(chart["categories"]),\n'
                                            '                "range": '
                                            'columns[str(chart["categories"])]["range"],\n'
                                            '            },\n'
                                            '            "series": [{"key": str(series["key"]), '
                                            '"name": str(series["name"]),\n'
                                            '                        "range": '
                                            'columns[str(series["key"])]["range"]}\n'),
                                           ('            "legend": len(chart["series"]) > 1,\n'
                                            '            # CHART POLISH (final delivery). '
                                            'PRESENTATION ONLY, BOTH OF THEM. A\n'
                                            '            # value-axis STEP (the tornado: 0.10) and '
                                            'a category label interval\n'
                                            '            # (the histogram: every second caption). '
                                            'Neither names a range, a\n'
                                            '            # series or a state word - and neither '
                                            'can hide one: the step\n'
                                            '            # divides whatever bounds Excel reads off '
                                            'the data, and the interval\n'
                                            '            # decides which captions are printed, not '
                                            'which points are plotted.\n'
                                            '            "value_axis_scale": ({k: float(v) for k, '
                                            'v in chart["value_axis_scale"].items()}\n'
                                            '                                 if '
                                            'chart.get("value_axis_scale") else None),\n'
                                            '            "category_label_interval": '
                                            '(int(chart["category_label_interval"])\n'
                                            '                                        if '
                                            'chart.get("category_label_interval") else None),\n'
                                            '        })\n',
                                            '            "legend": len(chart["series"]) > 1,\n'
                                            '        })\n'),
                                           ('                "match its series count")\n'
                                            '        # CHART POLISH (final delivery). A CHART '
                                            'WHOSE BLOCK CARRIES AN\n'
                                            '        # APPLIED-YEAR BINDING PLOTS THE NAMES, NEVER '
                                            'THE WINDOW. Bound to the\n'
                                            '        # whole window it would draw every reserved '
                                            'slot again - the crowded\n'
                                            '        # left-hand plot this correction exists to '
                                            'remove - and look fine.\n'
                                            '        block = '
                                            'inspection["bridge"][chart["source_block"]]\n'
                                            '        binding = block.get("applied_binding")\n'
                                            '        for entry in [chart["categories"]] + '
                                            'list(chart["series"]):\n'
                                            '            column = next(c for c in block["columns"] '
                                            'if c["key"] == entry["key"])\n'
                                            '            if entry["window_range"] != '
                                            'column["range"]:\n'
                                            '                raise ValueError(\n'
                                            '                    f"{INSPECTION_FILENAME}: chart '
                                            '{key!r} says {entry[\'key\']!r} "\n'
                                            '                    f"is written over '
                                            '{entry[\'window_range\']}, the block says "\n'
                                            '                    f"{column[\'range\']}")\n'
                                            '            if binding:\n'
                                            '                bound = column["applied_binding"]\n'
                                            '                if not bound or entry["binding"] != '
                                            'bound["name"]:\n'
                                            '                    raise ValueError(\n'
                                            '                        f"{INSPECTION_FILENAME}: '
                                            'chart {key!r} plots {entry[\'key\']!r} "\n'
                                            '                        "without its applied-year '
                                            'name")\n'
                                            '                if entry["range"] != '
                                            'bound["reference"]:\n'
                                            '                    raise ValueError(\n'
                                            '                        f"{INSPECTION_FILENAME}: '
                                            'chart {key!r} reads {entry[\'range\']} "\n'
                                            '                        f"for {entry[\'key\']!r}; the '
                                            'whole reserved window, not the "\n'
                                            '                        f"applied years '
                                            '({bound[\'reference\']})")\n'
                                            '                if entry["range"] == '
                                            'entry["window_range"]:\n'
                                            '                    raise ValueError(\n'
                                            '                        f"{INSPECTION_FILENAME}: '
                                            'chart {key!r} is bound to the whole "\n'
                                            '                        f"window '
                                            '{entry[\'window_range\']}")\n'
                                            '                _check_applied_binding_formula(key, '
                                            'entry["key"], bound,\n'
                                            '                                               '
                                            'column["range"], binding)\n'
                                            '            else:\n'
                                            '                if entry["binding"] is not None or '
                                            'entry["range"] != column["range"]:\n'
                                            '                    raise ValueError(\n'
                                            '                        f"{INSPECTION_FILENAME}: '
                                            'chart {key!r} reads {entry[\'range\']} "\n'
                                            '                        f"for {entry[\'key\']!r}, '
                                            'which is not the block\'s column")\n'
                                            '        # A VALUE-AXIS SCALE IS A STEP AND NOTHING '
                                            'ELSE. A declared minimum or\n'
                                            '        # maximum would let the presentation layer '
                                            'hide a published value: this\n'
                                            "        # workbook's tornado ranks by |rho| and plots "
                                            'SIGNED rho, so a minimum\n'
                                            '        # of 0 would draw no bar for a top-ranked '
                                            'negative driver and any\n'
                                            '        # maximum would clip a stronger one. The '
                                            'bounds belong to the data.\n'
                                            '        scale = chart["value_axis_scale"]\n'
                                            '        if scale is not None:\n'
                                            '            bounds = sorted({"min", "max"} & '
                                            'set(scale))\n'
                                            '            if bounds:\n'
                                            '                raise ValueError(\n'
                                            '                    f"{INSPECTION_FILENAME}: chart '
                                            '{key!r} declares value-axis "\n'
                                            '                    f"{bounds}; a bound can hide a '
                                            'plotted value, and the extent "\n'
                                            '                    "belongs to the data")\n'
                                            '            if set(scale) != {"major_unit"}:\n'
                                            '                raise ValueError(\n'
                                            '                    f"{INSPECTION_FILENAME}: chart '
                                            '{key!r} declares a value-axis "\n'
                                            '                    f"scale with {sorted(scale)}")\n'
                                            '            if not scale["major_unit"] > 0.0:\n'
                                            '                raise ValueError(\n'
                                            '                    f"{INSPECTION_FILENAME}: chart '
                                            '{key!r} value axis step "\n'
                                            '                    f"{scale[\'major_unit\']} is not '
                                            'a step")\n'
                                            '        interval = chart["category_label_interval"]\n'
                                            '        if interval is not None:\n'
                                            '            if interval < 1 or interval >= '
                                            'int(block["row_count"]):\n'
                                            '                raise ValueError(\n'
                                            '                    f"{INSPECTION_FILENAME}: chart '
                                            '{key!r} prints every "\n'
                                            '                    f"{interval} label(s) of '
                                            '{block[\'row_count\']} categories")\n'
                                            '        # UX-001. AN ABSENT VALUE IS NEVER A ZERO AND '
                                            'NEVER A BLANK. The\n',
                                            '                "match its series count")\n'
                                            '        # UX-001. AN ABSENT VALUE IS NEVER A ZERO AND '
                                            'NEVER A BLANK. The\n'),
                                           ('\n'
                                            'def _check_applied_binding_formula(chart_key: str, '
                                            'column_key: str,\n'
                                            '                                   bound: dict[str, '
                                            'Any], window_range: str,\n'
                                            '                                   binding: dict[str, '
                                            'Any]) -> None:\n'
                                            '    """The name\'s formula is the column\'s window '
                                            'range cut at the ONE extent\n'
                                            '    cell, inside the window, never below one row."""\n'
                                            '    sheet, cells = window_range.split("!", 1)\n'
                                            '    first_cell = cells.split(":", 1)[0]\n'
                                            '    expected = '
                                            '(f"{sheet}!{first_cell}:INDEX({window_range},"\n'
                                            '                '
                                            'f"MAX(1,MIN({int(binding[\'window_rows\'])},N({binding[\'extent_cell\']}))))")\n'
                                            '    if bound["formula"] != expected:\n'
                                            '        raise ValueError(\n'
                                            '            f"{INSPECTION_FILENAME}: chart '
                                            '{chart_key!r} plots {column_key!r} "\n'
                                            '            f"through {bound[\'formula\']}, not '
                                            '{expected}")\n'
                                            '    if bound["extent_cell"] != '
                                            'binding["extent_cell"]:\n'
                                            '        raise ValueError(\n'
                                            '            f"{INSPECTION_FILENAME}: chart '
                                            '{chart_key!r} cuts {column_key!r} at "\n'
                                            '            f"{bound[\'extent_cell\']}; the block\'s '
                                            'extent is {binding[\'extent_cell\']}")\n'
                                            '    if bound["window_range"] != window_range or '
                                            'bound["scope"] != sheet:\n'
                                            '        raise ValueError(\n'
                                            '            f"{INSPECTION_FILENAME}: chart '
                                            '{chart_key!r} binds {column_key!r} "\n'
                                            '            "to a window that is not its column\'s")\n'
                                            '    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", '
                                            'str(bound["name"])):\n'
                                            '        raise ValueError(\n'
                                            '            f"{INSPECTION_FILENAME}: '
                                            '{bound[\'name\']!r} is not a defined name")\n'
                                            '\n'
                                            '\n'
                                            'def emit_phase8_charts(spec: WorkbookSpec, window: '
                                            'int, build_dir: Path,\n',
                                            '\n'
                                            'def emit_phase8_charts(spec: WorkbookSpec, window: '
                                            'int, build_dir: Path,\n')),
 'builder/pccm_builder/spec_loader.py': (('\n'
                                          '    # CHART POLISH (final delivery). THE APPLIED-YEAR '
                                          'BINDING NAMES AN EXTENT\n'
                                          '    # THE RESULTS ANNUAL BLOCK PUBLISHES, and a prefix '
                                          'that can be a defined\n'
                                          '    # name. The names themselves are projected by the '
                                          'builder from the same\n'
                                          '    # cell the bridge guard reads; this only refuses a '
                                          'binding that could not\n'
                                          '    # be resolved.\n'
                                          '    binding = bridge["annual"].get("applied_binding")\n'
                                          '    if binding is not None:\n'
                                          '        prefix = str(binding.get("name_prefix", ""))\n'
                                          '        if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", '
                                          'prefix):\n'
                                          '            raise SpecError(\n'
                                          '                '
                                          'f"{where}.bridge.annual.applied_binding: name_prefix '
                                          '{prefix!r} "\n'
                                          '                "cannot begin a defined name")\n'
                                          '        extent = str(binding.get("extent", ""))\n'
                                          '        if f"{extent}_row" not in results["annual"]:\n'
                                          '            raise SpecError(\n'
                                          '                '
                                          'f"{where}.bridge.annual.applied_binding: extent '
                                          '{extent!r} is not a "\n'
                                          '                "row the Results annual block '
                                          'publishes")\n'
                                          '\n'
                                          '    published = {\n',
                                          '\n    published = {\n'),
                                         ('            raise SpecError(f"{where}: chart {key!r} is '
                                          'a {chart[\'kind\']!r} chart")\n'
                                          '        # CHART POLISH (final delivery). A declared '
                                          'value-axis scale is three\n'
                                          '        # numbers that describe an axis; a declared '
                                          'label interval is a count.\n'
                                          '        # A DECLARED VALUE-AXIS SCALE IS A STEP, AND '
                                          'ONLY A STEP. A minimum or a\n'
                                          '        # maximum here would decide what a reader can '
                                          'see of a published value:\n'
                                          '        # the tornado ranks by |rho| and plots SIGNED '
                                          'rho, so a minimum of 0\n'
                                          '        # hides every negative driver and any maximum '
                                          'clips whatever exceeds it.\n'
                                          "        # Excel's automatic bounds read the data that "
                                          'is actually there. The\n'
                                          '        # step divides whatever range they choose and '
                                          'fixes no extent.\n'
                                          '        scale = chart.get("value_axis_scale")\n'
                                          '        if scale is not None:\n'
                                          '            bounds = sorted({"min", "max"} & '
                                          'set(scale))\n'
                                          '            if bounds:\n'
                                          '                raise SpecError(\n'
                                          '                    f"{where}: chart {key!r} '
                                          'value_axis_scale declares {bounds}; a "\n'
                                          '                    "presentation bound can hide or '
                                          'clip a published value, and the "\n'
                                          '                    "axis extent belongs to the data")\n'
                                          '            if set(scale) != {"major_unit"}:\n'
                                          '                raise SpecError(\n'
                                          '                    f"{where}: chart {key!r} '
                                          'value_axis_scale carries {sorted(scale)}")\n'
                                          '            try:\n'
                                          '                step = float(scale["major_unit"])\n'
                                          '            except (TypeError, ValueError) as error:\n'
                                          '                raise SpecError(\n'
                                          '                    f"{where}: chart {key!r} '
                                          'value_axis_scale is not numeric") from error\n'
                                          '            if not step > 0.0:\n'
                                          '                raise SpecError(\n'
                                          '                    f"{where}: chart {key!r} '
                                          'value_axis_scale step {step} is not a step")\n'
                                          '        interval = '
                                          'chart.get("category_label_interval")\n'
                                          '        if interval is not None and (not '
                                          'isinstance(interval, int)\n'
                                          '                                     or '
                                          'isinstance(interval, bool) or interval < 1):\n'
                                          '            raise SpecError(\n'
                                          '                f"{where}: chart {key!r} '
                                          'category_label_interval {interval!r} is not "\n'
                                          '                "a positive count")\n'
                                          '        if chart["anchor"] in anchors:\n',
                                          '            raise SpecError(f"{where}: chart {key!r} is '
                                          'a {chart[\'kind\']!r} chart")\n'
                                          '        if chart["anchor"] in anchors:\n')),
 'builder/pccm_builder/workbook_builder.py': (('                worksheet, shell["charts"], '
                                               'shell["results"],\n',
                                               '                worksheet, shell["charts"],\n'),
                                              ('    # THE ONE YEAR-COUNT AUTHORITY: the same cell '
                                               'the applied-year chart names\n'
                                               '    # cut at (_annual_extent_cell), so a chart can '
                                               'never outreach its guard.\n'
                                               '    years = _annual_extent_cell(results, '
                                               '"year_count")\n',
                                               '    years = '
                                               'f"${nominal_col}${annual[\'year_count_row\']}"\n'),
                                              ('    emit(bridge["annual"], '
                                               '_chart_bridge_annual(bridge["annual"], results, '
                                               'raw, window))\n'
                                               '    bindings = applied_year_bindings(charts, '
                                               'results, window)\n'
                                               '    if bindings:\n'
                                               '        from openpyxl.workbook.defined_name import '
                                               'DefinedName\n'
                                               '        for entry in bindings.values():\n'
                                               '            if entry["name"] in '
                                               'worksheet.defined_names:\n'
                                               '                raise ValueError(\n'
                                               '                    f"defined name '
                                               "{entry['name']!r} already exists on "
                                               '{worksheet.title}")\n'
                                               '            worksheet.defined_names[entry["name"]] '
                                               '= DefinedName(\n'
                                               '                name=entry["name"], '
                                               'attr_text=entry["formula"])\n'
                                               '    header(bridge["distribution"])\n',
                                               '    emit(bridge["annual"], '
                                               '_chart_bridge_annual(bridge["annual"], results, '
                                               'raw, window))\n'
                                               '    header(bridge["distribution"])\n'),
                                              ('\n'
                                               'def _annual_extent_cell(results: dict[str, Any], '
                                               'extent: str) -> str:\n'
                                               '    """The Results annual state cell holding one '
                                               'stamped extent - `year_count`\n'
                                               '    for the applied year population - as a '
                                               '$-anchored address on its own sheet.\n'
                                               '    One resolution for the bridge guard and the '
                                               'applied-year chart names."""\n'
                                               '    annual = results["annual"]\n'
                                               '    row_key = f"{extent}_row"\n'
                                               '    if row_key not in annual:\n'
                                               '        raise ValueError(\n'
                                               '            f"the Results annual block declares no '
                                               '{row_key!r}; the applied-year "\n'
                                               '            f"binding cannot cut at an extent '
                                               'nobody publishes")\n'
                                               '    return '
                                               'f"${results[\'nominal_column\']}${int(annual[row_key])}"\n'
                                               '\n'
                                               '\n'
                                               '# CHART POLISH (final delivery). THE APPLIED-YEAR '
                                               'BINDING.\n'
                                               '#\n'
                                               '# The annual bridge block is written over the '
                                               'whole reserved window - the\n'
                                               '# structural year ceiling - and a chart bound to '
                                               'that window plots every one of\n'
                                               '# its category slots, so a ten-year project sits '
                                               'in the leftmost twentieth of\n'
                                               '# the axis with its labels on top of each other. '
                                               "The block's columns therefore\n"
                                               '# each get a SHEET-SCOPED DEFINED NAME on the '
                                               'bridge sheet whose formula is the\n'
                                               '# window range cut to the stamped year count:\n'
                                               '#\n'
                                               '#   Results!$H$279:INDEX(Results!$H$279:$H$478, '
                                               'MAX(1, MIN(200, N(years))))\n'
                                               '#\n'
                                               '# `years` is the same Results state cell the '
                                               'bridge guard reads, so the names\n'
                                               '# cut exactly where the guard turns the values to '
                                               'NA(); MIN keeps INDEX inside\n'
                                               '# the window for any count; MAX(1, N()) keeps a '
                                               'blank or NOT PRODUCED count on\n'
                                               '# one row - whose value is NA() and whose category '
                                               'is blank - so an empty\n'
                                               '# Dashboard still draws nothing. The names SELECT '
                                               'rows the block already holds;\n'
                                               '# no value is computed here and no second '
                                               'year-count authority exists.\n'
                                               'def applied_year_bindings(charts: dict[str, Any], '
                                               'results: dict[str, Any],\n'
                                               '                          window: int) -> '
                                               'dict[str, dict[str, str]] | None:\n'
                                               '    """Per annual bridge column: the defined name, '
                                               'its scope, its formula, the\n'
                                               '    reference a chart plots, the window range it '
                                               'cuts, and the extent cell.\n'
                                               '    None when the manifest declares no applied '
                                               'binding."""\n'
                                               '    block = charts["bridge"]["annual"]\n'
                                               '    binding = block.get("applied_binding")\n'
                                               '    if not binding:\n'
                                               '        return None\n'
                                               '    sheet = str(charts["bridge_sheet"])\n'
                                               '    first = int(block["first_row"])\n'
                                               '    last = first + int(window) - 1\n'
                                               '    extent = _annual_extent_cell(results, '
                                               'str(binding["extent"]))\n'
                                               '    prefix = str(binding["name_prefix"])\n'
                                               '    out: dict[str, dict[str, str]] = {}\n'
                                               '    for column in block["columns"]:\n'
                                               '        key = str(column["key"])\n'
                                               '        letter = str(column["column"])\n'
                                               '        name = f"{prefix}_{key}"\n'
                                               '        window_range = '
                                               'f"${letter}${first}:${letter}${last}"\n'
                                               '        out[key] = {\n'
                                               '            "name": name,\n'
                                               '            "scope": sheet,\n'
                                               '            "reference": f"{sheet}!{name}",\n'
                                               '            "window_range": '
                                               'f"{sheet}!{window_range}",\n'
                                               '            "extent_cell": f"{sheet}!{extent}",\n'
                                               '            # WHAT THE NAME SELECTS IN THE '
                                               'WORKBOOK AS BUILT, for the cache the\n'
                                               '            # chart part carries beside it. Stage '
                                               'A publishes no annual result,\n'
                                               '            # so the extent cell is blank, N() '
                                               'reads it as 0 and the MAX(1, ...)\n'
                                               '            # floor leaves exactly one selected '
                                               'row - a blank one. The cache\n'
                                               '            # therefore states one point and holds '
                                               'no value; Excel rewrites it\n'
                                               '            # from the plot on every save. This is '
                                               'not a second year-count\n'
                                               '            # authority: it is the floor of the '
                                               'one formula above, which the\n'
                                               '            # cache cannot contradict because it '
                                               'computes nothing.\n'
                                               '            "cached_points": 1,\n'
                                               '            "formula": '
                                               '(f"{sheet}!${letter}${first}:INDEX({sheet}!{window_range},"\n'
                                               '                        '
                                               'f"MAX(1,MIN({int(window)},N({sheet}!{extent}))))"),\n'
                                               '        }\n'
                                               '    return out\n'
                                               '\n'
                                               '\n'
                                               'def _chart_ranges(charts: dict[str, Any], window: '
                                               'int) -> dict[str, dict[str, Any]]:\n',
                                               '\n'
                                               'def _chart_ranges(charts: dict[str, Any], window: '
                                               'int) -> dict[str, dict[str, Any]]:\n'),
                                              ('                        for column in '
                                               'block["columns"]},\n'
                                               '            # The format each column declares, for '
                                               'the cache a named reference\n'
                                               '            # carries: a cache states the format '
                                               'of the data it holds.\n'
                                               '            "formats": {str(column["key"]): '
                                               'str(column["format"])\n'
                                               '                        for column in '
                                               'block["columns"]},\n'
                                               '        }\n',
                                               '                        for column in '
                                               'block["columns"]},\n'
                                               '        }\n'),
                                              ('\n'
                                               '# A REFERENCE INTO THE CHART PART, WITH THE CACHE '
                                               'EXCEL WRITES FOR A NAME.\n'
                                               '#\n'
                                               '# WINDOWS, FROM THE WORKBOOK BUILT AT a2da277. '
                                               'Both year charts came back from\n'
                                               '# Excel with an EMPTY second SERIES argument -\n'
                                               '#\n'
                                               '#     SERIES("Cumulative '
                                               'Nominal",,Results!chartAnnual_cumulative_nominal,1)\n'
                                               '#\n'
                                               '# - so the applied-year VALUE names survived and '
                                               'the applied-year CATEGORY name\n'
                                               '# did not. The markup was identical for both '
                                               'slots: `<c:numRef><c:f>` naming the\n'
                                               '# same kind of sheet-scoped name, and no '
                                               '`<c:numCache>` in either.\n'
                                               '#\n'
                                               '# WHY ONE SLOT AND NOT THE OTHER. Excel binds the '
                                               'two slots at different times.\n'
                                               "# A series' VALUES are re-bound when the workbook "
                                               'calculates, which is after\n'
                                               '# names are available, so a name there survives '
                                               'whatever the chart part cached.\n'
                                               '# The CATEGORY axis is built while the chart part '
                                               'is being read, before any\n'
                                               '# calculation: Excel resolves `c:cat` then and '
                                               'there. A literal area needs no\n'
                                               '# evaluation and resolves - which is why the '
                                               "histogram's and the tornado's\n"
                                               '# plain-range categories were never affected - but '
                                               'a defined name whose formula\n'
                                               '# is `$D$279:INDEX(...)` has to be EVALUATED to '
                                               'yield a range, and with no\n'
                                               '# cached data beside it Excel has neither a '
                                               'resolved reference nor anything to\n'
                                               '# draw. It drops the reference and numbers the '
                                               'categories 1, 2, 3 instead.\n'
                                               '#\n'
                                               '# THE CACHE IS WHAT EXCEL ITSELF WRITES, and '
                                               '`c:numRef` is defined as "a\n'
                                               '# reference to numeric data WITH A CACHE of the '
                                               'last values used" (ISO/IEC\n'
                                               '# 29500-1 §21.2.2.123). A chart built through '
                                               "Excel's own UI on a dynamic name -\n"
                                               '# the ordinary way this is done - carries one, '
                                               'which is why that chart keeps its\n'
                                               '# category binding across save and open and ours '
                                               'did not. So every reference\n'
                                               '# that names a bound range now carries the cache: '
                                               'the format code the bridge\n'
                                               '# column declares, and the point count the name '
                                               'selects in the workbook as\n'
                                               '# built. Nothing is fabricated - Stage A publishes '
                                               'no annual result, so the one\n'
                                               '# selected row is blank and the cache holds no '
                                               'point. Excel rewrites the cache\n'
                                               '# from the plot on every save.\n'
                                               '#\n'
                                               '# A PLAIN RANGE IS LEFT ALONE. It resolves without '
                                               'evaluation, it is what the\n'
                                               '# accepted charts have always carried, and adding '
                                               'a cache there would change a\n'
                                               '# reference that Windows has already proved '
                                               'survives.\n'
                                               'def _chart_reference(reference: str, cache: '
                                               'dict[str, Any] | None):\n'
                                               '    from openpyxl.chart.data_source import '
                                               'NumData, NumRef\n'
                                               '\n'
                                               '    item = NumRef(f=reference)\n'
                                               '    if cache is not None:\n'
                                               '        item.numCache = '
                                               'NumData(formatCode=str(cache["format_code"]),\n'
                                               '                                '
                                               'ptCount=int(cache["point_count"]))\n'
                                               '    return item\n'
                                               '\n'
                                               '\n'
                                               '# A SERIES OVER A REFERENCE THAT MAY BE A DEFINED '
                                               "NAME. openpyxl's Series\n"
                                               '# factory parses its argument as a cell range, '
                                               'which a name is not, so the\n'
                                               '# series is assembled from its parts: the value '
                                               'reference, the literal series\n'
                                               '# name, and the category reference - exactly what '
                                               'the factory builds for a\n'
                                               '# range, written the same way into the chart '
                                               'part.\n'
                                               'def _chart_series(values, title: str, '
                                               'categories):\n'
                                               '    from openpyxl.chart.data_source import '
                                               'AxDataSource, NumDataSource\n'
                                               '    from openpyxl.chart.series import Series, '
                                               'SeriesLabel\n'
                                               '\n'
                                               '    item = '
                                               'Series(val=NumDataSource(numRef=values), '
                                               'tx=SeriesLabel(v=title))\n'
                                               '    item.cat = AxDataSource(numRef=categories)\n'
                                               '    return item\n'
                                               '\n'
                                               '\n'
                                               'def _render_dashboard_charts(worksheet: Worksheet, '
                                               'charts: dict[str, Any],\n',
                                               '\n'
                                               'def _render_dashboard_charts(worksheet: Worksheet, '
                                               'charts: dict[str, Any],\n'),
                                              ('                             results: dict[str, '
                                               'Any], window: int) -> None:\n'
                                               '    from openpyxl.chart import BarChart, '
                                               'LineChart\n',
                                               '                             window: int) -> '
                                               'None:\n'
                                               '    from openpyxl.chart import BarChart, '
                                               'LineChart, Series\n'),
                                              ('    ranges = _chart_ranges(charts, window)\n'
                                               '    bindings = applied_year_bindings(charts, '
                                               'results, window) or {}\n'
                                               '    formats = charts["number_formats"]\n',
                                               '    ranges = _chart_ranges(charts, window)\n'
                                               '    formats = charts["number_formats"]\n'),
                                              ('        first, last = int(block["first_row"]), '
                                               'int(block["last_row"])\n'
                                               '        bound = bindings if str(spec["source"]) == '
                                               '"annual" else {}\n'
                                               '\n'
                                               '        # WHAT ONE COLUMN IS PLOTTED THROUGH: its '
                                               'applied-year name where the\n'
                                               '        # block declares one, its whole window '
                                               'range otherwise. Spelled with\n'
                                               '        # its sheet either way, because an '
                                               'openpyxl reference without one\n'
                                               "        # resolves against the chart's OWN sheet - "
                                               'the Dashboard - which holds\n'
                                               '        # none of this data. A NAME ALSO CARRIES '
                                               'THE CACHE Excel writes for\n'
                                               '        # one, without which Excel drops the '
                                               'reference while it reads the part;\n'
                                               '        # a plain range resolves without '
                                               'evaluation and carries none.\n'
                                               '        def reference(key: str):\n'
                                               '            if key in bound:\n'
                                               '                return '
                                               '_chart_reference(f"\'{sheet}\'!{bound[key][\'name\']}",\n'
                                               '                                        '
                                               '{"format_code": formats[block["formats"][key]],\n'
                                               '                                         '
                                               '"point_count": bound[key]["cached_points"]})\n'
                                               '            column = block["columns"][key]\n'
                                               '            return _chart_reference(\n'
                                               '                '
                                               'f"\'{sheet}\'!${column}${first}:${column}${last}", '
                                               'None)\n'
                                               '\n',
                                               '        first, last = int(block["first_row"]), '
                                               'int(block["last_row"])\n'
                                               '\n'),
                                              ('        categories = '
                                               'reference(str(spec["categories"]))\n',
                                               '        # THE RANGE IS SPELLED WITH ITS SHEET, '
                                               'always. An openpyxl Reference\n'
                                               '        # built without a worksheet resolves '
                                               "against the chart's OWN sheet -\n"
                                               '        # the Dashboard - which holds none of this '
                                               'data, so every range below\n'
                                               '        # is an explicit string naming the bridge '
                                               'sheet.\n'),
                                              ('            item = '
                                               '_chart_series(reference(str(series["key"])), '
                                               'str(series["name"]),\n'
                                               '                                 categories)\n',
                                               '            column = '
                                               'block["columns"][str(series["key"])]\n'
                                               '            item = '
                                               'Series(f"\'{sheet}\'!${column}${first}:${column}${last}",\n'
                                               '                          '
                                               'title=str(series["name"]))\n'),
                                              ('            chart.series.append(item)\n\n',
                                               '            chart.series.append(item)\n'
                                               '\n'
                                               '        category_column = '
                                               'block["columns"][str(spec["categories"])]\n'
                                               '        chart.set_categories(\n'
                                               '            '
                                               'f"\'{sheet}\'!${category_column}${first}:${category_column}${last}")\n'
                                               '\n'),
                                              ('        chart.dispBlanksAs = '
                                               'str(axes["display_blanks_as"])\n'
                                               '        # CHART POLISH (final delivery). A '
                                               'DECLARED VALUE-AXIS STEP, and NO\n'
                                               '        # BOUNDS. `y_axis` is the VALUE axis for '
                                               'every chart type here; on the\n'
                                               '        # horizontal bar it is the axis Excel '
                                               'draws along the bottom, so this is\n'
                                               '        # the tornado\'s "x-axis" step as a reader '
                                               'sees it: <c:valAx><c:majorUnit/>.\n'
                                               '        # <c:scaling> is left with its orientation '
                                               'alone - no <c:min/>, no\n'
                                               '        # <c:max/> - so Excel reads the extent off '
                                               'the plotted values. The\n'
                                               '        # tornado ranks by |rho| and plots SIGNED '
                                               'rho: a minimum of 0 would have\n'
                                               '        # hidden a top-ranked negative driver and '
                                               'a maximum would have clipped a\n'
                                               '        # stronger one, which is a presentation '
                                               'setting deciding what a reader\n'
                                               '        # sees of a published analytical value.\n'
                                               '        scale = spec.get("value_axis_scale")\n'
                                               '        if scale:\n'
                                               '            chart.y_axis.majorUnit = '
                                               'float(scale["major_unit"])\n'
                                               '        # AND A CATEGORY LABEL INTERVAL, where one '
                                               'is declared: every n-th\n'
                                               '        # caption is printed '
                                               '(<c:catAx><c:tickLblSkip/>). Which captions are\n'
                                               '        # printed, not what is plotted - every '
                                               'category and every value stays.\n'
                                               '        interval = '
                                               'spec.get("category_label_interval")\n'
                                               '        if interval:\n'
                                               '            chart.x_axis.tickLblSkip = '
                                               'int(interval)\n'
                                               '        worksheet.add_chart(chart, '
                                               'str(spec["anchor"]))\n',
                                               '        chart.dispBlanksAs = '
                                               'str(axes["display_blanks_as"])\n'
                                               '        worksheet.add_chart(chart, '
                                               'str(spec["anchor"]))\n')),
 'spec/workbook.yaml': (('      rho: "0.000"\n'
                         "      # CHART POLISH (final delivery). The tornado's VALUE AXIS reads "
                         'two\n'
                         '      # decimals; the bridge cells behind it keep `rho` at three. An '
                         'axis label\n'
                         '      # is a tick, not a published value, and 0.00 is the resolution a '
                         'reader\n'
                         '      # compares bars at.\n'
                         '      rho_axis: "0.00"\n'
                         '      text: "General"\n',
                         '      rho: "0.000"\n      text: "General"\n'),
                        ('      # DELIBERATELY NOT SET HERE: a tick-label interval for the YEAR '
                         'axes. A\n'
                         '      # build-time skip chosen against the 200-column ceiling would hide '
                         'four\n'
                         '      # labels in five on a ten-year project. The year axes are instead '
                         'bound to\n'
                         '      # the APPLIED year population (bridge.annual.applied_binding '
                         'below), so\n'
                         "      # Excel's automatic interval reads a plot that holds only real "
                         'years. The\n'
                         '      # histogram is the one axis whose population is FIXED at build '
                         'time - the\n'
                         '      # declared bin count - so it, and only it, carries a declared '
                         'interval on\n'
                         '      # its own chart entry (category_label_interval).\n',
                         '      # DELIBERATELY NOT SET: a tick-label interval. A build-time skip '
                         'would have\n'
                         '      # to be chosen against the 200-column ceiling and would then hide '
                         'four\n'
                         '      # labels in five on a ten-year project, which is a worse chart '
                         'than the one\n'
                         "      # it fixes. Excel's automatic interval reads the rendered width at "
                         'open\n'
                         '      # time and is the only thing that can know; enlarging the plot and '
                         'shrinking\n'
                         '      # the label font is how this batch makes that automatic choice a '
                         'good one.\n'),
                        ('        note: "The published annual profile, bounded by the stamped year '
                         'count, plus its running total. NA() past the last stamped year and '
                         'whenever no annual result is produced."\n'
                         '        # CHART POLISH (final delivery). THE APPLIED-YEAR BINDING. The '
                         'block\n'
                         '        # below is written over the whole reserved window - 200 rows, '
                         'the\n'
                         '        # structural year ceiling - and a chart bound to the whole '
                         'window plots\n'
                         '        # 200 category slots, of which a ten-year project fills ten: the '
                         'real\n'
                         '        # years crowd the far left and the labels overlap. Each column '
                         'of this\n'
                         '        # block therefore also gets a SHEET-SCOPED DEFINED NAME on the '
                         'bridge\n'
                         "        # sheet, `<name_prefix>_<key>`, whose formula is the column's "
                         'window\n'
                         '        # range cut to the applied year count:\n'
                         '        #\n'
                         '        #   Results!$H$279:INDEX(Results!$H$279:$H$478, MAX(1, MIN(200, '
                         'N(years))))\n'
                         '        #\n'
                         '        # and the two year charts plot THOSE names. `years` is the '
                         'Results annual\n'
                         '        # state row the bridge guard already reads (`extent`, the '
                         'stamped year\n'
                         '        # count) - the ONE year-count authority, not a second - so the '
                         'names cut\n'
                         '        # exactly where the guard turns the values to NA(). MIN keeps '
                         'INDEX\n'
                         '        # inside the window; MAX(1, N()) keeps a blank or NOT PRODUCED '
                         'count on\n'
                         '        # one row, whose value is NA() and whose category is blank, so '
                         'an empty\n'
                         '        # Dashboard still draws nothing. No value moves: the names '
                         'SELECT rows\n'
                         '        # this block already holds.\n'
                         '        applied_binding:\n'
                         '          name_prefix: "chartAnnual"\n'
                         '          extent: "year_count"\n'
                         '        columns:\n',
                         '        note: "The published annual profile, bounded by the stamped year '
                         'count, plus its running total. NA() past the last stamped year and '
                         'whenever no annual result is produced."\n'
                         '        columns:\n'),
                        ('        # CHART POLISH (final delivery): renamed from "Cumulative '
                         'Cost".\n'
                         '        title: "Cumulative Cost Profile"\n',
                         '        title: "Cumulative Cost"\n'),
                        ('          - {key: "count", name: "Iterations"}\n'
                         '        # CHART POLISH (final delivery). Twenty bin-edge labels in a '
                         'compact\n'
                         '        # money format crowd an 18 cm axis; every second label is shown. '
                         'The\n'
                         '        # bins, their edges and their counts are untouched - this '
                         'decides which\n'
                         '        # of the twenty captions are PRINTED, nothing about what is '
                         'plotted.\n'
                         '        category_label_interval: 2\n'
                         "        # THE PUBLISHED SIMULATION'S OWN STATE, not the annual "
                         "product's. The\n",
                         '          - {key: "count", name: "Iterations"}\n'
                         "        # THE PUBLISHED SIMULATION'S OWN STATE, not the annual "
                         "product's. The\n"),
                        ('        value_axis_format: "rho_axis"\n',
                         '        value_axis_format: "rho"\n'),
                        ('        category_axis_format: "text"\n'
                         '        # CHART POLISH (final delivery). THE VALUE AXIS CARRIES A STEP '
                         'AND A\n'
                         '        # FORMAT, AND NO BOUNDS. In openpyxl - and in the chart part - '
                         'the value\n'
                         '        # axis of a horizontal bar chart is `y_axis` / <c:valAx>, drawn\n'
                         '        # HORIZONTALLY on screen, so "the x-axis" a reader sees is this '
                         "axis's\n"
                         '        # <c:majorUnit> and, where one is declared, its <c:scaling> '
                         'min/max.\n'
                         '        #\n'
                         '        # WHY NO MINIMUM AND NO MAXIMUM. The tornado RANKS by |rho| and '
                         'PLOTS\n'
                         '        # signed rho, so a strongly negative driver ranks alongside an '
                         'equally\n'
                         '        # strong positive one and is drawn to the left of zero. A '
                         'declared\n'
                         '        # minimum of 0 would have hidden that bar, and a declared '
                         'maximum would\n'
                         '        # have clipped any |rho| above it - a presentation setting '
                         'deciding what\n'
                         "        # a reader can see of a published analytical value. Excel's "
                         'automatic\n'
                         '        # bounds read the data that is actually there, so every ranked '
                         'driver is\n'
                         '        # visible whatever its sign or magnitude. The STEP is safe to '
                         'declare\n'
                         '        # because it divides whatever range Excel chooses; it fixes no '
                         'extent.\n'
                         '        value_axis_scale:\n'
                         '          major_unit: 0.10\n'
                         '        # Fractions of the CHART area, edge-anchored: the plot starts '
                         '34% in and\n',
                         '        category_axis_format: "text"\n'
                         '        # Fractions of the CHART area, edge-anchored: the plot starts '
                         '34% in and\n'))}


def chart_polish_touches(path: str) -> bool:
    return path in _HUNKS


def strip_chart_polish(path: str, text: str) -> str:
    """`text` with the chart polish removed - all or none, exactly as the VBA
    layers: none of the fragments present returns the text unchanged, all of
    them present takes the layer off exactly, some of them raises."""
    hunks = _HUNKS.get(path, ())
    if not hunks:
        return text
    # PRESENT means the current fragment is there and the accepted one is not
    # - unless the hunk only ADDS lines, in which case its accepted fragment
    # is context that the current fragment contains. A hunk that only
    # REMOVES lines has a current fragment made of context, which the
    # accepted text carries too, around the lines it still has; there the
    # accepted fragment must be absent.
    present = [text.count(current) == 1
               and (text.count(accepted) == 0 or accepted in current)
               for current, accepted in hunks]
    if not any(present):
        return text
    if not all(present):
        missing = [index for index, found in enumerate(present) if not found]
        raise AssertionError(
            f"{path}: the chart polish is partly present (fragments {missing} absent); "
            "an undeclared edit sits inside the declared layer")
    for current, accepted in hunks:
        text = text.replace(current, accepted)
    return text


def undeclared_after_chart_polish(commit: str, changed: list[str], pccm_root) -> list[str]:
    """`changed` (pccm/-prefixed paths from `git diff --name-only commit`) with
    the declared chart-polish files taken out - after proving each reverses to
    `commit`'s bytes exactly, the reversal applied to BOTH sides so a pin that
    sits before or after the polish still compares the trees beneath it."""
    import subprocess
    from pathlib import Path as _Path
    root = _Path(pccm_root)
    polished = {f"pccm/{name}" for name in DECLARED_CHART_POLISH_CHANGES}
    for path in sorted(set(changed) & polished):
        name = path[len("pccm/"):]
        current = strip_chart_polish(name, (root / name).read_text(encoding="utf-8"))
        accepted = subprocess.run(["git", "show", f"{commit}:{path}"], cwd=root.parent,
                                  check=True, stdout=subprocess.PIPE).stdout.decode("utf-8")
        accepted = strip_chart_polish(name, accepted)
        assert current == accepted, f"{path} moved outside the declared chart polish"
    return [path for path in changed if path not in polished]
