#!/usr/bin/env python3
"""PCCM Phase 6 Step 13: STATIC tests over the Windows Gate-B harness extension.

NO WINDOWS RUN HAPPENS HERE, AND NONE CAN. Linux has no Excel and no PowerShell
host; every assertion below is a statement about SOURCE TEXT and about the
artefacts the Stage-A builder emits. Nothing here starts a COM session, drives a
workbook, or claims that any VBA has executed.

    static/source evidence  !=  Windows/Excel runtime evidence

What this file DOES establish:

  * the accepted Phase-4/Phase-5 harness files are BYTE-IDENTICAL to the
    production baseline, except `phase4_functional_test.ps1`, whose only change
    is the authorised Phase-6 wiring;
  * the Phase-6 scenario file restates no `_SimData` address, no defined name
    and no expected simulation value: every one comes from
    `build/phase6_gate_b_inspection.json` or `build/phase6_gate_b_cases.json`;
  * every address in the inspection projection agrees with the generated
    `modSimContract.bas` / `modConstants.bas`, and its sheet agrees with the
    generated Stage-A workbook;
  * the three failpoint stage names and the seven public procedure names the
    harness spells are CHECKED COPIES of the production/contract authority;
  * the parity corpus is generated by the accepted oracle, binds each case to an
    existing Phase-5 plan case, and covers the four sampling mechanisms;
  * the scenario matrix is complete, fail-closed, and records one result per ID.

What it does NOT establish is anything about behaviour. Whether Excel agrees is
Gate B's, on Windows, and that run has not been made.

Runs standalone or under pytest.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

PCCM_ROOT = Path(__file__).resolve().parent.parent
REPO_ROOT = PCCM_ROOT.parent
sys.path.insert(0, str(PCCM_ROOT / "builder"))

from pccm_builder import load_contract, load_sim_contract  # noqa: E402
from pccm_builder.calc_cases import CASES as PLAN_CASES  # noqa: E402
from pccm_builder.calc_loader import load_calc_contract  # noqa: E402
from pccm_builder.sim_cases import (  # noqa: E402
    GATE_B_ITERATIONS,
    GATE_B_PARITY_PLAN_CASES,
    GATE_B_SUPPLIED_SEED,
)
from pccm_builder.sim_inspection import (  # noqa: E402
    ALLOWED_BLOCK_KEYS,
    ALLOWED_CONTROL_KEYS,
    ALLOWED_IDENTITY_KEYS,
    ALLOWED_ITERATION_KEYS,
    ALLOWED_PENDING_KEYS,
    ALLOWED_PUBLICATION_KEYS,
    ALLOWED_ROOT_KEYS,
    ALLOWED_SIM_DATA_KEYS,
    ALLOWED_SURFACE_KEYS,
    build_sim_inspection,
)

BOOTSTRAP = PCCM_ROOT / "bootstrap" / "windows"
HARNESS = BOOTSTRAP / "phase4_functional_test.ps1"
PHASE5 = BOOTSTRAP / "phase5_gate_b_scenarios.ps1"
PHASE6 = BOOTSTRAP / "phase6_gate_b_scenarios.ps1"
LIFECYCLE = BOOTSTRAP / "com_lifecycle.ps1"
DIAGNOSTIC = BOOTSTRAP / "phase5_gate_b_diagnostics.bas"
BUILD_STAGE_B = BOOTSTRAP / "build_stage_b.ps1"

SRC_VBA = PCCM_ROOT / "src" / "vba"
SPEC = PCCM_ROOT / "spec"
BUILD = PCCM_ROOT / "build"

INSPECTION_PATH = BUILD / "phase6_gate_b_inspection.json"
GATE_B_CASES_PATH = BUILD / "phase6_gate_b_cases.json"

# The production baseline this harness is evidence infrastructure FOR. Named,
# never inferred: a runtime result is attributable to a commit or it is worth
# nothing.
PRODUCTION_BASELINE = "bc7949b"

_CACHE: dict[str, object] = {}


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------
def _text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _inspection() -> dict:
    if "inspection" not in _CACHE:
        _CACHE["inspection"] = json.loads(_text(INSPECTION_PATH))
    return _CACHE["inspection"]  # type: ignore[return-value]


def _cases() -> dict:
    if "cases" not in _CACHE:
        _CACHE["cases"] = json.loads(_text(GATE_B_CASES_PATH))
    return _CACHE["cases"]  # type: ignore[return-value]


def _sim_constants() -> dict[str, str]:
    """`SIM_*` and `NM_*` constants, as written by the generator."""
    if "constants" not in _CACHE:
        found: dict[str, str] = {}
        for module in ("modSimContract.bas", "modConstants.bas"):
            for line in _text(BUILD / "vba" / module).splitlines():
                match = re.match(
                    r"Public Const (\w+) As \w+ = (.+?)(?:\s+'.*)?$", line.strip()
                )
                if match:
                    found[match.group(1)] = match.group(2).strip().strip('"')
        _CACHE["constants"] = found
    return _CACHE["constants"]  # type: ignore[return-value]


def _executable(path: Path) -> str:
    """PowerShell source with the block comment and every `#` line removed.

    A rule about what the harness may not RESTATE has to be checked against what
    it EXECUTES. Prose that explains why an address is not spelled here would
    otherwise trip the rule that it is not spelled here.
    """
    body = re.sub(r"<#.*?#>", "", _text(path), flags=re.S)
    return "\n".join(
        line for line in body.splitlines() if not line.lstrip().startswith("#")
    )


def _git_show(revision: str, relative: str) -> bytes:
    return subprocess.run(
        ["git", "show", f"{revision}:{relative}"],
        cwd=REPO_ROOT, check=True, stdout=subprocess.PIPE,
    ).stdout


# ===========================================================================
# 1. THE ACCEPTED HARNESS IS NOT REWRITTEN
# ===========================================================================
def _accepted_lines(path: Path) -> list[str]:
    relative = path.relative_to(REPO_ROOT).as_posix()
    return _git_show(PRODUCTION_BASELINE, relative).decode("utf-8").splitlines()


def _current_lines(path: Path) -> list[str]:
    return _text(path).splitlines()


def test_01_the_phase4_and_phase5_harness_files_are_byte_identical() -> None:
    """Step 13 is an extension. Four accepted files may not move at all.

    `git show` against the production baseline, not a hash written down here: a
    pinned digest would have to be updated by hand and the update is exactly the
    thing that would go unnoticed.

    Compared as LINES, not raw bytes: `.gitattributes` declares `*.ps1` as
    `eol=crlf`, so git stores LF and a checkout holds CRLF. That difference is
    packaging, and `splitlines` is blind to it while remaining exact about
    every character that is not a line terminator.
    """
    for path in (PHASE5, LIFECYCLE, DIAGNOSTIC, BUILD_STAGE_B):
        assert _current_lines(path) == _accepted_lines(path), (
            f"{path.name} moved from {PRODUCTION_BASELINE}"
        )


def test_02_the_only_change_to_the_phase4_driver_is_the_phase6_wiring() -> None:
    """One dot-source, one preflight, two artefact loads, one call. Nothing else."""
    before = _accepted_lines(HARNESS)
    after = _current_lines(HARNESS)

    # EXACTLY ONE ACCEPTED LINE MAY BE MODIFIED, and it is named here rather
    # than tolerated by a count: the required-artefact list gained the two
    # Phase-6 paths. Any OTHER removal is a rewrite of accepted Phase-4/5
    # behaviour and fails.
    extended = (
        "    foreach ($required in @($manifestPath, $scenarioPath, $casesPath, "
        "$inspectPath)) {"
    )
    removed = [line for line in before if line not in after]
    assert removed == [extended], f"the Phase-4 driver lost lines: {removed[:5]}"
    assert any(
        ("$simInspectPath" in line and "$simCasesPath" in line) for line in after
    ), "the required-artefact list does not name the two Phase-6 artefacts"

    added = "\n".join(line for line in after if line not in before)
    assert "phase6_gate_b_scenarios.ps1" in added
    assert "Invoke-Phase6CoveragePreflight" in added
    assert "Invoke-Phase6GateBScenarios" in added
    assert "phase6_gate_b_inspection.json" in added
    assert "phase6_gate_b_cases.json" in added
    # AND NOTHING PHASE-5 OR PHASE-4 WAS REWRITTEN IN THE PROCESS.
    for forbidden in ("Invoke-Phase5GateBScenarios -", "Get-Phase4RequiredScenarioIds ="):
        assert forbidden not in added, forbidden


def test_03_the_phase6_block_starts_nothing_of_its_own() -> None:
    """It runs inside the Phase-4 COM lifecycle. It does not build a second one."""
    code = _executable(PHASE6)
    for forbidden in ("New-Object -ComObject", "Excel.Application", "New-ReleaseLedger",
                      "build_stage_b.ps1", ".Quit(", "Stop-Process", "$excel.Workbooks"):
        assert forbidden not in code, f"the Phase-6 block must not use {forbidden}"


def test_04_no_production_or_phase5_authority_is_written() -> None:
    """Evidence infrastructure only: it changes no production file."""
    changed = subprocess.run(
        ["git", "diff", "--name-only", PRODUCTION_BASELINE, "--",
         "pccm/src", "pccm/spec"],
        cwd=REPO_ROOT, check=True, stdout=subprocess.PIPE,
    ).stdout.decode("utf-8").strip()
    assert changed == "", f"production authority moved: {changed}"


# ===========================================================================
# 2. THE HARNESS RESTATES NO ADDRESS
# ===========================================================================
def test_05_no_a1_address_literal_appears_in_executable_code() -> None:
    """Every cell the harness touches is named by the projection, never spelled.

    A quoted A1 reference in executable PowerShell would be a SECOND reader of
    the `_SimData` layout, which is the whole reason the projection exists.
    """
    code = _executable(PHASE6)
    literals = re.findall(
        r"""['"]([A-Z]{1,2}[0-9]{1,5}(?::[A-Z]{1,2}[0-9]{1,5})?)['"]""", code
    )
    assert literals == [], f"restated addresses: {sorted(set(literals))}"
    assert not re.search(r"\.Range\(\s*['\"]", code), (
        "a Range call was given a literal address"
    )


def test_06_no_sheet_or_defined_name_is_restated() -> None:
    code = _executable(PHASE6)
    sheet = _inspection()["sim_data"]["sheet"]
    assert f"'{sheet}'" not in code and f'"{sheet}"' not in code, (
        "the _SimData sheet name is spelled in executable code"
    )
    for control in _inspection()["controls"].values():
        assert control["defined_name"] not in code, control["defined_name"]
    assert "$Inspection.sim_data.sheet" in code or "SimInspection" in code


def test_07_no_identity_row_number_is_restated() -> None:
    """Rows are asked for by MEANING. A bare row integer would be a second copy."""
    code = _executable(PHASE6)
    rows = _inspection()["sim_data"]["run_identity"]["rows"]
    for key, row in rows.items():
        if row < 10:
            # A single digit is shared with every count and index in the file,
            # and cannot build an address on its own: a literal A1 reference and
            # a quoted column letter are both already refused above, so there is
            # nothing for a bare 8 to be concatenated with.
            continue
        # `(?<![\w.\-])` so "Step-13" is not read as the row 13.
        assert not re.search(rf"(?<![\w.\-]){row}(?![\w.\-])", code), (
            f"the row number {row} ({key}) is restated in executable code"
        )


def test_08_no_bank_column_letter_is_restated() -> None:
    code = _executable(PHASE6)
    columns = _inspection()["sim_data"]["run_identity"]["bank_value_columns"]
    for bank, column in columns.items():
        assert f"'{column}'" not in code, (
            f"bank {bank}'s column letter {column} is spelled in executable code"
        )


def test_09_no_expected_simulation_value_is_restated() -> None:
    """Every digest, seed and ladder value comes from the corpus."""
    code = _executable(PHASE6)
    for case in _cases()["parity_cases"]:
        expected = case["expected_exact"]
        assert expected["result_digest"] not in code, expected["result_digest"]
        if "calculation_fingerprint" in expected:
            assert expected["calculation_fingerprint"] not in code
            assert expected["request_fingerprint"] not in code
    # No 16-character hex token of any kind, so a future digest cannot be pasted.
    assert re.findall(r"\b[0-9A-F]{16}\b", code) == []
    for bound in _cases()["bounds"].values():
        if int(bound) in (0, 1, 2):
            continue
        assert not re.search(rf"(?<![\w.]){bound}(?![\w.])", code), (
            f"the bound {bound} is restated in executable code"
        )


def test_10_there_is_no_recomputation_and_no_fallback() -> None:
    """A harness that could compute the expectation could disagree with the oracle."""
    code = _executable(PHASE6)
    for forbidden in ("[math]::", "Measure-Object -Average", "Get-Random",
                      "tolerance", "Tolerance", "-lt 1e-", "AbsoluteDifference"):
        assert forbidden not in code, f"the harness must not contain {forbidden}"
    assert "Test-SimExactDouble" in code and "Test-SimExactText" in code


# ===========================================================================
# 3. CHECKED COPIES, NOT SECOND DECLARATIONS
# ===========================================================================
def test_11_the_three_failpoint_names_match_production() -> None:
    """They are declared in VBA, so VBA stays the authority and this is a copy."""
    code = _executable(PHASE6)
    declared = {}
    for module in ("modSimNonce.bas", "modSimReport.bas"):
        for line in _text(SRC_VBA / module).splitlines():
            match = re.match(
                r'Public Const (FAILPOINT_SIM_\w+) As String = "([^"]+)"', line.strip()
            )
            if match:
                declared[match.group(1)] = match.group(2)
    assert set(declared) == {
        "FAILPOINT_SIM_AFTER_NONCE", "FAILPOINT_SIM_CANDIDATE_BANK",
        "FAILPOINT_SIM_FINAL_COMMIT",
    }, declared
    for name in declared.values():
        assert f"'{name}'" in code, f"the harness never names the failpoint {name}"
    # AND NAMES NOTHING ELSE THAT LOOKS LIKE ONE.
    harness_names = set(re.findall(r"'(Phase6\w+)'", code))
    assert harness_names == set(declared.values()), harness_names


def test_12_the_public_surface_the_harness_spells_is_the_contract_s() -> None:
    """P6-ACC must name each accessor: their semantics differ, so a loop cannot."""
    code = _executable(PHASE6)
    surface = _inspection()["command_surface"]
    for name in surface["read_accessors"]:
        assert f"'{name}'" in code, f"P6-ACC never calls {name}"
    # The endpoint is invoked through the projection, never by a spelled name.
    assert f"'{surface['automation_endpoint']}'" in code
    spelled = set(re.findall(r"'(PCCM_\w+)'", code))
    accepted = set(surface["read_accessors"]) | {surface["automation_endpoint"]}
    # The Phase-4/5 automation helpers the block legitimately reuses.
    accepted |= {"PCCM_AutomationBegin", "PCCM_AutomationResult", "PCCM_Calculate",
                 "PCCM_CalculationFingerprint"}
    assert spelled <= accepted, sorted(spelled - accepted)


def test_13_the_calculation_fingerprint_accessor_is_a_phase5_endpoint() -> None:
    """The golden analytical binding calls Phase 5's own accessor, not a copy."""
    import yaml
    structure = yaml.safe_load(_text(SPEC / "structure_contract.yaml"))
    assert "PCCM_CalculationFingerprint" in structure["vba"]["api_procedures"]


# ===========================================================================
# 4. THE INSPECTION PROJECTION AGREES WITH THE GENERATED AUTHORITY
# ===========================================================================
def test_14_the_projection_is_generated_not_handwritten() -> None:
    sim = load_sim_contract(SPEC / "sim_contract.yaml")
    contract = load_contract(SPEC / "input_contract.yaml")
    assert build_sim_inspection(sim, contract) == _inspection(), (
        "build/phase6_gate_b_inspection.json is not what the builder emits"
    )


def test_15_every_key_is_on_the_positive_allowlist() -> None:
    """An allowlist refuses the next semantic value too, whatever it is called."""
    inspection = _inspection()
    assert tuple(inspection) == ALLOWED_ROOT_KEYS, tuple(inspection)
    assert tuple(inspection["sim_data"]) == ALLOWED_SIM_DATA_KEYS
    assert tuple(inspection["sim_data"]["run_identity"]) == ALLOWED_IDENTITY_KEYS
    assert tuple(inspection["sim_data"]["pending_auto_nonce"]) == ALLOWED_PENDING_KEYS
    assert tuple(inspection["sim_data"]["iteration_records"]) == ALLOWED_ITERATION_KEYS
    for block in ("summary_statistics", "contingency_ladder"):
        assert tuple(inspection["sim_data"][block]) == ALLOWED_BLOCK_KEYS, block
    assert tuple(inspection["publication"]) == ALLOWED_PUBLICATION_KEYS
    assert tuple(inspection["command_surface"]) == ALLOWED_SURFACE_KEYS
    for control in inspection["controls"].values():
        assert tuple(control) == ALLOWED_CONTROL_KEYS


def test_16_the_projection_carries_no_expected_value_and_no_vocabulary() -> None:
    """Identities only. Bounds and label sets belong to the expectation corpus."""
    flat = json.dumps(_inspection())
    for semantic in ("SUCCESS", "REFUSED", "FAILED", "AUTO_NONCE_INDETERMINATE",
                     "CURRENT", "STALE", "INVALID", "tolerance", "minimum_iterations",
                     "run_id_maximum", "PERSISTENCE_INDETERMINATE"):
        assert semantic not in flat, f"the projection carries the semantic {semantic}"


def test_17_every_identity_row_matches_the_generated_module() -> None:
    constants = _sim_constants()
    rows = _inspection()["sim_data"]["run_identity"]["rows"]
    for key, row in rows.items():
        name = "SIM_IDENTITY_ROW_" + key.upper()
        assert name in constants, name
        assert int(constants[name]) == row, f"{name}: {constants[name]} != {row}"
    assert len(rows) == 23, len(rows)


def test_18_the_columns_the_sidecar_and_the_commit_range_match() -> None:
    constants = _sim_constants()
    sim_data = _inspection()["sim_data"]
    identity = sim_data["run_identity"]
    assert identity["label_column"] == constants["SIM_IDENTITY_LABEL_COLUMN"]
    assert identity["value_column"] == constants["SIM_IDENTITY_VALUE_COLUMN"]
    assert identity["value_column"] == constants["SIM_SHARED_VALUE_COLUMN"]
    assert identity["bank_value_columns"]["A"] == constants["SIM_SNAPSHOT_COLUMN_A"]
    assert identity["bank_value_columns"]["B"] == constants["SIM_SNAPSHOT_COLUMN_B"]
    assert int(identity["first_row"]) == int(constants["SIM_IDENTITY_FIRST_ROW"])
    assert int(identity["last_row"]) == int(constants["SIM_IDENTITY_LAST_ROW"])
    assert sim_data["pending_auto_nonce"]["cell"] == constants["SIM_PENDING_AUTO_NONCE_CELL"]
    assert (_inspection()["publication"]["final_commit_range"]
            == constants["SIM_FINAL_COMMIT_RANGE"])


def test_19_the_iteration_summary_and_contingency_geometry_match() -> None:
    constants = _sim_constants()
    sim_data = _inspection()["sim_data"]
    iteration = sim_data["iteration_records"]
    assert int(iteration["header_row"]) == int(constants["SIM_DATA_HEADER_ROW"])
    assert (int(iteration["first_iteration_row"])
            == int(constants["SIM_DATA_FIRST_ITERATION_ROW"]))
    for bank, suffix in (("A", "A"), ("B", "B")):
        for key in ("iteration_index", "total_nominal", "total_pv"):
            name = f"SIM_ITER_{suffix}_{key.upper()}_COLUMN"
            assert iteration["banks"][bank][key] == constants[name], name
    summary = sim_data["summary_statistics"]
    assert summary["label_column"] == constants["SIM_SUMMARY_LABEL_COLUMN"]
    assert summary["bank_value_columns"]["A"]["nominal"] == constants["SIM_SUMMARY_A_NOMINAL_COLUMN"]
    assert summary["bank_value_columns"]["B"]["pv"] == constants["SIM_SUMMARY_B_PV_COLUMN"]
    for key, row in summary["rows"].items():
        assert int(constants["SIM_SUMMARY_ROW_" + key.upper()]) == row, key
    contingency = sim_data["contingency_ladder"]
    assert contingency["label_column"] == constants["SIM_CONTINGENCY_LABEL_COLUMN"]
    for key, row in contingency["rows"].items():
        assert int(constants["SIM_CONTINGENCY_ROW_" + key.upper()]) == row, key


def test_20_the_controls_match_the_generated_defined_names() -> None:
    constants = _sim_constants()
    controls = _inspection()["controls"]
    assert (controls["monte_carlo_iterations"]["defined_name"]
            == constants["NM_INPUT_MONTE_CARLO_ITERATIONS"])
    assert controls["random_seed"]["defined_name"] == constants["NM_INPUT_RANDOM_SEED"]
    for control in controls.values():
        assert control["sheet"] == "Setup"
        assert re.fullmatch(r"[A-Z]{1,2}[0-9]{1,4}", control["cell"]), control["cell"]


def test_21_the_projected_sheet_exists_in_the_generated_workbook() -> None:
    """The address authority and the workbook the harness drives must agree."""
    import openpyxl
    workbook = openpyxl.load_workbook(BUILD / "PCCM_stageA.xlsx", read_only=True)
    try:
        sheet_name = _inspection()["sim_data"]["sheet"]
        assert sheet_name in workbook.sheetnames, workbook.sheetnames
        assert (workbook[sheet_name].sheet_state
                == _inspection()["sim_data"]["required_visibility"])
    finally:
        workbook.close()


def test_22_the_command_surface_matches_the_contract_and_the_module() -> None:
    sim = load_sim_contract(SPEC / "sim_contract.yaml")
    surface = _inspection()["command_surface"]
    block = sim.raw["command_surface"]
    assert surface["automation_endpoint"] == block["automation_endpoint"]
    assert surface["read_accessors"] == list(block["read_accessors"])
    constants = _sim_constants()
    assert int(constants["SIM_READ_ACCESSOR_COUNT"]) == len(surface["read_accessors"])
    for index, name in enumerate(surface["read_accessors"], start=1):
        assert constants[f"SIM_READ_ACCESSOR_{index}"] == name
    # AND THE PROCEDURES EXIST IN THE PRODUCTION MODULE THAT OWNS THEM.
    reporter = _text(SRC_VBA / "modSimReport.bas")
    for name in [surface["automation_endpoint"]] + surface["read_accessors"]:
        assert re.search(rf"^Public (Sub|Function) {name}\b", reporter, re.M), name


# ===========================================================================
# 5. THE PARITY CORPUS IS GENERATED, BOUND AND EXACT
# ===========================================================================
def test_23_the_corpus_is_generated_not_handwritten() -> None:
    sim = load_sim_contract(SPEC / "sim_contract.yaml")
    contract = load_contract(SPEC / "input_contract.yaml")
    calc = load_calc_contract(SPEC / "calc_contract.yaml")
    from pccm_builder.sim_cases import build_gate_b_cases
    built = build_gate_b_cases(sim, contract, calc, _cases()["model_version"])
    assert built == _cases(), (
        "build/phase6_gate_b_cases.json is not what the accepted oracle emits"
    )


def test_24_every_case_binds_an_existing_phase5_plan_case() -> None:
    """Not "a similar fixture": the SAME model, by id, that P5-AN already drives."""
    known = {case["id"]: case for case in PLAN_CASES}
    for case in _cases()["parity_cases"]:
        identifier = case["plan_case_id"]
        assert identifier in known, identifier
        assert "model" in known[identifier], identifier
        assert case["analytical_identity"]["plan_case_id"] == identifier
        assert case["analytical_identity"]["authority"] == "phase5_cases.json"
        assert case["id"].endswith(str(identifier))


def test_25_the_four_sampling_mechanisms_are_covered() -> None:
    """No single existing fixture reaches all four, so four existing ones are used.

    Reported rather than papered over: this is why the corpus has four cases and
    not one, and why no fifth fixture was invented.
    """
    families = set()
    for identifier, mechanism, _golden in GATE_B_PARITY_PLAN_CASES:
        model = {case["id"]: case for case in PLAN_CASES}[identifier]["model"]
        for driver in model["cost_lines"]:
            families.add(driver["distribution"])
        for driver in model["risks"]:
            families.add(driver["distribution"])
            assert driver["probability"] is not None, mechanism
        assert mechanism
    assert {"Triangular", "Beta-PERT", "Uniform"} <= families, families
    assert any(model_has_risk() for model_has_risk in [
        lambda: any(
            {case["id"]: case for case in PLAN_CASES}[identifier]["model"]["risks"]
            for identifier, _m, _g in GATE_B_PARITY_PLAN_CASES
        )
    ]), "no case reaches the Bernoulli occurrence primitive"


def test_26_no_parity_fixture_is_degenerate() -> None:
    """A min == max driver draws the same value under every seed.

    Plan case 30 is exactly that - three Uniform drivers with min == max - and a
    parity case built on it would pass whatever the RNG did.
    """
    known = {case["id"]: case for case in PLAN_CASES}
    for identifier, mechanism, _golden in GATE_B_PARITY_PLAN_CASES:
        model = known[identifier]["model"]
        drivers = list(model["cost_lines"]) + list(model["risks"])
        assert drivers, identifier
        for driver in drivers:
            assert driver["min_value"] != driver["max_value"], (
                f"plan case {identifier} ({mechanism}) has a degenerate driver"
            )


def test_27_the_golden_case_binds_the_accepted_fingerprint_reference() -> None:
    """One case has an INDEPENDENTLY derivable analytical identity, and only one.

    Plan case 1's model IS the accepted fingerprint reference vector, so its
    digest comes from `reference_stream`, an authority that is already emitted
    and already pinned. For any other model the canonical stream would have to
    be rebuilt field by field here, which would be a second implementation of
    the fingerprint layout, so no fingerprint is emitted for the other three.
    """
    golden = [case for case in _cases()["parity_cases"]
              if case["analytical_identity"]["fingerprint_independently_derivable"]]
    assert len(golden) == 1, [case["id"] for case in golden]
    assert golden[0]["plan_case_id"] == 1
    reference = json.loads(_text(BUILD / "phase5_cases.json"))
    assert (golden[0]["expected_exact"]["calculation_fingerprint"]
            == reference["fingerprint"]["reference"]["digest"]), (
        "the golden analytical digest is not the accepted Phase-5 reference digest"
    )
    for case in _cases()["parity_cases"]:
        if case["plan_case_id"] == 1:
            assert "request_fingerprint" in case["expected_exact"]
        else:
            assert "calculation_fingerprint" not in case["expected_exact"]
            assert "request_fingerprint" not in case["expected_exact"]


def test_28_the_iteration_count_is_the_contract_minimum() -> None:
    from pccm_builder.sim_oracle import business_minimum_iterations
    contract = load_contract(SPEC / "input_contract.yaml")
    assert GATE_B_ITERATIONS == business_minimum_iterations(contract)
    assert _cases()["iterations"] == GATE_B_ITERATIONS
    for case in _cases()["parity_cases"]:
        assert case["inputs"]["iterations"] == GATE_B_ITERATIONS
        assert case["expected_exact"]["iterations_run"] == GATE_B_ITERATIONS


def test_29_the_fixed_seed_and_effective_seed_come_from_the_case() -> None:
    for case in _cases()["parity_cases"]:
        assert case["inputs"]["seed_mode"] == "FIXED"
        assert case["inputs"]["supplied_seed"] == GATE_B_SUPPLIED_SEED
        # FIXED: the effective seed IS the supplied seed, and it is emitted
        # rather than assumed so the harness compares a value it was given.
        assert case["expected_exact"]["effective_seed"] == GATE_B_SUPPLIED_SEED


def test_30_every_case_carries_a_distinct_exact_digest_and_a_full_ladder() -> None:
    digests = []
    labels = _cases()["vocabulary"]["quantile_labels"]
    for case in _cases()["parity_cases"]:
        expected = case["expected_exact"]
        assert case["comparison"] == "EXACT", case["id"]
        assert re.fullmatch(r"[0-9A-F]{16}", expected["result_digest"]), case["id"]
        digests.append(expected["result_digest"])
        for measure in ("nominal", "pv"):
            ladder = expected["summary"][measure]
            for key in ("mean", "sample_standard_deviation", "minimum", "maximum"):
                assert isinstance(ladder[key], (int, float)), (case["id"], key)
            assert list(ladder["quantiles"]) == labels, case["id"]
        assert set(expected["deterministic_base"]) == {"nominal", "pv"}
    assert len(set(digests)) == len(digests), "two cases share a digest"


def test_31_the_corpus_admits_no_tolerance() -> None:
    """`sim_contract.yaml` forbids a comparison tolerance, and so does this."""
    # AFFIRMATIVE PHRASES. The comparison policy DENIES that a tolerance is
    # admissible, so a bare ban on the word "tolerance" would refuse the very
    # sentence that forbids one. What may not appear is a tolerance being
    # GRANTED, or any numeric slack field.
    flat = json.dumps(_cases()).lower()
    for granted in ("tolerance_", "relative_tolerance", "absolute_tolerance",
                    "epsilon", "approximately", "\"tolerance\":"):
        assert granted not in flat, granted
    policy = _cases()["comparison_policy"]
    assert policy.startswith("EXACT")
    assert "no tolerance is admissible" in policy
    assert "decimal separator" in policy


def test_32_the_bounds_and_vocabulary_come_from_the_owning_authorities() -> None:
    sim = load_sim_contract(SPEC / "sim_contract.yaml")
    contract = load_contract(SPEC / "input_contract.yaml")
    bounds = _cases()["bounds"]
    lifecycle = sim.raw["seeding"]["nonce_lifecycle"]
    assert bounds["run_id_maximum"] == sim.raw["run_id"]["maximum"]
    assert bounds["run_id_initial"] == sim.raw["run_id"]["initial"]
    assert bounds["nonce_initial"] == lifecycle["initial"]
    assert bounds["nonce_exhausted_value"] == lifecycle["exhausted_value"]
    assert bounds["max_iterations_representable"] == sim.max_iterations_representable
    seed_rule = contract.inputs["random_seed"].validation
    assert bounds["seed_minimum"] == int(seed_rule["formula1"])
    assert bounds["seed_maximum"] == int(seed_rule["formula2"])
    vocabulary = _cases()["vocabulary"]
    for key, label_set in (("attempt_results", "attempt_result"),
                           ("sim_states", "sim_state"),
                           ("seed_modes", "seed_mode")):
        assert vocabulary[key] == list(sim.raw["label_sets"][label_set]), key
    # THE ORDER IS LOAD-BEARING. The harness reads attempt_results[0] as the
    # never-attempted token and sim_states[0] as CURRENT.
    assert vocabulary["attempt_results"][0] == "NONE"
    assert vocabulary["sim_states"][0] == "CURRENT"


def test_33_the_generated_constants_agree_with_the_corpus_bounds() -> None:
    constants = _sim_constants()
    bounds = _cases()["bounds"]
    assert int(constants["SIM_MIN_ITERATIONS"]) == bounds["business_minimum_iterations"]
    assert int(constants["SIM_MAX_ITERATIONS"]) == bounds["max_iterations_representable"]
    assert int(constants["SIM_SEED_MIN"]) == bounds["seed_minimum"]
    assert int(constants["SIM_SEED_MAX"]) == bounds["seed_maximum"]
    assert int(constants["SIM_RUN_ID_MAXIMUM"]) == bounds["run_id_maximum"]
    assert (int(constants["SIM_NONCE_FIRST_VALID"])
            == bounds["nonce_first_valid_allocation"])
    assert (int(constants["SIM_NONCE_LAST_VALID"])
            == bounds["nonce_last_valid_allocation"])
    assert int(constants["SIM_NONCE_EXHAUSTED"]) == bounds["nonce_exhausted_value"]


# ===========================================================================
# 6. THE SCENARIO MATRIX IS COMPLETE AND FAIL-CLOSED
# ===========================================================================
REQUIRED_SCENARIOS = (
    "P6-PRE", "P6-ART", "P6-CMP", "P6-M", "P6-API", "P6-BTN", "P6-INIT",
    "P6-FX1", "P6-DET", "P6-ORA", "P6-FIXED-INERT",
    "P6-AU1", "P6-AU2", "P6-BANK", "P6-ACC",
    "P6-RF1", "P6-PRESERVE", "P6-FP1", "P6-FP2", "P6-FP3",
    "P6-REC1", "P6-REC2", "P6-REC3", "P6-REC4", "P6-REC5",
    "P6-RIDMAX", "P6-AXIS", "P6-LDG",
)


def test_34_every_required_scenario_is_declared_and_recorded() -> None:
    code = _executable(PHASE6)
    declared = set(re.findall(r"'(P6-[A-Z0-9-]+)'", code))
    for identifier in REQUIRED_SCENARIOS:
        assert identifier in declared, identifier
        # Recorded through the ledger, or - for the two ledger-integrity IDs -
        # through Add-Result deliberately, so the ledger cannot suppress itself.
        assert (f"Add-Phase6Result '{identifier}'" in code
                or f"Add-Result '{identifier}'" in code
                or f"-Id '{identifier}'" in code), identifier
    assert "P6-FIN" in declared


def test_34b_the_declared_scenario_set_covers_every_required_and_recorded_id() -> None:
    """`Get-Phase6ScenarioIds` is the declaration the preflight validates against.

    Scoped to that function's own return block: an ID that still appears
    elsewhere in the file - in the required list, or in the Add-Phase6Result
    call that records it - is NOT declared, and the preflight would refuse it on
    Windows. A whole-file search would find those other mentions and pass.
    """
    code = _executable(PHASE6)
    block = code.split("function Get-Phase6ScenarioIds")[1].split("\nfunction ")[0]
    declared = set(re.findall(r"'(P6-[A-Z0-9-]+)'", block))
    for identifier in REQUIRED_SCENARIOS:
        assert identifier in declared, f"{identifier} is not declared"
    assert "P6-FIN" in declared
    required_block = code.split("function Get-Phase6RequiredScenarioIds")[1].split(
        "\nfunction ")[0]
    required = set(re.findall(r"'(P6-[A-Z0-9-]+)'", required_block))
    assert required == set(REQUIRED_SCENARIOS), sorted(required ^ set(REQUIRED_SCENARIOS))
    assert required <= declared, sorted(required - declared)
    recorded = set(re.findall(r"Add-Phase6Result '(P6-[A-Z0-9-]+)'", code))
    recorded |= set(re.findall(r"-Id '(P6-[A-Z0-9-]+)'", code))
    assert recorded <= declared, sorted(recorded - declared)


def test_35_the_recorded_ids_are_exactly_the_declared_set() -> None:
    """A typo cannot invent a scenario, and a scenario cannot go unlisted."""
    code = _executable(PHASE6)
    recorded = set(re.findall(r"Add-Phase6Result '(P6-[A-Z0-9-]+)'", code))
    recorded |= set(re.findall(r"Add-Result '(P6-[A-Z0-9-]+)'", code))
    recorded |= set(re.findall(r"-Id '(P6-[A-Z0-9-]+)'", code))
    listed = set(re.findall(r"'(P6-[A-Z0-9-]+)'", code))
    assert recorded <= listed, sorted(recorded - listed)
    assert set(REQUIRED_SCENARIOS) <= recorded, sorted(set(REQUIRED_SCENARIOS) - recorded)


def test_36_the_prerequisite_path_fails_closed() -> None:
    """Not attempted must be as loud as failed, and never a SKIP."""
    code = _executable(PHASE6)
    assert "if (-not $prerequisiteOk)" in code
    assert "'FAIL'" in code
    # NO SCENARIO MAY BE RECORDED AS A SKIP. Reading the results for skips is a
    # different thing from writing one, so the ban is on the write.
    assert not re.search(r"Add-(Phase6)?Result [^\n]*'SKIP'", code), (
        "the Phase-6 block records a SKIP"
    )
    # SCOPED BY CODE, NOT BY A COMMENT MARKER. `_executable` removes every `#`
    # line, so splitting on one would silently take the rest of the file and the
    # check would find its evidence somewhere else entirely.
    block = code.split("if (-not $prerequisiteOk)")[1].split("# ---")[0][:1600]
    assert "Get-Phase6RequiredScenarioIds" in block
    assert "Add-Phase6Result $id" in block
    assert "'P6-FIN'" in block


def test_37_the_ledger_refuses_a_second_result_and_reports_it() -> None:
    code = _executable(PHASE6)
    assert "Test-Phase6ResultRecorded" in code
    assert "Phase6LedgerViolations" in code
    # The violation must reach a FAIL, not only a Note.
    integrity = code.split("function Add-Phase6LedgerIntegrityResult")[1].split(
        "function ")[0]
    assert "'P6-LDG'" in integrity
    assert "'FAIL'" in integrity


def test_38_every_fixture_writing_scenario_captures_restores_and_verifies() -> None:
    """A scenario whose restoration fails is a FAIL, never a note."""
    code = _executable(PHASE6)
    assert "function New-Phase6CellFixture" in code
    assert "function Set-Phase6CellFixture" in code
    assert "function Restore-Phase6CellFixture" in code
    # The restore's verification result goes into the same checklist the
    # scenario's PASS/FAIL is computed from.
    restore = code.split("function Restore-Phase6CellFixture")[1].split("function ")[0]
    assert "Add-Check $List" in restore
    assert "is restored exactly" in restore
    # And every direct machine-state write goes through the fixture helper.
    writes = re.findall(r"Set-SimRawCell -Workbook \$Workbook", code)
    assert len(writes) >= 3, writes
    for scenario in ("P6-REC1", "P6-REC2", "P6-REC3", "P6-REC4", "P6-REC5", "P6-RIDMAX"):
        assert scenario in code, scenario
    assert code.count("Restore-Phase6CellFixture -Workbook") >= 2


def test_39_post_evidence_is_captured_before_cleanup() -> None:
    recovery = _executable(PHASE6).split(
        "function Invoke-Phase6RecoveryScenario")[1].split("$pendingCell =")[0]
    evidence_at = recovery.index("$evidence =")
    restore_at = recovery.index("Restore-Phase6CellFixture")
    assert evidence_at < restore_at, (
        "the recovery scenarios restore before they capture their evidence"
    )


def test_40_no_mid_call_observation_is_claimed() -> None:
    """Application.Run is synchronous; the harness must not pretend otherwise."""
    text = _text(PHASE6)
    # AFFIRMATIVE PHRASINGS ONLY, so the file's own denials cannot match them.
    for forbidden in ("holds the transaction open", "while the call is running",
                      "observed mid-call", "read during FinalCommit",
                      "paused inside", "with the transaction still open"):
        assert forbidden not in text, forbidden
    assert "Application.Run is synchronous" in text or "Application.Run is SYNCHRONOUS" in text
    bank = text.split("# P6-BANK.")[1].split("# P6-ACC.")[0]
    assert "AGGREGATE" in bank
    assert "SOURCE evidence" in bank


def test_41_no_runtime_claim_is_made_about_the_private_consumption_flag() -> None:
    text = _text(PHASE6)
    assert "NonceConsumed" in text, "the exclusion is not stated at all"
    for line in text.splitlines():
        if "NonceConsumed" not in line:
            continue
        at = text.index(line)
        # FLATTENED. The exclusion is prose and wraps across lines, so a raw
        # substring search would miss "PowerShell cannot / observe it".
        window = " ".join(text[max(0, at - 500): at + 500].split())
        assert ("cannot observe" in window) or ("Private Boolean" in window), line


def test_42_the_no_replay_invariant_is_not_stated_as_digest_inequality() -> None:
    """Two seeds may legitimately produce the same digest on a degenerate model."""
    text = _text(PHASE6)
    au2 = text.split("# P6-AU1 / P6-AU2.")[1].split("# P6-BANK.")[0]
    assert "digest inequality is not a contract rule" in au2
    assert "consumed different AUTO nonces" in au2
    assert "different effective seeds" in au2
    # The digest comparison in P6-AU2 is a NOTE, never an Add-Check.
    for line in au2.splitlines():
        if "Digest" in line and "Add-Check" in line:
            raise AssertionError(f"P6-AU2 asserts on a digest: {line.strip()}")


def test_43_the_compile_and_inventory_scenarios_are_derived_not_re_executed() -> None:
    """Reporting a second compile that did not happen would be an overclaim."""
    text = _text(PHASE6)
    for identifier, source in (("P6-CMP", "P5-CMP"), ("P6-M", "P5-M")):
        block = text.split(f"# {identifier} ")[0] if False else text
        assert f"'{source}'" in block, source
    assert "DERIVED. The compile itself is P5-CMP" in text
    assert "DERIVED. The inventory itself is P5-M" in text
    code = _executable(PHASE6)
    for forbidden in ("Compile VBAProject", "VBComponents", "CommandBars"):
        assert forbidden not in code, (
            f"the Phase-6 block must not re-execute the compile control ({forbidden})"
        )


def test_44_the_preflight_runs_before_excel_and_aborts_the_run() -> None:
    driver = _text(HARNESS)
    preflight_at = driver.index("Invoke-Phase6CoveragePreflight")
    excel_at = driver.index("Prepare a disposable copy of the build")
    assert preflight_at < excel_at, "the Phase-6 preflight runs after the copy is made"
    block = driver[preflight_at - 200: preflight_at + 800]
    assert "exit 1" in block
    code = _executable(PHASE6)
    # THE FUNCTION, NOT THE REST OF THE FILE. `_executable` strips comment
    # lines, so a split on `# ===` would take everything after the preflight and
    # find `result_digest` in the parity comparator instead - a check that could
    # not fail. The next `function` keyword is the real boundary.
    preflight = code.split("function Invoke-Phase6CoveragePreflight")[1]
    preflight = preflight.split("\nfunction ")[0]
    for required in ("phase6_gate_b_inspection.json", "phase6_gate_b_cases.json",
                     "result_digest", "effective_seed", "summary",
                     "deterministic_base", "comparison_policy"):
        assert required in preflight, required
    # AND THE PER-CASE CHECKS ARE REAL PREDICATES, not a constant.
    assert "$null -ne $case.expected_exact.PSObject.Properties[$key]" in preflight
    assert "Add-Check $list ($case.id + ' carries ' + $key) $true" not in preflight


def test_45_the_step13_file_claims_no_execution() -> None:
    """The distinction the whole step turns on, stated in the file itself."""
    text = _text(PHASE6)
    assert "NOTHING HERE HAS BEEN EXECUTED" in text
    assert "no Windows run has been made" in text
    for overclaim in ("Excel produced", "the run passed", "proven on Windows",
                      "confirmed in Excel"):
        assert overclaim not in text, overclaim


def test_46_the_parity_scenario_proves_the_analytical_identity_first() -> None:
    """Comparing a simulation before proving WHICH model produced it compares
    two different questions.

    The golden case's analytical digest is independently derivable and must be
    asserted outright; for the other three the accepted `phase5_cases.json`
    expectations are the identity, and the harness must say so rather than
    silently skipping the question.
    """
    code = _executable(PHASE6)
    block = code.split("foreach ($case in $parityCases)")[1].split("Add-Phase6Result 'P6-ORA'")[0]
    identity_at = block.index("PCCM_CalculationFingerprint")
    parity_at = block.index("Add-Phase6ParityChecks")
    assert identity_at < parity_at, (
        "P6-ORA compares simulation output before establishing the analytical identity"
    )
    # A REAL PREDICATE, not a disabled branch.
    assert "if ([bool]$case.analytical_identity.fingerprint_independently_derivable)" in block
    assert "$storedFingerprint -ceq [string]$case.expected_exact.calculation_fingerprint" in block
    # AND THE NON-DERIVABLE CASES SAY WHERE THEIR IDENTITY COMES FROM.
    assert "phase5_cases.json" in block
    assert "second" in block and "implementation" in block


def test_47_the_parity_comparison_is_mandatory_and_covers_the_whole_ladder() -> None:
    """Digest and ladder, both measures, every published row. A digest match
    with an unchecked ladder would prove the retained totals and nothing else."""
    code = _executable(PHASE6)
    comparator = code.split("function Add-Phase6ParityChecks")[1].split("\nfunction ")[0]
    if not comparator.strip():
        comparator = code.split("function Add-Phase6ParityChecks")[1]
    for required in ("result_digest", "effective_seed", "iterations_run",
                     "rng_version", "sim_method_version",
                     "'nominal', 'pv'", "quantile_labels", "deterministic_base_a"):
        assert required in comparator, required
    assert "Test-SimExactText" in comparator and "Test-SimExactDouble" in comparator
    for forbidden in ("if ($false)", "continue  #", "-or $true"):
        assert forbidden not in comparator, forbidden


def test_48_the_two_new_generated_artefacts_are_byte_identical() -> None:
    """A DERIVED PIN, and it catches what the round-trip checks cannot.

    `test_14` and `test_23` prove each artefact equals what the builder emits
    RIGHT NOW. A change to the builder itself moves both sides of that
    comparison and passes. These two hashes are the fixed point: if the emitted
    bytes move, the Windows harness is reading a different authority than the
    one this review saw, and that has to be a deliberate, reported act.
    """
    import hashlib
    for path, expected in (
        (INSPECTION_PATH,
         "51d9092c13d910d88b74b986111b885f481ec7a65f57064eb89a2e263203f239"),
        (GATE_B_CASES_PATH,
         "8c17df7cd0eaa685151bca683219a536d01ebdb0edcd8bbf80993532b20b8726"),
    ):
        actual = hashlib.sha256(path.read_bytes()).hexdigest()
        assert actual == expected, f"{path.name} moved: {actual}"
