#!/usr/bin/env python3
"""PCCM Phase 6 Step 13: STATIC tests over the Windows Gate-B harness extension.

NO WINDOWS RUN HAPPENS HERE, AND NONE CAN. Linux has no Excel and no PowerShell
host; every assertion below is a statement about SOURCE TEXT and about the
artefacts the Stage-A builder emits. Nothing here starts a COM session, drives a
workbook, or claims that any VBA has executed.

    static/source evidence  !=  Windows/Excel runtime evidence

What this file DOES establish:

  * the accepted Phase-4/Phase-5 harness files are BYTE-IDENTICAL to the
    production baseline, except `phase4_functional_test.ps1`, whose only change
    is the authorised Phase-6 wiring;
  * the Phase-6 scenario file restates no `_SimData` address, no defined name
    and no expected simulation value: every one comes from
    `build/phase6_gate_b_inspection.json` or `build/phase6_gate_b_cases.json`;
  * every address in the inspection projection agrees with the generated
    `modSimContract.bas` / `modConstants.bas`, and its sheet agrees with the
    generated Stage-A workbook;
  * the three failpoint stage names and the seven public procedure names the
    harness spells are CHECKED COPIES of the production/contract authority;
  * the parity corpus is generated by the accepted oracle, binds each case to an
    existing Phase-5 plan case, and covers the four sampling mechanisms;
  * the scenario matrix is complete, fail-closed, and records one result per ID.

What it does NOT establish is anything about behaviour. Whether Excel agrees is
Gate B's, on Windows, and that run has not been made.

Runs standalone or under pytest.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

PCCM_ROOT = Path(__file__).resolve().parent.parent
REPO_ROOT = PCCM_ROOT.parent
sys.path.insert(0, str(PCCM_ROOT / "builder"))

from pccm_builder import load_contract, load_sim_contract  # noqa: E402
from pccm_builder.calc_cases import CASES as PLAN_CASES  # noqa: E402
from pccm_builder.calc_loader import load_calc_contract  # noqa: E402
from pccm_builder.sim_cases import (  # noqa: E402
    GATE_B_ITERATIONS,
    GATE_B_PARITY_PLAN_CASES,
    GATE_B_SUPPLIED_SEED,
)
from pccm_builder.sim_inspection import (  # noqa: E402
    ALLOWED_BLOCK_KEYS,
    ALLOWED_CANDIDATE_TARGET_KEYS,
    ALLOWED_CONTROL_KEYS,
    ALLOWED_IDENTITY_KEYS,
    ALLOWED_ITERATION_KEYS,
    ALLOWED_PENDING_KEYS,
    ALLOWED_PUBLICATION_KEYS,
    ALLOWED_ROOT_KEYS,
    ALLOWED_SIM_DATA_KEYS,
    ALLOWED_SURFACE_KEYS,
    build_sim_inspection,
)

BOOTSTRAP = PCCM_ROOT / "bootstrap" / "windows"
HARNESS = BOOTSTRAP / "phase4_functional_test.ps1"
PHASE5 = BOOTSTRAP / "phase5_gate_b_scenarios.ps1"
PHASE6 = BOOTSTRAP / "phase6_gate_b_scenarios.ps1"
LIFECYCLE = BOOTSTRAP / "com_lifecycle.ps1"
DIAGNOSTIC = BOOTSTRAP / "phase5_gate_b_diagnostics.bas"
BUILD_STAGE_B = BOOTSTRAP / "build_stage_b.ps1"

SRC_VBA = PCCM_ROOT / "src" / "vba"
SPEC = PCCM_ROOT / "spec"
BUILD = PCCM_ROOT / "build"

INSPECTION_PATH = BUILD / "phase6_gate_b_inspection.json"
GATE_B_CASES_PATH = BUILD / "phase6_gate_b_cases.json"

# The production baseline this harness is evidence infrastructure FOR. Named,
# never inferred: a runtime result is attributable to a commit or it is worth
# nothing.
PRODUCTION_BASELINE = "5a5b183"

_CACHE: dict[str, object] = {}


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------
def _text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _inspection() -> dict:
    if "inspection" not in _CACHE:
        _CACHE["inspection"] = json.loads(_text(INSPECTION_PATH))
    return _CACHE["inspection"]  # type: ignore[return-value]


def _cases() -> dict:
    if "cases" not in _CACHE:
        _CACHE["cases"] = json.loads(_text(GATE_B_CASES_PATH))
    return _CACHE["cases"]  # type: ignore[return-value]


def _sim_constants() -> dict[str, str]:
    """`SIM_*` and `NM_*` constants, as written by the generator."""
    if "constants" not in _CACHE:
        found: dict[str, str] = {}
        for module in ("modSimContract.bas", "modConstants.bas"):
            for line in _text(BUILD / "vba" / module).splitlines():
                match = re.match(
                    r"Public Const (\w+) As \w+ = (.+?)(?:\s+'.*)?$", line.strip()
                )
                if match:
                    found[match.group(1)] = match.group(2).strip().strip('"')
        _CACHE["constants"] = found
    return _CACHE["constants"]  # type: ignore[return-value]


def _executable(path: Path) -> str:
    """PowerShell source with the block comment and every `#` line removed.

    A rule about what the harness may not RESTATE has to be checked against what
    it EXECUTES. Prose that explains why an address is not spelled here would
    otherwise trip the rule that it is not spelled here.
    """
    body = re.sub(r"<#.*?#>", "", _text(path), flags=re.S)
    return "\n".join(
        line for line in body.splitlines() if not line.lstrip().startswith("#")
    )


def _git_show(revision: str, relative: str) -> bytes:
    return subprocess.run(
        ["git", "show", f"{revision}:{relative}"],
        cwd=REPO_ROOT, check=True, stdout=subprocess.PIPE,
    ).stdout


# ===========================================================================
# 1. THE ACCEPTED HARNESS IS NOT REWRITTEN
# ===========================================================================
def _accepted_lines(path: Path) -> list[str]:
    relative = path.relative_to(REPO_ROOT).as_posix()
    return _git_show(PRODUCTION_BASELINE, relative).decode("utf-8").splitlines()


def _current_lines(path: Path) -> list[str]:
    return _text(path).splitlines()


def test_01_the_phase4_and_phase5_harness_files_are_byte_identical() -> None:
    """Step 13 is an extension. Four accepted files may not move at all.

    `git show` against the production baseline, not a hash written down here: a
    pinned digest would have to be updated by hand and the update is exactly the
    thing that would go unnoticed.

    Compared as LINES, not raw bytes: `.gitattributes` declares `*.ps1` as
    `eol=crlf`, so git stores LF and a checkout holds CRLF. That difference is
    packaging, and `splitlines` is blind to it while remaining exact about
    every character that is not a line terminator.
    """
    for path in (PHASE5, LIFECYCLE, DIAGNOSTIC, BUILD_STAGE_B):
        assert _current_lines(path) == _accepted_lines(path), (
            f"{path.name} moved from {PRODUCTION_BASELINE}"
        )


def test_02_the_phase4_driver_carries_the_wiring_and_nothing_was_removed() -> None:
    """Two statements, and they are different statements.

    THE DRIVER IS FROZEN AGAINST THE PRODUCTION BASELINE. Once the baseline
    moved to the commit that carries the compile repair, the harness wiring is
    already inside it, so a diff against the baseline is the right way to say
    "this harness commit did not touch the Phase-4 driver" — and the wiring
    itself has to be asserted directly rather than as the residue of a diff,
    because that residue is now empty by construction.
    """
    assert _current_lines(HARNESS) == _accepted_lines(HARNESS), (
        f"{HARNESS.name} moved from {PRODUCTION_BASELINE}"
    )

    driver = _text(HARNESS)
    # THE WIRING, NAMED. One dot-source, one preflight, two artefact loads, one
    # harness-commit capture, one scenario call, one ledger verdict, and a
    # summary that names Phase 6.
    for required in ("phase6_gate_b_scenarios.ps1",
                     "Invoke-Phase6CoveragePreflight",
                     "Invoke-Phase6GateBScenarios",
                     "phase6_gate_b_inspection.json",
                     "phase6_gate_b_cases.json",
                     "$harnessCommit",
                     "$repoRoot = Split-Path -Parent $pccmRoot",
                     "-RepoRoot $repoRoot",
                     "Add-Phase6LedgerIntegrityResult",
                     "Phase-6 Gate-B scenarios",
                     "PHASE-4 / PHASE-5 / PHASE-6 FUNCTIONAL TEST: ALL CHECKS PASSED"):
        assert required in driver, required
    assert any(
        ("$simInspectPath" in line and "$simCasesPath" in line)
        for line in driver.splitlines()
    ), "the required-artefact list does not name the two Phase-6 artefacts"

    # AND NOTHING PHASE-4 OR PHASE-5 WAS REWRITTEN TO MAKE ROOM.
    for accepted in ("Invoke-Phase5GateBScenarios",
                     "Add-Phase4FinalCompletenessResult -Results $results",
                     "Add-Phase5LedgerIntegrityResult",
                     "Invoke-Phase5CoveragePreflight"):
        assert accepted in driver, accepted


def test_03_the_phase6_block_starts_nothing_of_its_own() -> None:
    """It runs inside the Phase-4 COM lifecycle. It does not build a second one."""
    code = _executable(PHASE6)
    for forbidden in ("New-Object -ComObject", "Excel.Application", "New-ReleaseLedger",
                      "build_stage_b.ps1", ".Quit(", "Stop-Process", "$excel.Workbooks"):
        assert forbidden not in code, f"the Phase-6 block must not use {forbidden}"


def test_04_no_production_or_phase5_authority_is_written() -> None:
    """Evidence infrastructure only: it changes no production file."""
    changed = subprocess.run(
        ["git", "diff", "--name-only", PRODUCTION_BASELINE, "--",
         "pccm/src", "pccm/spec"],
        cwd=REPO_ROOT, check=True, stdout=subprocess.PIPE,
    ).stdout.decode("utf-8").strip()
    assert changed == "", f"production authority moved: {changed}"


# ===========================================================================
# 2. THE HARNESS RESTATES NO ADDRESS
# ===========================================================================
def test_05_no_a1_address_literal_appears_in_executable_code() -> None:
    """Every cell the harness touches is named by the projection, never spelled.

    A quoted A1 reference in executable PowerShell would be a SECOND reader of
    the `_SimData` layout, which is the whole reason the projection exists.
    """
    code = _executable(PHASE6)
    literals = re.findall(
        r"""['"]([A-Z]{1,2}[0-9]{1,5}(?::[A-Z]{1,2}[0-9]{1,5})?)['"]""", code
    )
    assert literals == [], f"restated addresses: {sorted(set(literals))}"
    assert not re.search(r"\.Range\(\s*['\"]", code), (
        "a Range call was given a literal address"
    )


def test_06_no_sheet_or_defined_name_is_restated() -> None:
    code = _executable(PHASE6)
    sheet = _inspection()["sim_data"]["sheet"]
    assert f"'{sheet}'" not in code and f'"{sheet}"' not in code, (
        "the _SimData sheet name is spelled in executable code"
    )
    for control in _inspection()["controls"].values():
        assert control["defined_name"] not in code, control["defined_name"]
    assert "$Inspection.sim_data.sheet" in code or "SimInspection" in code


def test_07_no_identity_row_number_is_restated() -> None:
    """Rows are asked for by MEANING. A bare row integer would be a second copy."""
    code = _executable(PHASE6)
    rows = _inspection()["sim_data"]["run_identity"]["rows"]
    for key, row in rows.items():
        if row < 10:
            # A single digit is shared with every count and index in the file,
            # and cannot build an address on its own: a literal A1 reference and
            # a quoted column letter are both already refused above, so there is
            # nothing for a bare 8 to be concatenated with.
            continue
        # `(?<![\w.\-])` so "Step-13" is not read as the row 13.
        assert not re.search(rf"(?<![\w.\-]){row}(?![\w.\-])", code), (
            f"the row number {row} ({key}) is restated in executable code"
        )


def test_08_no_bank_column_letter_is_restated() -> None:
    code = _executable(PHASE6)
    columns = _inspection()["sim_data"]["run_identity"]["bank_value_columns"]
    for bank, column in columns.items():
        assert f"'{column}'" not in code, (
            f"bank {bank}'s column letter {column} is spelled in executable code"
        )


def test_09_no_expected_simulation_value_is_restated() -> None:
    """Every digest, seed and ladder value comes from the corpus."""
    code = _executable(PHASE6)
    for case in _cases()["parity_cases"]:
        expected = case["expected_exact"]
        assert expected["result_digest"] not in code, expected["result_digest"]
        if "calculation_fingerprint" in expected:
            assert expected["calculation_fingerprint"] not in code
            assert expected["request_fingerprint"] not in code
    # No 16-character hex token of any kind, so a future digest cannot be pasted.
    assert re.findall(r"\b[0-9A-F]{16}\b", code) == []
    for bound in _cases()["bounds"].values():
        if int(bound) in (0, 1, 2):
            continue
        assert not re.search(rf"(?<![\w.]){bound}(?![\w.])", code), (
            f"the bound {bound} is restated in executable code"
        )


def test_10_there_is_no_recomputation_and_no_fallback() -> None:
    """A harness that could compute the expectation could disagree with the oracle."""
    code = _executable(PHASE6)
    for forbidden in ("[math]::", "Measure-Object -Average", "Get-Random",
                      "-lt 1e-", "AbsoluteDifference"):
        assert forbidden not in code, f"the harness must not contain {forbidden}"
    assert "Test-SimExactDouble" in code and "Test-SimExactText" in code

    # THE TOLERANCE BAN IS SCOPED, and the scope is the point. The SIMULATION
    # comparison is exact and may not name a tolerance at all. The ANALYTICAL
    # identity check hands the accepted Phase-5 comparator its own emitted
    # `$Cases.tolerances`, which is that comparator's authority, not a slack the
    # harness invented - so a blanket ban would forbid reusing the accepted
    # machinery and push the harness towards reimplementing it.
    comparator = code.split("function Add-Phase6ParityChecks")[1].split("\nfunction ")[0]
    for forbidden in ("tolerance", "Tolerance"):
        assert forbidden not in comparator, (
            f"the simulation comparator names {forbidden}"
        )
    for site in re.findall(r"[^\n]*[Tt]olerance[^\n]*", code):
        assert "$Cases.tolerances" in site, (
            f"a tolerance appears outside the accepted Phase-5 pass-through: {site.strip()}"
        )


# ===========================================================================
# 3. CHECKED COPIES, NOT SECOND DECLARATIONS
# ===========================================================================
def test_11_the_three_failpoint_names_match_production() -> None:
    """They are declared in VBA, so VBA stays the authority and this is a copy."""
    code = _executable(PHASE6)
    declared = {}
    for module in ("modSimNonce.bas", "modSimReport.bas"):
        for line in _text(SRC_VBA / module).splitlines():
            match = re.match(
                r'Public Const (FAILPOINT_SIM_\w+) As String = "([^"]+)"', line.strip()
            )
            if match:
                declared[match.group(1)] = match.group(2)
    assert set(declared) == {
        "FAILPOINT_SIM_AFTER_NONCE", "FAILPOINT_SIM_CANDIDATE_BANK",
        "FAILPOINT_SIM_FINAL_COMMIT",
    }, declared
    for name in declared.values():
        assert f"'{name}'" in code, f"the harness never names the failpoint {name}"
    # AND NAMES NOTHING ELSE THAT LOOKS LIKE ONE.
    harness_names = set(re.findall(r"'(Phase6\w+)'", code))
    assert harness_names == set(declared.values()), harness_names


def test_12_the_public_surface_the_harness_spells_is_the_contract_s() -> None:
    """P6-ACC must name each accessor: their semantics differ, so a loop cannot."""
    code = _executable(PHASE6)
    surface = _inspection()["command_surface"]
    for name in surface["read_accessors"]:
        assert f"'{name}'" in code, f"P6-ACC never calls {name}"
    # The endpoint is invoked through the projection, never by a spelled name.
    assert f"'{surface['automation_endpoint']}'" in code
    spelled = set(re.findall(r"'(PCCM_\w+)'", code))
    accepted = set(surface["read_accessors"]) | {surface["automation_endpoint"]}
    # The Phase-4/5 automation helpers the block legitimately reuses.
    accepted |= {"PCCM_AutomationBegin", "PCCM_AutomationResult", "PCCM_Calculate"}
    # The Phase-5 read accessors the CURRENT-fixture identity check calls before
    # every parity comparison. Not a Phase-6 surface: pinned as Phase-5's own
    # api_procedures by test_13.
    accepted |= set(PHASE5_ACCESSORS_USED)
    assert spelled <= accepted, sorted(spelled - accepted)


PHASE5_ACCESSORS_USED = (
    "PCCM_CalculationFingerprint",
    "PCCM_CurrentInputFingerprint",
    "PCCM_CalculationStatus",
    "PCCM_CalculationAttemptResult",
)


def test_13_the_phase5_accessors_it_calls_are_phase5_endpoints() -> None:
    """The current-fixture identity check calls Phase 5's own accessors, not copies."""
    import yaml
    structure = yaml.safe_load(_text(SPEC / "structure_contract.yaml"))
    for name in PHASE5_ACCESSORS_USED:
        assert name in structure["vba"]["api_procedures"], name


# ===========================================================================
# 4. THE INSPECTION PROJECTION AGREES WITH THE GENERATED AUTHORITY
# ===========================================================================
def test_14_the_projection_is_generated_not_handwritten() -> None:
    sim = load_sim_contract(SPEC / "sim_contract.yaml")
    contract = load_contract(SPEC / "input_contract.yaml")
    assert build_sim_inspection(sim, contract) == _inspection(), (
        "build/phase6_gate_b_inspection.json is not what the builder emits"
    )


def test_15_every_key_is_on_the_positive_allowlist() -> None:
    """An allowlist refuses the next semantic value too, whatever it is called."""
    inspection = _inspection()
    assert tuple(inspection) == ALLOWED_ROOT_KEYS, tuple(inspection)
    assert tuple(inspection["sim_data"]) == ALLOWED_SIM_DATA_KEYS
    assert tuple(inspection["sim_data"]["run_identity"]) == ALLOWED_IDENTITY_KEYS
    assert tuple(inspection["sim_data"]["pending_auto_nonce"]) == ALLOWED_PENDING_KEYS
    assert tuple(inspection["sim_data"]["iteration_records"]) == ALLOWED_ITERATION_KEYS
    for block in ("summary_statistics", "contingency_ladder"):
        assert tuple(inspection["sim_data"][block]) == ALLOWED_BLOCK_KEYS, block
    assert tuple(inspection["publication"]) == ALLOWED_PUBLICATION_KEYS
    assert tuple(inspection["command_surface"]) == ALLOWED_SURFACE_KEYS
    for control in inspection["controls"].values():
        assert tuple(control) == ALLOWED_CONTROL_KEYS


def test_16_the_projection_carries_no_expected_value_and_no_vocabulary() -> None:
    """Identities only. Bounds and label sets belong to the expectation corpus."""
    flat = json.dumps(_inspection())
    for semantic in ("SUCCESS", "REFUSED", "FAILED", "AUTO_NONCE_INDETERMINATE",
                     "CURRENT", "STALE", "INVALID", "tolerance", "minimum_iterations",
                     "run_id_maximum", "PERSISTENCE_INDETERMINATE"):
        assert semantic not in flat, f"the projection carries the semantic {semantic}"


def test_17_every_identity_row_matches_the_generated_module() -> None:
    constants = _sim_constants()
    rows = _inspection()["sim_data"]["run_identity"]["rows"]
    for key, row in rows.items():
        name = "SIM_IDENTITY_ROW_" + key.upper()
        assert name in constants, name
        assert int(constants[name]) == row, f"{name}: {constants[name]} != {row}"
    assert len(rows) == 23, len(rows)


def test_18_the_columns_the_sidecar_and_the_commit_range_match() -> None:
    constants = _sim_constants()
    sim_data = _inspection()["sim_data"]
    identity = sim_data["run_identity"]
    assert identity["label_column"] == constants["SIM_IDENTITY_LABEL_COLUMN"]
    assert identity["value_column"] == constants["SIM_IDENTITY_VALUE_COLUMN"]
    assert identity["value_column"] == constants["SIM_SHARED_VALUE_COLUMN"]
    assert identity["bank_value_columns"]["A"] == constants["SIM_SNAPSHOT_COLUMN_A"]
    assert identity["bank_value_columns"]["B"] == constants["SIM_SNAPSHOT_COLUMN_B"]
    assert int(identity["first_row"]) == int(constants["SIM_IDENTITY_FIRST_ROW"])
    assert int(identity["last_row"]) == int(constants["SIM_IDENTITY_LAST_ROW"])
    assert sim_data["pending_auto_nonce"]["cell"] == constants["SIM_PENDING_AUTO_NONCE_CELL"]
    assert (_inspection()["publication"]["final_commit_range"]
            == constants["SIM_FINAL_COMMIT_RANGE"])


def test_19_the_iteration_summary_and_contingency_geometry_match() -> None:
    constants = _sim_constants()
    sim_data = _inspection()["sim_data"]
    iteration = sim_data["iteration_records"]
    assert int(iteration["header_row"]) == int(constants["SIM_DATA_HEADER_ROW"])
    assert (int(iteration["first_iteration_row"])
            == int(constants["SIM_DATA_FIRST_ITERATION_ROW"]))
    for bank, suffix in (("A", "A"), ("B", "B")):
        for key in ("iteration_index", "total_nominal", "total_pv"):
            name = f"SIM_ITER_{suffix}_{key.upper()}_COLUMN"
            assert iteration["banks"][bank][key] == constants[name], name
    summary = sim_data["summary_statistics"]
    assert summary["label_column"] == constants["SIM_SUMMARY_LABEL_COLUMN"]
    assert summary["bank_value_columns"]["A"]["nominal"] == constants["SIM_SUMMARY_A_NOMINAL_COLUMN"]
    assert summary["bank_value_columns"]["B"]["pv"] == constants["SIM_SUMMARY_B_PV_COLUMN"]
    for key, row in summary["rows"].items():
        assert int(constants["SIM_SUMMARY_ROW_" + key.upper()]) == row, key
    contingency = sim_data["contingency_ladder"]
    assert contingency["label_column"] == constants["SIM_CONTINGENCY_LABEL_COLUMN"]
    for key, row in contingency["rows"].items():
        assert int(constants["SIM_CONTINGENCY_ROW_" + key.upper()]) == row, key


def test_20_the_controls_match_the_generated_defined_names() -> None:
    constants = _sim_constants()
    controls = _inspection()["controls"]
    assert (controls["monte_carlo_iterations"]["defined_name"]
            == constants["NM_INPUT_MONTE_CARLO_ITERATIONS"])
    assert controls["random_seed"]["defined_name"] == constants["NM_INPUT_RANDOM_SEED"]
    for control in controls.values():
        assert control["sheet"] == "Setup"
        assert re.fullmatch(r"[A-Z]{1,2}[0-9]{1,4}", control["cell"]), control["cell"]


def test_21_the_projected_sheet_exists_in_the_generated_workbook() -> None:
    """The address authority and the workbook the harness drives must agree."""
    import openpyxl
    workbook = openpyxl.load_workbook(BUILD / "PCCM_stageA.xlsx", read_only=True)
    try:
        sheet_name = _inspection()["sim_data"]["sheet"]
        assert sheet_name in workbook.sheetnames, workbook.sheetnames
        assert (workbook[sheet_name].sheet_state
                == _inspection()["sim_data"]["required_visibility"])
    finally:
        workbook.close()


def test_22_the_command_surface_matches_the_contract_and_the_module() -> None:
    sim = load_sim_contract(SPEC / "sim_contract.yaml")
    surface = _inspection()["command_surface"]
    block = sim.raw["command_surface"]
    assert surface["automation_endpoint"] == block["automation_endpoint"]
    assert surface["read_accessors"] == list(block["read_accessors"])
    constants = _sim_constants()
    assert int(constants["SIM_READ_ACCESSOR_COUNT"]) == len(surface["read_accessors"])
    for index, name in enumerate(surface["read_accessors"], start=1):
        assert constants[f"SIM_READ_ACCESSOR_{index}"] == name
    # AND THE PROCEDURES EXIST IN THE PRODUCTION MODULE THAT OWNS THEM.
    reporter = _text(SRC_VBA / "modSimReport.bas")
    for name in [surface["automation_endpoint"]] + surface["read_accessors"]:
        assert re.search(rf"^Public (Sub|Function) {name}\b", reporter, re.M), name


# ===========================================================================
# 5. THE PARITY CORPUS IS GENERATED, BOUND AND EXACT
# ===========================================================================
def test_23_the_corpus_is_generated_not_handwritten() -> None:
    sim = load_sim_contract(SPEC / "sim_contract.yaml")
    contract = load_contract(SPEC / "input_contract.yaml")
    calc = load_calc_contract(SPEC / "calc_contract.yaml")
    from pccm_builder.sim_cases import build_gate_b_cases
    built = build_gate_b_cases(sim, contract, calc, _cases()["model_version"])
    assert built == _cases(), (
        "build/phase6_gate_b_cases.json is not what the accepted oracle emits"
    )


def test_24_every_case_binds_an_existing_phase5_plan_case() -> None:
    """Not "a similar fixture": the SAME model, by id, that P5-AN already drives."""
    known = {case["id"]: case for case in PLAN_CASES}
    for case in _cases()["parity_cases"]:
        identifier = case["plan_case_id"]
        assert identifier in known, identifier
        assert "model" in known[identifier], identifier
        assert case["analytical_identity"]["plan_case_id"] == identifier
        assert case["analytical_identity"]["authority"] == "phase5_cases.json"
        assert case["id"].endswith(str(identifier))


def test_25_the_four_sampling_mechanisms_are_covered() -> None:
    """No single existing fixture reaches all four, so four existing ones are used.

    Reported rather than papered over: this is why the corpus has four cases and
    not one, and why no fifth fixture was invented.
    """
    families = set()
    for identifier, mechanism, _golden in GATE_B_PARITY_PLAN_CASES:
        model = {case["id"]: case for case in PLAN_CASES}[identifier]["model"]
        for driver in model["cost_lines"]:
            families.add(driver["distribution"])
        for driver in model["risks"]:
            families.add(driver["distribution"])
            assert driver["probability"] is not None, mechanism
        assert mechanism
    assert {"Triangular", "Beta-PERT", "Uniform"} <= families, families
    assert any(model_has_risk() for model_has_risk in [
        lambda: any(
            {case["id"]: case for case in PLAN_CASES}[identifier]["model"]["risks"]
            for identifier, _m, _g in GATE_B_PARITY_PLAN_CASES
        )
    ]), "no case reaches the Bernoulli occurrence primitive"


def test_26_no_parity_fixture_is_degenerate() -> None:
    """A min == max driver draws the same value under every seed.

    Plan case 30 is exactly that - three Uniform drivers with min == max - and a
    parity case built on it would pass whatever the RNG did.
    """
    known = {case["id"]: case for case in PLAN_CASES}
    for identifier, mechanism, _golden in GATE_B_PARITY_PLAN_CASES:
        model = known[identifier]["model"]
        drivers = list(model["cost_lines"]) + list(model["risks"])
        assert drivers, identifier
        for driver in drivers:
            assert driver["min_value"] != driver["max_value"], (
                f"plan case {identifier} ({mechanism}) has a degenerate driver"
            )


def test_27_the_golden_case_binds_the_accepted_fingerprint_reference() -> None:
    """One case has an INDEPENDENTLY derivable analytical identity, and only one.

    Plan case 1's model IS the accepted fingerprint reference vector, so its
    digest comes from `reference_stream`, an authority that is already emitted
    and already pinned. For any other model the canonical stream would have to
    be rebuilt field by field here, which would be a second implementation of
    the fingerprint layout, so no fingerprint is emitted for the other three.
    """
    golden = [case for case in _cases()["parity_cases"]
              if case["analytical_identity"]["fingerprint_independently_derivable"]]
    assert len(golden) == 1, [case["id"] for case in golden]
    assert golden[0]["plan_case_id"] == 1
    reference = json.loads(_text(BUILD / "phase5_cases.json"))
    assert (golden[0]["expected_exact"]["calculation_fingerprint"]
            == reference["fingerprint"]["reference"]["digest"]), (
        "the golden analytical digest is not the accepted Phase-5 reference digest"
    )
    for case in _cases()["parity_cases"]:
        if case["plan_case_id"] == 1:
            assert "request_fingerprint" in case["expected_exact"]
        else:
            assert "calculation_fingerprint" not in case["expected_exact"]
            assert "request_fingerprint" not in case["expected_exact"]


def test_28_the_iteration_count_is_the_contract_minimum() -> None:
    from pccm_builder.sim_oracle import business_minimum_iterations
    contract = load_contract(SPEC / "input_contract.yaml")
    assert GATE_B_ITERATIONS == business_minimum_iterations(contract)
    assert _cases()["iterations"] == GATE_B_ITERATIONS
    for case in _cases()["parity_cases"]:
        assert case["inputs"]["iterations"] == GATE_B_ITERATIONS
        assert case["expected_exact"]["iterations_run"] == GATE_B_ITERATIONS


def test_29_the_fixed_seed_and_effective_seed_come_from_the_case() -> None:
    for case in _cases()["parity_cases"]:
        assert case["inputs"]["seed_mode"] == "FIXED"
        assert case["inputs"]["supplied_seed"] == GATE_B_SUPPLIED_SEED
        # FIXED: the effective seed IS the supplied seed, and it is emitted
        # rather than assumed so the harness compares a value it was given.
        assert case["expected_exact"]["effective_seed"] == GATE_B_SUPPLIED_SEED


def test_30_every_case_carries_a_distinct_exact_digest_and_a_full_ladder() -> None:
    digests = []
    labels = _cases()["vocabulary"]["quantile_labels"]
    for case in _cases()["parity_cases"]:
        expected = case["expected_exact"]
        assert case["comparison"] == "EXACT", case["id"]
        assert re.fullmatch(r"[0-9A-F]{16}", expected["result_digest"]), case["id"]
        digests.append(expected["result_digest"])
        for measure in ("nominal", "pv"):
            ladder = expected["summary"][measure]
            for key in ("mean", "sample_standard_deviation", "minimum", "maximum"):
                assert isinstance(ladder[key], (int, float)), (case["id"], key)
            assert list(ladder["quantiles"]) == labels, case["id"]
        assert set(expected["deterministic_base"]) == {"nominal", "pv"}
    assert len(set(digests)) == len(digests), "two cases share a digest"


def test_31_the_corpus_admits_no_tolerance() -> None:
    """`sim_contract.yaml` forbids a comparison tolerance, and so does this."""
    # AFFIRMATIVE PHRASES. The comparison policy DENIES that a tolerance is
    # admissible, so a bare ban on the word "tolerance" would refuse the very
    # sentence that forbids one. What may not appear is a tolerance being
    # GRANTED, or any numeric slack field.
    flat = json.dumps(_cases()).lower()
    for granted in ("tolerance_", "relative_tolerance", "absolute_tolerance",
                    "epsilon", "approximately", "\"tolerance\":"):
        assert granted not in flat, granted
    policy = _cases()["comparison_policy"]
    assert policy.startswith("EXACT")
    assert "no tolerance is admissible" in policy
    assert "decimal separator" in policy


def test_32_the_bounds_and_vocabulary_come_from_the_owning_authorities() -> None:
    sim = load_sim_contract(SPEC / "sim_contract.yaml")
    contract = load_contract(SPEC / "input_contract.yaml")
    bounds = _cases()["bounds"]
    lifecycle = sim.raw["seeding"]["nonce_lifecycle"]
    assert bounds["run_id_maximum"] == sim.raw["run_id"]["maximum"]
    assert bounds["run_id_initial"] == sim.raw["run_id"]["initial"]
    assert bounds["nonce_initial"] == lifecycle["initial"]
    assert bounds["nonce_exhausted_value"] == lifecycle["exhausted_value"]
    assert bounds["max_iterations_representable"] == sim.max_iterations_representable
    seed_rule = contract.inputs["random_seed"].validation
    assert bounds["seed_minimum"] == int(seed_rule["formula1"])
    assert bounds["seed_maximum"] == int(seed_rule["formula2"])
    vocabulary = _cases()["vocabulary"]
    for key, label_set in (("attempt_results", "attempt_result"),
                           ("sim_states", "sim_state"),
                           ("seed_modes", "seed_mode")):
        assert vocabulary[key] == list(sim.raw["label_sets"][label_set]), key
    # THE ORDER IS LOAD-BEARING. The harness reads attempt_results[0] as the
    # never-attempted token and sim_states[0] as CURRENT.
    assert vocabulary["attempt_results"][0] == "NONE"
    assert vocabulary["sim_states"][0] == "CURRENT"


def test_33_the_generated_constants_agree_with_the_corpus_bounds() -> None:
    constants = _sim_constants()
    bounds = _cases()["bounds"]
    assert int(constants["SIM_MIN_ITERATIONS"]) == bounds["business_minimum_iterations"]
    assert int(constants["SIM_MAX_ITERATIONS"]) == bounds["max_iterations_representable"]
    assert int(constants["SIM_SEED_MIN"]) == bounds["seed_minimum"]
    assert int(constants["SIM_SEED_MAX"]) == bounds["seed_maximum"]
    assert int(constants["SIM_RUN_ID_MAXIMUM"]) == bounds["run_id_maximum"]
    assert (int(constants["SIM_NONCE_FIRST_VALID"])
            == bounds["nonce_first_valid_allocation"])
    assert (int(constants["SIM_NONCE_LAST_VALID"])
            == bounds["nonce_last_valid_allocation"])
    assert int(constants["SIM_NONCE_EXHAUSTED"]) == bounds["nonce_exhausted_value"]


# ===========================================================================
# 6. THE SCENARIO MATRIX IS COMPLETE AND FAIL-CLOSED
# ===========================================================================
# THE FUNCTIONAL SET. P6-FIN is the verdict OVER it and P6-LDG the verdict over
# every guarded result including P6-FIN, so neither may be a member: making the
# ledger's verdict a precondition of the completeness verdict that precedes it
# is exactly the circular ordering Round 4A removed from Phase 5.
REQUIRED_SCENARIOS = (
    "P6-PRE", "P6-ART", "P6-CMP", "P6-M", "P6-API", "P6-BTN", "P6-INIT",
    "P6-FX1", "P6-DET", "P6-ORA", "P6-FIXED-INERT",
    "P6-AU1", "P6-AU2", "P6-BANK", "P6-ACC",
    "P6-RF1", "P6-PRESERVE", "P6-FP1", "P6-FP2", "P6-FP3",
    "P6-REC1", "P6-REC2", "P6-REC3", "P6-REC4", "P6-REC5",
    "P6-RIDMAX", "P6-AXIS",
)

FIXTURE_SCENARIOS = ("P6-REC1", "P6-REC2", "P6-REC3", "P6-REC4", "P6-REC5",
                     "P6-RIDMAX")


def test_34_every_required_scenario_is_declared_and_recorded() -> None:
    code = _executable(PHASE6)
    declared = set(re.findall(r"'(P6-[A-Z0-9-]+)'", code))
    for identifier in REQUIRED_SCENARIOS:
        assert identifier in declared, identifier
        # Recorded through the ledger, or - for the two ledger-integrity IDs -
        # through Add-Result deliberately, so the ledger cannot suppress itself.
        assert (f"Add-Phase6Result '{identifier}'" in code
                or f"Add-Result '{identifier}'" in code
                or f"-Id '{identifier}'" in code), identifier
    assert "P6-FIN" in declared


def test_34b_the_declared_scenario_set_covers_every_required_and_recorded_id() -> None:
    """`Get-Phase6ScenarioIds` is the declaration the preflight validates against.

    Scoped to that function's own return block: an ID that still appears
    elsewhere in the file - in the required list, or in the Add-Phase6Result
    call that records it - is NOT declared, and the preflight would refuse it on
    Windows. A whole-file search would find those other mentions and pass.
    """
    code = _executable(PHASE6)
    block = code.split("function Get-Phase6ScenarioIds")[1].split("\nfunction ")[0]
    declared = set(re.findall(r"'(P6-[A-Z0-9-]+)'", block))
    for identifier in REQUIRED_SCENARIOS:
        assert identifier in declared, f"{identifier} is not declared"
    assert "P6-FIN" in declared
    required_block = code.split("function Get-Phase6RequiredScenarioIds")[1].split(
        "\nfunction ")[0]
    required = set(re.findall(r"'(P6-[A-Z0-9-]+)'", required_block))
    assert required == set(REQUIRED_SCENARIOS), sorted(required ^ set(REQUIRED_SCENARIOS))
    assert required <= declared, sorted(required - declared)
    recorded = set(re.findall(r"Add-Phase6Result '(P6-[A-Z0-9-]+)'", code))
    recorded |= set(re.findall(r"-Id '(P6-[A-Z0-9-]+)'", code))
    assert recorded <= declared, sorted(recorded - declared)


def test_35_the_recorded_ids_are_exactly_the_declared_set() -> None:
    """A typo cannot invent a scenario, and a scenario cannot go unlisted."""
    code = _executable(PHASE6)
    recorded = set(re.findall(r"Add-Phase6Result '(P6-[A-Z0-9-]+)'", code))
    recorded |= set(re.findall(r"Add-Result '(P6-[A-Z0-9-]+)'", code))
    recorded |= set(re.findall(r"-Id '(P6-[A-Z0-9-]+)'", code))
    listed = set(re.findall(r"'(P6-[A-Z0-9-]+)'", code))
    assert recorded <= listed, sorted(recorded - listed)
    assert set(REQUIRED_SCENARIOS) <= recorded, sorted(set(REQUIRED_SCENARIOS) - recorded)


def test_36_the_prerequisite_path_fails_closed() -> None:
    """Not attempted must be as loud as failed, and never a SKIP."""
    code = _executable(PHASE6)
    assert "if (-not $prerequisiteOk)" in code
    assert "'FAIL'" in code
    # NO SCENARIO MAY BE RECORDED AS A SKIP. Reading the results for skips is a
    # different thing from writing one, so the ban is on the write.
    assert not re.search(r"Add-(Phase6)?Result [^\n]*'SKIP'", code), (
        "the Phase-6 block records a SKIP"
    )
    # SCOPED BY CODE, NOT BY A COMMENT MARKER. `_executable` removes every `#`
    # line, so splitting on one would silently take the rest of the file and the
    # check would find its evidence somewhere else entirely.
    block = code.split("if (-not $prerequisiteOk)")[1].split("# ---")[0][:1600]
    assert "Get-Phase6RequiredScenarioIds" in block
    assert "Add-Phase6Result $id" in block
    assert "'P6-FIN'" in block


def test_37_the_ledger_refuses_a_second_result_and_reports_it() -> None:
    code = _executable(PHASE6)
    assert "Test-Phase6ResultRecorded" in code
    assert "Phase6LedgerViolations" in code
    # The violation must reach a FAIL, not only a Note.
    integrity = code.split("function Add-Phase6LedgerIntegrityResult")[1].split(
        "function ")[0]
    assert "'P6-LDG'" in integrity
    assert "'FAIL'" in integrity


def test_38_every_fixture_writing_scenario_restores_on_every_path() -> None:
    """Restoration in a `finally`, or it is not restoration.

    The submitted version put the restore on the success path only. Any
    exception after the fixture write - a COM raise from Application.Run, a
    state capture, an assertion helper, evidence formatting - jumped straight to
    `catch` and left the modified F21 or counter in the workbook, and every
    later scenario then ran against it. Proving a restore CALL exists is not the
    same as proving it is reached.
    """
    code = _executable(PHASE6)
    assert "function New-Phase6CellFixture" in code
    assert "function Set-Phase6CellFixture" in code
    assert "function Restore-Phase6CellFixture" in code
    assert "function Complete-Phase6Fixture" in code

    # THE UNWIND IS REACHED FROM A `finally`, once per fixture-writing scenario.
    unwinds = re.findall(
        r"\} finally \{[^}]*?Complete-Phase6Fixture", code, re.S
    )
    assert len(unwinds) >= 2, (
        f"only {len(unwinds)} fixture unwind(s) sit in a finally block"
    )
    assert "Complete-Phase6Fixture" in code
    # AND NOWHERE ELSE. A restore on the success path only is the defect.
    assert code.count("Complete-Phase6Fixture -Workbook") == len(unwinds), (
        "a fixture is completed outside a finally block"
    )

    # THE WRITE IS FLAGGED BEFORE IT HAPPENS, so a raising assignment that still
    # changed the cell is unwound.
    setter = code.split("function Set-Phase6CellFixture")[1].split("\nfunction ")[0]
    assert setter.index("$Fixture.Written = $true") < setter.index("Set-SimRawCell"), (
        "the fixture is only marked written after a successful write"
    )

    # THE RESTORE NEVER THROWS, so a cleanup failure cannot replace the original
    # scenario failure.
    restore = code.split("function Restore-Phase6CellFixture")[1].split("\nfunction ")[0]
    assert "} catch {" in restore and "restoration raised" in restore
    # THE VERDICT IS THE COMPARISON, not merely that a check was emitted. A
    # restore that reported its read-back as a Note and returned $true would
    # satisfy "an Add-Check exists" through its raise arm alone.
    assert "Test-SimSameValue -A $readBack -B $Fixture.Original" in restore, (
        "the restoration does not compare the read-back against the original"
    )
    assert restore.count("Add-Check $List") >= 2
    assert "Add-Note" not in restore, (
        "a restoration outcome reported as a Note cannot fail the scenario"
    )

    # AND AN UNVERIFIED RESTORATION LATCHES CONTAMINATION.
    complete = code.split("function Complete-Phase6Fixture")[1].split("\nfunction ")[0]
    assert "Set-Phase6Contaminated" in complete
    assert "if (-not $restored)" in complete

    for scenario in FIXTURE_SCENARIOS:
        assert scenario in code, scenario


def test_38b_the_original_failure_survives_the_cleanup() -> None:
    """Cleanup must not become the story. The scenario's own exception is kept."""
    code = _executable(PHASE6)
    recovery = code.split("function Invoke-Phase6RecoveryScenario")[1].split(
        "$pendingCell =")[0]
    assert "$scenarioFailure = Format-Phase6Err $_" in recovery
    assert "the scenario ran to completion" in recovery
    assert recovery.index("} catch {") < recovery.index("} finally {"), (
        "the fixture unwind does not follow the catch"
    )


def test_38c_a_contaminated_workbook_stops_stateful_evidence() -> None:
    """Behavioural evidence from a state the harness put there is worse than none."""
    code = _executable(PHASE6)
    assert "function Set-Phase6Contaminated" in code
    assert "function Test-Phase6FixtureIntegrity" in code
    latch = code.split("function Set-Phase6Contaminated")[1].split("\nfunction ")[0]
    assert "if ($script:Phase6FixtureIntegrity)" in latch, "the flag does not latch"

    # EVERY FIXTURE-WRITING SCENARIO CHECKS IT BEFORE RUNNING ANYTHING.
    guards = code.count("if (-not (Test-Phase6FixtureIntegrity))")
    assert guards >= 2, f"only {guards} scenario guard(s) on the contamination flag"
    for fragment in ("not attempted: the harness could not restore an earlier fixture",
                     "Get-Phase6ContaminationReason"):
        assert fragment in code, fragment
    # AND THE RUN CANNOT FINISH GREEN AFTER ONE.
    fin = code.split("# P6-FIN.")[1] if "# P6-FIN." in code else code
    assert "Test-Phase6FixtureIntegrity" in code.split("Add-Phase6Result 'P6-FIN'")[0]


def test_39_post_evidence_is_captured_before_cleanup() -> None:
    """Post-state captured after the restore would describe the harness's own
    tidy-up, not what production left behind."""
    code = _executable(PHASE6)
    # THE CAPTURE, NOT THE DECLARATION. Both blocks initialise `$evidence = \'\'`
    # at the top of the try, so searching for the bare assignment would find the
    # initialiser and pass however far down the real capture had been moved.
    capture = "$evidence = (Format-Phase6State"
    recovery = code.split("function Invoke-Phase6RecoveryScenario")[1].split(
        "$pendingCell =")[0]
    assert capture in recovery
    assert recovery.index(capture) < recovery.index("Complete-Phase6Fixture")
    # SCOPED BY CODE, NOT BY A COMMENT MARKER: `_executable` strips comment
    # lines, so a split on `# P6-RIDMAX` would take the rest of the file.
    ridmax = code.split("-Address $runIdCell")[1].split("Add-Phase6Result 'P6-RIDMAX'")[0]
    assert capture in ridmax
    assert ridmax.index(capture) < ridmax.index("Complete-Phase6Fixture")


def test_40_no_mid_call_observation_is_claimed() -> None:
    """Application.Run is synchronous; the harness must not pretend otherwise."""
    text = _text(PHASE6)
    # AFFIRMATIVE PHRASINGS ONLY, so the file's own denials cannot match them.
    for forbidden in ("holds the transaction open", "while the call is running",
                      "observed mid-call", "read during FinalCommit",
                      "paused inside", "with the transaction still open"):
        assert forbidden not in text, forbidden
    assert "Application.Run is synchronous" in text or "Application.Run is SYNCHRONOUS" in text
    bank = text.split("# P6-BANK.")[1].split("# P6-ACC.")[0]
    assert "AGGREGATE" in bank
    assert "SOURCE evidence" in bank


def test_41_no_runtime_claim_is_made_about_the_private_consumption_flag() -> None:
    text = _text(PHASE6)
    assert "NonceConsumed" in text, "the exclusion is not stated at all"
    for line in text.splitlines():
        if "NonceConsumed" not in line:
            continue
        at = text.index(line)
        # FLATTENED. The exclusion is prose and wraps across lines, so a raw
        # substring search would miss "PowerShell cannot / observe it".
        window = " ".join(text[max(0, at - 500): at + 500].split())
        assert ("cannot observe" in window) or ("Private Boolean" in window), line


def test_42_the_no_replay_invariant_is_not_stated_as_digest_inequality() -> None:
    """Two seeds may legitimately produce the same digest on a degenerate model."""
    text = _text(PHASE6)
    au2 = text.split("# P6-AU1 / P6-AU2.")[1].split("# P6-BANK.")[0]
    assert "digest inequality is not a contract rule" in au2
    assert "consumed different AUTO nonces" in au2
    assert "different effective seeds" in au2
    # The digest comparison in P6-AU2 is a NOTE, never an Add-Check.
    for line in au2.splitlines():
        if "Digest" in line and "Add-Check" in line:
            raise AssertionError(f"P6-AU2 asserts on a digest: {line.strip()}")


def test_43_the_compile_and_inventory_scenarios_are_derived_not_re_executed() -> None:
    """Reporting a second compile that did not happen would be an overclaim."""
    text = _text(PHASE6)
    for identifier, source in (("P6-CMP", "P5-CMP"), ("P6-M", "P5-M")):
        block = text.split(f"# {identifier} ")[0] if False else text
        assert f"'{source}'" in block, source
    assert "DERIVED. The compile itself is P5-CMP" in text
    assert "DERIVED. The inventory itself is P5-M" in text
    code = _executable(PHASE6)
    for forbidden in ("Compile VBAProject", "VBComponents", "CommandBars"):
        assert forbidden not in code, (
            f"the Phase-6 block must not re-execute the compile control ({forbidden})"
        )


def test_44_the_preflight_runs_before_excel_and_aborts_the_run() -> None:
    driver = _text(HARNESS)
    preflight_at = driver.index("Invoke-Phase6CoveragePreflight")
    excel_at = driver.index("Prepare a disposable copy of the build")
    assert preflight_at < excel_at, "the Phase-6 preflight runs after the copy is made"
    block = driver[preflight_at - 200: preflight_at + 800]
    assert "exit 1" in block
    code = _executable(PHASE6)
    # THE FUNCTION, NOT THE REST OF THE FILE. `_executable` strips comment
    # lines, so a split on `# ===` would take everything after the preflight and
    # find `result_digest` in the parity comparator instead - a check that could
    # not fail. The next `function` keyword is the real boundary.
    preflight = code.split("function Invoke-Phase6CoveragePreflight")[1]
    preflight = preflight.split("\nfunction ")[0]
    for required in ("phase6_gate_b_inspection.json", "phase6_gate_b_cases.json",
                     "result_digest", "effective_seed", "summary",
                     "deterministic_base", "comparison_policy"):
        assert required in preflight, required
    # AND THE PER-CASE CHECKS ARE REAL PREDICATES, not a constant.
    assert "$null -ne $case.expected_exact.PSObject.Properties[$key]" in preflight
    assert "Add-Check $list ($case.id + ' carries ' + $key) $true" not in preflight


def test_45_the_step13_file_claims_no_execution() -> None:
    """The distinction the whole step turns on, stated in the file itself."""
    text = _text(PHASE6)
    assert "NOTHING HERE HAS BEEN EXECUTED" in text
    assert "no Windows run has been made" in text
    for overclaim in ("Excel produced", "the run passed", "proven on Windows",
                      "confirmed in Excel"):
        assert overclaim not in text, overclaim


def test_46_the_parity_scenario_proves_the_current_analytical_identity_first() -> None:
    """Comparing a simulation before proving WHICH model produced it, right now,
    compares two different questions.

    A NOTE ABOUT EARLIER EVIDENCE IS NOT A CHECK. The submitted version proved
    only that the duration control matched the model and, for the three
    non-golden cases, emitted a note saying P5-AN had already driven the accepted
    expectations. That is a statement about a different scenario at a different
    time; it says nothing about the workbook as it stands immediately before
    THIS simulation. Every case now establishes current Phase-5 authority
    through the ACCEPTED comparators before the run.
    """
    code = _executable(PHASE6)
    block = code.split("foreach ($case in $parityCases)")[1].split(
        "Add-Phase6Result 'P6-ORA'")[0]

    # 1. EVERY CASE, NOT JUST THE GOLDEN ONE. The accepted Phase-5 comparators
    #    are called unconditionally, outside any `if`.
    for required in ("Add-Phase5AnalyticalChecks", "Add-Phase5SuccessStateChecks"):
        assert required in block, required
        # Not inside the derivable-fingerprint branch.
        conditional = block.split(
            "if ([bool]$case.analytical_identity.fingerprint_independently_derivable)")[1]
        assert required not in conditional, (
            f"{required} runs only for the golden case"
        )

    # 2. THE CURRENT SNAPSHOT IS CURRENT, and the stored digest IS the current
    #    one - a stale fingerprint would name a model that has since moved.
    for required in ("PCCM_CalculationAttemptResult", "PCCM_CalculationStatus",
                     "PCCM_CalculationFingerprint", "PCCM_CurrentInputFingerprint",
                     "$calcStored -ceq $calcCurrent"):
        assert required in block, required

    # 3. AND ALL OF IT HAPPENS BEFORE THE SIMULATION AND BEFORE THE COMPARISON.
    identity_at = max(block.index("Add-Phase5AnalyticalChecks"),
                      block.index("Add-Phase5SuccessStateChecks"))
    run_at = block.index("Invoke-Phase6Simulation")
    parity_at = block.index("Add-Phase6ParityChecks")
    assert identity_at < run_at, (
        "P6-ORA runs the simulation before establishing the current analytical identity"
    )
    assert run_at < parity_at

    # 4. THE GOLDEN CASE KEEPS ITS INDEPENDENT REFERENCE CHECK, in addition.
    assert "$calcStored -ceq [string]$case.expected_exact.calculation_fingerprint" in block


def test_47_the_parity_comparison_is_mandatory_and_covers_the_whole_ladder() -> None:
    """Digest and ladder, both measures, every published row. A digest match
    with an unchecked ladder would prove the retained totals and nothing else."""
    code = _executable(PHASE6)
    comparator = code.split("function Add-Phase6ParityChecks")[1].split("\nfunction ")[0]
    if not comparator.strip():
        comparator = code.split("function Add-Phase6ParityChecks")[1]
    for required in ("result_digest", "effective_seed", "iterations_run",
                     "rng_version", "sim_method_version",
                     "'nominal', 'pv'", "quantile_labels", "deterministic_base_a"):
        assert required in comparator, required
    assert "Test-SimExactText" in comparator and "Test-SimExactDouble" in comparator
    for forbidden in ("if ($false)", "continue  #", "-or $true"):
        assert forbidden not in comparator, forbidden


def test_48_the_two_new_generated_artefacts_are_byte_identical() -> None:
    """A DERIVED PIN, and it catches what the round-trip checks cannot.

    `test_14` and `test_23` prove each artefact equals what the builder emits
    RIGHT NOW. A change to the builder itself moves both sides of that
    comparison and passes. These two hashes are the fixed point: if the emitted
    bytes move, the Windows harness is reading a different authority than the
    one this review saw, and that has to be a deliberate, reported act.
    """
    import hashlib
    for path, expected in (
        (INSPECTION_PATH,
         "83eff35ffe1523547313a9c57a58d2b8adeb4e2e6ceeacb85dd846ed30111573"),
        (GATE_B_CASES_PATH,
         "8c17df7cd0eaa685151bca683219a536d01ebdb0edcd8bbf80993532b20b8726"),
    ):
        actual = hashlib.sha256(path.read_bytes()).hexdigest()
        assert actual == expected, f"{path.name} moved: {actual}"


def test_49_the_live_prerequisite_uses_the_accepted_lifecycle_partition() -> None:
    """P6-PRE runs INSIDE the automation session, so Y and Z cannot exist yet.

    The submitted version demanded the full Phase-4 required set, which includes
    the two post-session finalisation cases, and was therefore unsatisfiable by
    construction: every stateful Phase-6 scenario would have failed before the
    first simulation ran. That is the Run-1 sequencing defect under a Phase-6
    name, and the accepted Phase-5 source had already derived the partition for
    exactly this reason.
    """
    code = _executable(PHASE6)
    block = code.split("$prerequisiteOk = $false")[1].split("if (-not $prerequisiteOk)")[0]

    # THE DERIVED PARTITION, not the full Y/Z-inclusive set.
    assert "Get-Phase4PrerequisiteScenarioIds" in block, (
        "P6-PRE does not use the accepted live-session Phase-4 partition"
    )
    assert "Get-Phase4FinalizationScenarioIds" in block
    # The full set may be read ONLY to prove the partition covers it.
    for line in block.splitlines():
        if "Get-Phase4RequiredScenarioIds" not in line:
            continue
        assert "$phase4Required" in line, line

    # THE MEMBERSHIP TEST IS AGAINST THE PREREQUISITE SET.
    assert "$phase4Prerequisite -contains $_.Id" in block
    assert "$phase4Required -contains $_.Id" not in block, (
        "P6-PRE gates on the full Y/Z-inclusive Phase-4 set"
    )

    # THE PARTITION AND THE DEFERRAL ARE BOTH PROVED, not asserted in prose.
    assert "partition the whole matrix" in block
    assert "have not run yet" in block
    # THE PREDICATE, not the variable name. `$earlyDeferred = @()` would satisfy
    # a check that only looked for the identifier.
    assert "$earlyDeferred = @($phase4Deferred | Where-Object { $seen -contains $_ })" in block, (
        "the deferral check does not actually look for an early deferred result"
    )
    assert "($earlyDeferred.Count -eq 0)" in block

    # AND THE PHASE-5 SIDE IS DERIVED TOO, with its own post-session results
    # excluded rather than demanded.
    assert "Get-Phase5ScenarioIds" in block
    for deferred in ("'P5-FIN'", "'P5-LDG'"):
        assert deferred in block, deferred
    assert "has not run yet" in block


def test_50_the_full_35_case_demand_is_not_weakened() -> None:
    """It moved, it did not go away: P5-FIN still gates final acceptance."""
    driver = _text(HARNESS)
    assert "Add-Phase4FinalCompletenessResult -Results $results" in driver
    phase5 = _text(PHASE5)
    assert "function Add-Phase4FinalCompletenessResult" in phase5
    # And the Phase-6 block does not claim to make that demand itself.
    code = _executable(PHASE6)
    assert "Add-Phase4FinalCompletenessResult" not in code


def test_51_the_completeness_and_ledger_verdicts_are_ordered_and_acyclic() -> None:
    """Round 4A, reused rather than reinvented.

    P6-FIN is a guarded result, so a duplicate attempt at it is only visible to
    a verdict emitted AFTER it. And P6-LDG may not be a member of the set P6-FIN
    requires, or the ledger's verdict becomes a precondition of the completeness
    verdict that precedes it.
    """
    code = _executable(PHASE6)
    # P6-FIN through the guarded reporter, and never through Add-Result.
    assert "Add-Phase6Result 'P6-FIN'" in code
    assert "Add-Result 'P6-FIN'" not in code, (
        "P6-FIN bypasses the Phase-6 result guard"
    )
    # P6-LDG through the unguarded one, from ONE emitter, so the ledger cannot
    # suppress its own verdict. The emitter has a PASS arm and a FAIL arm; what
    # must be single is the emission POINT and the emitted-once flag guarding
    # it, not the number of Add-Result lines.
    assert "Add-Phase6Result 'P6-LDG'" not in code
    emitter = code.split("function Add-Phase6LedgerIntegrityResult")[1].split(
        "\nfunction ")[0]
    assert code.count("Add-Result 'P6-LDG'") == emitter.count("Add-Result 'P6-LDG'"), (
        "P6-LDG is emitted from outside its one emitter"
    )
    assert emitter.count("Add-Result 'P6-LDG'") == 2, "the PASS and FAIL arms"
    assert "if ($script:Phase6LedgerReported) { return }" in emitter
    assert "$script:Phase6LedgerReported = $true" in emitter
    # AND IT IS NOT IN THE REQUIRED SET.
    required_block = code.split("function Get-Phase6RequiredScenarioIds")[1].split(
        "\nfunction ")[0]
    for excluded in ("P6-LDG", "P6-FIN"):
        assert f"'{excluded}'" not in required_block, (
            f"{excluded} is a precondition of the verdict that reports on it"
        )
    # THE DRIVER EMITS IT LAST, once, after the Phase-6 call and its catch.
    driver = _text(HARNESS)
    assert driver.count("Add-Phase6LedgerIntegrityResult") == 1
    assert (driver.index("Invoke-Phase6GateBScenarios")
            < driver.index("Add-Phase6LedgerIntegrityResult"))
    assert (driver.index("Add-Phase5LedgerIntegrityResult")
            < driver.index("Add-Phase6LedgerIntegrityResult"))
    # And the scenario function does not emit it itself.
    assert "Add-Phase6LedgerIntegrityResult" not in code.split(
        "function Invoke-Phase6GateBScenarios")[1]


def test_52_the_artefact_identity_separates_the_two_commits() -> None:
    """The production baseline is a pinned authority; HEAD is the harness commit."""
    code = _executable(PHASE6)
    assert "function Get-Phase6ProductionBaseline" in code
    baseline_block = code.split("function Get-Phase6ProductionBaseline")[1].split(
        "\nfunction ")[0]
    assert f"'{PRODUCTION_BASELINE}'" in baseline_block, (
        "the harness's pinned production baseline is not this review's baseline"
    )
    assert "rev-parse HEAD" not in baseline_block

    block = code.split("$baseline = Get-Phase6ProductionBaseline")[1].split(
        "Add-Phase6Result 'P6-ART'")[0]
    assert "production baseline commit" in block
    assert "runtime harness commit" in block
    # THE TWO ARE COMPARED, so one cannot be reported as the other.
    assert "$HarnessCommit -notlike ($baseline + '*')" in block

    # NO GIT MEANS NO PASS, and the arm that says so must actually FAIL. A
    # check that reports the right message with a $true condition passes while
    # claiming the opposite.
    assert "$gitOk" in block
    assert "git is not available on this machine" in block
    assert "'the accepted production source can be bound to the baseline' $false" in block, (
        "the no-git arm of P6-ART does not fail"
    )
    assert "'the accepted production source can be bound to the baseline' $true" not in block
    driver = _text(HARNESS)
    assert "$harnessCommit = ''" in driver, (
        "the driver still substitutes a placeholder for a missing commit"
    )
    assert "unknown (git was not available" not in driver

    # THE BINDING IS BY BLOB IDENTITY, not by module name.
    assert "Get-Phase6ProductionModules" in block
    assert "rev-parse ($baseline + ':' + $relative)" in block
    assert "the accepted baseline source" in block
    assert "diff --quiet" in block
    modules = code.split("function Get-Phase6ProductionModules")[1].split(
        "\nfunction ")[0]
    for name in ("modSimContract", "modSimRng", "modSimSample", "modSimEngine",
                 "modSimStats", "modSimFingerprint", "modSimNonce", "modSimReport"):
        assert f"'{name}'" in modules, name


def test_53_the_pinned_baseline_really_is_unchanged_production() -> None:
    """The pin is only worth what the tree behind it is."""
    changed = subprocess.run(
        ["git", "diff", "--name-only", PRODUCTION_BASELINE, "--",
         "pccm/src/vba", "pccm/spec"],
        cwd=REPO_ROOT, check=True, stdout=subprocess.PIPE,
    ).stdout.decode("utf-8").strip()
    assert changed == "", f"production authority moved: {changed}"
    frozen = json.loads(
        re.search(r"FROZEN_SOURCE = (\{.*?\})",
                  _text(PCCM_ROOT / "tests" / "test_phase6_integration_source.py"),
                  re.S).group(1).replace("'", '"').replace(",\n}", "\n}")
    )
    import hashlib
    for name in ("modSimContract", "modSimRng", "modSimSample", "modSimEngine",
                 "modSimStats", "modSimFingerprint", "modSimNonce", "modSimReport"):
        path = SRC_VBA / f"{name}.bas"
        if name == "modSimContract":
            continue  # generated, pinned by test_48's siblings
        assert name in frozen, name
        actual = hashlib.sha256(path.read_bytes()).hexdigest()
        assert actual == frozen[name], f"{name}.bas moved: {actual}"


def test_54_the_prerequisite_consumes_the_pending_phase5_ledger() -> None:
    """"P5-LDG has not run yet" is necessary, and on its own it is not enough.

    The accepted Phase-5 guard leaves an intermediate state that a scan of
    recorded results cannot see: a duplicate attempt neither overwrites the
    first result nor creates a FAIL. It is recorded as a violation and converted
    into a FAIL by P5-LDG — which is deliberately deferred until after Phase 6.
    So every Phase-5 scenario can read PASS while Phase 5 is already known to
    have a harness-integrity violation, and Phase 6 would build behavioural
    evidence on top of it.
    """
    code = _executable(PHASE6)
    block = code.split("$prerequisiteOk = $false")[1].split("if (-not $prerequisiteOk)")[0]
    assert "Get-Phase5LedgerViolations" in block, (
        "P6-PRE does not read the pending Phase-5 ledger state"
    )
    assert "$phase5LedgerViolations.Count -eq 0" in block, (
        "the pending-violation count is read but not required to be zero"
    )
    assert "pending Phase-5 duplicate attempts" in block
    # THE AUTHORITY IS PHASE 5'S OWN, consumed rather than reimplemented.
    assert "Phase5LedgerViolations" not in code.replace(
        "Get-Phase5LedgerViolations", ""
    ), "the Phase-6 block reaches into Phase 5's ledger state directly"
    assert "function Get-Phase5LedgerViolations" in _text(PHASE5)
    # AND P5-LDG IS STILL NOT EMITTED EARLY.
    assert "Add-Phase5LedgerIntegrityResult" not in code
    driver = _text(HARNESS)
    assert (driver.index("Invoke-Phase6GateBScenarios")
            < driver.index("Add-Phase5LedgerIntegrityResult"))


def test_55_a_fixture_that_fails_verification_never_reaches_production() -> None:
    """Write, VERIFY, and only then invoke production.

    A COM write can return normally and still leave a cell holding something
    other than what was asked for. Recording the failed check and running the
    endpoint anyway produces behavioural observations against a fixture the
    harness had itself just proved was not established.
    """
    code = _executable(PHASE6)
    for block in (
        code.split("function Invoke-Phase6RecoveryScenario")[1].split("$pendingCell =")[0],
        code.split("-Address $runIdCell")[1].split("Add-Phase6Result 'P6-RIDMAX'")[0],
    ):
        # THE RETURN VALUE IS CAPTURED, not discarded.
        assert "$fixtureOk = Set-Phase6CellFixture" in block, (
            "the establishment verdict is discarded"
        )
        assert "$null = Set-Phase6CellFixture" not in block
        # AND IT GATES THE INVOCATION, before any state capture or run.
        assert "if (-not $fixtureOk)" in block
        assert "production was not invoked" in block
        gate_at = block.index("if (-not $fixtureOk)")
        for later in ("Get-Phase6State", "Invoke-Phase6Simulation"):
            assert gate_at < block.index(later), (
                f"{later} is reached before the fixture establishment gate"
            )
        # THE GATE THROWS, so the finally still restores and the failure is kept.
        gate = block[gate_at:gate_at + 400]
        assert "throw" in gate, "the gate does not stop the scenario"
    # AND THE FIXTURE IS STILL MARKED WRITTEN, so restoration is still attempted.
    setter = code.split("function Set-Phase6CellFixture")[1].split("\nfunction ")[0]
    assert setter.index("$Fixture.Written = $true") < setter.index("Set-SimRawCell")


def test_56_the_whole_tree_freeze_runs_from_the_repository_root() -> None:
    """`git -C <path>` resolves a diff pathspec relative to <path>.

    The first version started git inside `pccm` and passed `pccm/src`, which
    resolves to `pccm/pccm/src` and matches nothing. A pathspec matching nothing
    produces no diff, so `--quiet` exited 0 and the freeze check passed whatever
    the tree held — fail-open, on the one statement the whole claim rests on.
    """
    code = _executable(PHASE6)
    assert "$RepoRoot" in code
    assert "$PccmRoot" not in code, "the Phase-6 block still carries the pccm root"
    for line in re.findall(r"[^\n]*& git -C [^\n]*", code):
        assert "$RepoRoot" in line, f"a git invocation does not use the repo root: {line.strip()}"
    # The INVOCATION, not every line that mentions the flag: the result line
    # quotes it back in its diagnostic.
    freeze = [line for line in code.splitlines() if "& git" in line and "diff --quiet" in line]
    assert len(freeze) == 1, freeze
    assert "-C $RepoRoot" in freeze[0]
    assert "'pccm/src' 'pccm/spec'" in freeze[0]
    # AND THE PATHSPEC IS PROVED TO MATCH SOMETHING.
    assert "ls-tree -r --name-only" in code
    assert "the freeze pathspec matches the production trees it names" in code

    driver = _text(HARNESS)
    assert "$repoRoot = Split-Path -Parent $pccmRoot" in driver
    assert "-RepoRoot $repoRoot" in driver
    assert "-PccmRoot" not in driver


def test_57_the_pathspec_defect_is_demonstrated_against_real_git() -> None:
    """Not an argument about git's behaviour — a measurement of it.

    Run both command shapes against a path that genuinely differs from the
    baseline. The corrected form detects the drift; the submitted form reports
    a clean tree.
    """
    correct = subprocess.run(
        ["git", "-C", str(REPO_ROOT), "diff", "--quiet", PRODUCTION_BASELINE,
         "--", "pccm/bootstrap"],
        capture_output=True,
    ).returncode
    submitted = subprocess.run(
        ["git", "-C", str(PCCM_ROOT), "diff", "--quiet", PRODUCTION_BASELINE,
         "--", "pccm/bootstrap"],
        capture_output=True,
    ).returncode
    assert correct != 0, (
        "the control is vacuous: pccm/bootstrap does not differ from the baseline"
    )
    assert submitted == 0, (
        "git no longer resolves the pathspec relative to -C; the rationale for "
        "this correction needs re-deriving rather than assuming"
    )


def test_58_a_drift_in_a_non_modsim_production_file_fails_the_freeze() -> None:
    """The whole-tree claim must not rest on the eight module blob checks.

    A throwaway local clone, a real edit to a production file no `modSim*` check
    covers, and the corrected command shape run against it.
    """
    import shutil
    import tempfile
    with tempfile.TemporaryDirectory(prefix="pccm-freeze-control-") as name:
        clone = Path(name) / "repo"
        result = subprocess.run(
            ["git", "clone", "--quiet", "--local", "--no-hardlinks",
             str(REPO_ROOT), str(clone)],
            capture_output=True,
        )
        if result.returncode != 0:  # pragma: no cover - environment without clone
            raise AssertionError(
                "the freeze control could not clone the repository: "
                + result.stderr.decode("utf-8", "replace")[:200]
            )
        victim = clone / "pccm" / "src" / "vba" / "modWorkbook.bas"
        assert victim.is_file(), victim
        assert "modWorkbook" not in _text(PHASE6), (
            "the control is vacuous: this file IS covered by a module blob check"
        )
        clean = subprocess.run(
            ["git", "-C", str(clone), "diff", "--quiet", PRODUCTION_BASELINE,
             "--", "pccm/src", "pccm/spec"],
            capture_output=True,
        ).returncode
        assert clean == 0, "the clone does not start frozen against the baseline"
        victim.write_text(_text(victim) + "\n' drift\n", encoding="utf-8")
        drifted = subprocess.run(
            ["git", "-C", str(clone), "diff", "--quiet", PRODUCTION_BASELINE,
             "--", "pccm/src", "pccm/spec"],
            capture_output=True,
        ).returncode
        assert drifted != 0, (
            "a real edit to a non-modSim production file did not fail the freeze"
        )
        # AND THE SUBMITTED SHAPE WOULD HAVE MISSED IT.
        missed = subprocess.run(
            ["git", "-C", str(clone / "pccm"), "diff", "--quiet",
             PRODUCTION_BASELINE, "--", "pccm/src", "pccm/spec"],
            capture_output=True,
        ).returncode
        assert missed == 0, (
            "the submitted pathspec shape no longer fails open; re-derive the "
            "rationale for this correction"
        )
        shutil.rmtree(clone, ignore_errors=True)


# ===========================================================================
# 7. WINDOWS POWERSHELL 5.1 CAN PARSE WHAT THE BUILD EMITS
# ===========================================================================
# Step-13 Run 1 died in the preflight, before Excel was started, on
#
#     PSArgumentException: Cannot process argument because the value of
#     argument "name" is not valid.
#
# `phase6_gate_b_inspection.json` carried a JSON object whose property NAME was
# the empty string - the contract's legitimate "no bank has ever been published"
# selector key - and Windows PowerShell 5.1's ConvertFrom-Json cannot
# materialise such an object as a PSCustomObject. `-AsHashtable` is a
# PowerShell 6.0 switch, and the accepted runtime target is 5.1.
#
# Nothing about the contract was wrong. What was wrong was a projection shape
# chosen without asking what its only consumer can read, and no control asked
# that question. These do.
def _empty_key_paths(node: object, where: str) -> list[str]:
    found: list[str] = []
    if isinstance(node, dict):
        for key, value in node.items():
            if key == "":
                found.append(where)
            found.extend(_empty_key_paths(value, f"{where}.{key}"))
    elif isinstance(node, list):
        for index, value in enumerate(node):
            found.extend(_empty_key_paths(value, f"{where}[{index}]"))
    return found


def test_59_neither_generated_artefact_carries_an_empty_object_key() -> None:
    """Recursive, and over BOTH artefacts.

    `candidate_target` is where it happened; assuming it is the only place it
    could happen is how the next one gets shipped.
    """
    for path in (INSPECTION_PATH, GATE_B_CASES_PATH):
        found = _empty_key_paths(json.loads(_text(path)), path.name)
        assert found == [], (
            f"{path.name} carries an object key that Windows PowerShell 5.1 "
            f"cannot parse, at: {found}"
        )


def test_60_the_emitter_refuses_an_empty_object_key() -> None:
    """A build-time refusal, not a convention.

    The emitter is the last place that can stop an artefact the Windows host
    cannot read, and the failure it prevents happens on a machine this build
    never sees.
    """
    from pccm_builder.sim_inspection import _reject_empty_keys
    _reject_empty_keys(json.loads(_text(INSPECTION_PATH)), "control")
    for shape in ({"": "A"},
                  {"publication": {"candidate_target": {"": "A"}}},
                  {"entries": [{"ok": 1}, {"": 2}]}):
        try:
            _reject_empty_keys(shape, "control")
        except ValueError as error:
            assert "empty string" in str(error)
            assert "PowerShell 5.1" in str(error)
        else:  # pragma: no cover - the refusal is the point
            raise AssertionError(f"the emitter accepted {shape!r}")


def test_61_the_candidate_target_projection_preserves_the_contract_mapping() -> None:
    """One for one, in the contract's own order, with the blank as a null VALUE.

    A reshape that loses, gains, reorders or renames a mapping would answer the
    selector question differently from the contract while looking correct.
    """
    sim = load_sim_contract(SPEC / "sim_contract.yaml")
    source = sim.raw["publication"]["banks"]["candidate_target"]
    projected = _inspection()["publication"]["candidate_target"]

    assert isinstance(projected, list), "the selector map is still a JSON object"
    assert len(projected) == len(source), (len(projected), len(source))
    assert [tuple(entry) for entry in projected] == [
        ALLOWED_CANDIDATE_TARGET_KEYS for _ in projected
    ], "an entry carries a key outside the allowlist"

    # EXACTLY ONE representation of the blank source key, as null.
    blanks = [entry for entry in projected if entry["active_bank"] is None]
    assert len(blanks) == 1, blanks
    assert blanks[0]["candidate_bank"] == source[""]

    # EVERY source key survives, and no nonblank key was renamed.
    rebuilt = {
        ("" if entry["active_bank"] is None else entry["active_bank"]):
            entry["candidate_bank"]
        for entry in projected
    }
    assert rebuilt == dict(source), (rebuilt, dict(source))
    assert list(rebuilt) == list(source), "the contract's order was not preserved"

    # AND NO SENTINEL WAS INVENTED for the absence.
    for entry in projected:
        assert entry["active_bank"] is None or entry["active_bank"] in source
    flat = json.dumps(projected)
    for sentinel in ("BLANK", "NONE", "EMPTY", "NULL_BANK", "__none__"):
        assert sentinel not in flat, sentinel


def test_62_the_selector_consumes_entries_and_fails_closed() -> None:
    """The harness must not go back to indexing an empty property name, and must
    not answer from a projection that answers zero times or twice."""
    code = _executable(PHASE6)
    selector = code.split("function Get-Phase6CandidateTarget")[1].split("\nfunction ")[0]

    # ENTRY-BASED, and the regression shape is named and refused.
    assert "$Inspection.publication.candidate_target" in selector
    assert "$matched[0].candidate_bank" in selector
    for regression in ("$map.PSObject.Properties[", "$map.$key", "PSObject.Properties[$key]"):
        assert regression not in selector, (
            f"the selector indexes the projection as an object: {regression}"
        )
    assert "$matches" not in selector, (
        "$matches is a PowerShell automatic variable and must not be reused here"
    )

    # THE BLANK IS NORMALISED ONLY FOR COMPARISON.
    assert "$null -eq $_.active_bank" in selector
    assert "[string]::IsNullOrEmpty($ActiveBank)" in selector

    # EXACTLY ONE, FAIL-CLOSED BOTH WAYS.
    assert "$matched.Count -eq 0" in selector
    assert "$matched.Count -gt 1" in selector
    assert selector.count("throw") >= 3

    # AND THE ANSWER CAN ONLY COME FROM A PROJECTED ENTRY. Named shapes are not
    # enough - the first version of this check listed three ways to spell the
    # A/B rule and missed a fourth. What is required instead is structural:
    # exactly one return, and it reads the matched entry.
    returns = [line.strip() for line in selector.splitlines()
               if line.strip().startswith("return")]
    assert returns == ["return [string]$matched[0].candidate_bank"], returns
    # No bank label may appear as a literal in the selector at all, so no
    # shortcut can answer for one without consulting the projection.
    for label in _inspection()["publication"]["bank_labels"]:
        assert f"'{label}'" not in selector, (
            f"the selector spells the bank label {label}"
        )


def test_63_the_documented_log_name_does_not_overwrite_a_recorded_run() -> None:
    """An aborted attempt is evidence, and a command that clobbers it is a bug.

    Run 1 was attempted and aborted before Excel; it is what found the
    `ConvertFrom-Json` defect. The documented command redirects into a log named
    for the run, so the number in that name has to be the next one the ledger
    does not already record.
    """
    doc = _text(PCCM_ROOT / "docs" / "phase6_step13_gate_b.md")
    recorded = set(re.findall(r"\|\s*\*\*Run (\d+)\*\*\s*\|", doc))
    assert recorded, "the run ledger records no runs"
    # THE COMMAND, not the prose. The paragraph beside it names run1 on purpose,
    # to say what must not be written; scoping to the redirect is what keeps the
    # explanation and the instruction from being confused for each other.
    commands = [line for line in doc.splitlines() if "*>" in line]
    logs = set()
    for line in commands:
        logs.update(re.findall(r"phase6_gate_b_run(\d+)\.log", line))
    assert len(logs) == 1, f"the documented command names {len(logs)} run logs: {logs}"
    documented = int(logs.pop())
    assert documented == max(int(number) for number in recorded), (
        f"the command writes run{documented}.log while the ledger records runs "
        f"{sorted(int(n) for n in recorded)}; an earlier run's evidence would be "
        "overwritten"
    )
    # AND THE LEDGER SAYS WHICH RUN IS STILL TO BE MADE, and what the earlier
    # ones established. A ledger that recorded only successes would be a way of
    # losing the two attempts that found the defects.
    assert "not yet executed" in doc
    assert "ABORTED PRE-EXCEL" in doc
    assert "VALID runtime attempt" in doc


def test_64_the_ledger_verdict_survives_the_zero_violation_case() -> None:
    """The case Runtime Run 2 died on, and it is the NORMAL one.

        PropertyNotFoundException:
        The property 'Count' cannot be found on this object.

    A PowerShell function returning an empty collection emits ZERO pipeline
    objects, so `$violations = Get-Phase6LedgerViolations` lands `$null` and
    StrictMode turns `$violations.Count` into a hard error. Zero violations is
    what a clean run has, so this failed every clean run — after Z, Y, P5-FIN
    and P5-LDG had all passed, with only P6-LDG left to emit.

    The rule is the accepted Phase-4 one: collections are materialised AT THE
    CALLER.
    """
    code = _executable(PHASE6)
    emitter = code.split("function Add-Phase6LedgerIntegrityResult")[1].split(
        "\nfunction ")[0]
    assert "$violations = @(Get-Phase6LedgerViolations)" in emitter, (
        "the ledger verdict reads an unwrapped collection and will throw on a "
        "clean run"
    )
    assert "$violations = Get-Phase6LedgerViolations" not in emitter.replace(
        "$violations = @(Get-Phase6LedgerViolations)", ""
    )

    # ZERO -> exactly one PASS, and it returns rather than falling through into
    # the FAIL arm. Split at the zero-violation branch itself: partitioning on
    # the first `return` would find the emitted-once guard instead.
    guard = "if ($violations.Count -eq 0) {"
    assert guard in emitter
    pass_arm, _, fail_arm = emitter.partition(guard)
    pass_arm, _, fail_arm = fail_arm.partition("\n        return\n    }")
    assert "'PASS'" in pass_arm, pass_arm
    assert "'FAIL'" not in pass_arm, "the zero-violation branch can reach a FAIL"
    # ONE OR MORE -> exactly one FAIL, with EVERY violation represented.
    assert "'FAIL'" in fail_arm
    assert "$violations -join" in fail_arm, (
        "the FAIL arm reports only some of the violations"
    )
    assert "$violations[0]" not in emitter

    # AND EVERY OTHER COLLECTION-RETURNING HELPER IS MATERIALISED AT ITS CALLER.
    collections = ("Get-Phase6LedgerViolations", "Get-Phase6ScenarioIds",
                   "Get-Phase6RequiredScenarioIds", "Get-Phase6FixtureScenarioIds")
    for helper in collections:
        for line in code.splitlines():
            if re.search(rf"=\s*{helper}\b", line):
                assert f"@({helper}" in line, (
                    f"an unwrapped assignment from {helper}: {line.strip()}"
                )


def test_65_the_ledger_verdict_is_the_final_phase6_result() -> None:
    """It has to see every guarded result, P6-FIN included."""
    driver = _text(HARNESS)
    ledger_at = driver.index("Add-Phase6LedgerIntegrityResult")
    for earlier in ("Invoke-Phase6GateBScenarios", "Add-Phase5LedgerIntegrityResult",
                    "Add-Phase4FinalCompletenessResult -Results $results"):
        assert driver.index(earlier) < ledger_at, earlier
    # Nothing records a Phase-6 result after it.
    tail = driver[ledger_at + len("Add-Phase6LedgerIntegrityResult"):]
    assert "Add-Phase6Result" not in tail
    assert "Invoke-Phase6GateBScenarios" not in tail
