#!/usr/bin/env python3
"""PCCM Phase 5 Gate-A Step-3 tests: Stage-A calculation workspace emission.

REPRESENTATION, NOT CALCULATION. Step 3 puts the physical `_Calc` workspace into
the generated workbook, projects the contract's runtime literals into
`modCalcContract.bas`, and emits the acceptance corpus `phase5_cases.json`.
Nothing in the build calculates a model into a cell.

--------------------------------------------------------------------------------
WHAT THIS FILE CHECKS, AND WHERE IT LOOKS
--------------------------------------------------------------------------------
The generated ARTIFACT, read back from disk. Proving that the contract says
`H:J` and that the renderer was called proves nothing about what shipped, so the
workbook is opened and its actual ListObject refs, cells, formats and validations
are asserted. The same for the two generated files: they are read as text and as
JSON, not as in-memory objects.

--------------------------------------------------------------------------------
GOLDEN INDEPENDENCE
--------------------------------------------------------------------------------
    hand-derived literal  ->  Python oracle  ->  phase5_cases.json  ->  later VBA

`phase5_cases.json` is generated BY the accepted oracle, so comparing it back to
that oracle would prove nothing. Every emitted number is therefore re-derived here
by a second, independently written route:

  * the plan's own section-23 literals, restated in this file;
  * `_reference_payload`, a complete second implementation of the accepted
    evaluation semantics, written from the plan's rules and sharing no code with
    `calc_oracle.py`. Because it reproduces those semantics rather than an
    idealised real-number formula, emitted Doubles are compared by EXACT equality;
  * the fingerprint reference stream, its 366-code-unit length, its digest and the
    eight probe digests, restated here as literals.

PROOF SCOPE: Linux, Python, openpyxl. NO VBA IS EXECUTED. NO WINDOWS TEST IS RUN.

Runs standalone or under pytest.
"""

from __future__ import annotations

import json
import math
import os
import shutil
import subprocess
import sys
import tempfile
from fractions import Fraction
from pathlib import Path

from openpyxl import load_workbook

PCCM_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PCCM_ROOT / "builder"))

from pccm_builder import (  # noqa: E402
    build_workbook,
    emit_calc_artifacts,
    load_calc_contract,
    load_contract,
    load_driver_contract,
    load_spec,
    load_structure_contract,
    verify_workbook,
)
from pccm_builder.calc_emit import (  # noqa: E402
    CALC_MODULE_NAME,
    render_calc_contract_module,
    render_cases_json,
)
from pccm_builder.calc_render import placeholder_row, table_ref  # noqa: E402

SPEC_PATH = PCCM_ROOT / "spec" / "workbook.yaml"
CONTRACT_PATH = PCCM_ROOT / "spec" / "input_contract.yaml"
DRIVERS_PATH = PCCM_ROOT / "spec" / "driver_contract.yaml"
STRUCTURE_PATH = PCCM_ROOT / "spec" / "structure_contract.yaml"
CALC_PATH = PCCM_ROOT / "spec" / "calc_contract.yaml"
BUILD_SCRIPT = PCCM_ROOT / "builder" / "build_stage_a.py"

# ---------------------------------------------------------------------------
# Locked literals - restated here so the emitted values have something
# independent to be wrong against.
# ---------------------------------------------------------------------------
LOCKED_TABLE_ANCHORS = {
    "tblCalcYears": (15, "H", "J", 3),
    "tblCalcInflationFactors": (15, "M", "P", 4),
    "tblCalcFX": (15, "S", "U", 3),
    "tblCalcDrivers": (15, "X", "AR", 21),
    "tblCalcAnnual": (15, "AU", "BB", 8),
}

LOCKED_CALC_STATE_INITIAL = {
    13: None, 14: None, 15: None, 16: None,
    17: "NONE", 18: None, 19: "NOT CALCULATED", 20: None,
}
LOCKED_CALC_TOTALS_ROWS = tuple(range(23, 33))

REFERENCE_STREAM = (
    "S7:PCCM-FPI1:1S6:HEADERI1:1I1:4"
    "N22:2.0260000000000000E+03N22:2.0260000000000000E+03"
    "N22:1.0000000000000000E+00N22:1.0000000000000001E-01"
    "S4:COSTI1:1I1:9S6:CL-001S10:Triangular"
    "N22:1.0000000000000000E+01N22:8.0000000000000000E+01"
    "N22:1.5000000000000000E+02N22:1.0000000000000000E+02"
    "N22:1.0000000000000000E+00N22:1.0000000000000000E+00"
    "N22:1.0000000000000000E+00"
    "S4:RISKI1:0"
)
REFERENCE_CODE_UNITS = 366
REFERENCE_DIGEST = "50B6EB0E26857EA7"

LOCKED_PROBE_DIGESTS = (
    "041ACBD05C7BF72C", "52704E9A542869CA", "0C8A057A0BE7EB51", "7674F1C35E639F98",
    "7D26D4C95587DE0C", "0821AFB0608291C8", "5B4CA2E133AD91A2", "101504AC7803B226",
)

LOCKED_REDUCTION_REMAINDERS = (65404, 65404, 667120106, 667121456)

LOCKED_TOLERANCES = {
    "profiling_sum_absolute": 1e-9,
    "identity_absolute_floor": 1e-6,
    "identity_relative_coefficient": 1e-12,
    "conditioning_scale_floor": 1.0,
}

LOCKED_HASH_CONSTANTS = {
    "FP_BASE": 131, "FP_MOD_1": 2147483647, "FP_MOD_2": 2147483629,
    "FP_INIT_1": 1, "FP_INIT_2": 1,
}

# Plan section 23, hand-derived. The design oracle for the cases it states.
PLAN_LITERALS = {
    1: {"knom": 1.0, "kpv": 1.0, "a_nom": 1000.0, "c_nom": 1100.0, "b_nom": 100.0},
    2: {"knom": 3.75, "a_nom": 1500.0},
    3: {"knom": 1.1085375, "a_nom": 1108.5375},
    4: {"kpv": 0.998150826446, "a_pv": 998.150826446, "c_pv": 1097.965909091},
    5: {"c_nom": 1219.39125, "b_nom": 110.85375},
    6: {"central_value": 100.0, "mean_value": 105.0},
    7: {"central_value": 115.0, "mean_value": 115.0, "b_nom": 0.0},
    8: {"mean_value": 250.0, "d_nom": 75.0},
    9: {"d_nom": 83.1403125, "d_pv": 74.8613119835},
    22: {"central_value": 115.0, "mean_value": 115.0},
}

REL = 1e-11


def _close(actual: float, expected: float, note: str = "", rel: float = REL) -> None:
    allowance = abs(expected) * rel + 1e-9
    assert abs(actual - expected) <= allowance, (
        f"{note or 'value'}: got {actual!r}, expected {expected!r}"
    )


# ---------------------------------------------------------------------------
# shared build
# ---------------------------------------------------------------------------
_ARTIFACTS: dict[str, object] = {}


def _built() -> dict:
    """One real build, reused. Every assertion reads it back from DISK."""
    if _ARTIFACTS:
        return _ARTIFACTS
    directory = Path(tempfile.mkdtemp(prefix="pccm-step3-"))
    spec = load_spec(SPEC_PATH)
    contract = load_contract(CONTRACT_PATH)
    drivers = load_driver_contract(DRIVERS_PATH)
    structure = load_structure_contract(STRUCTURE_PATH)
    calc = load_calc_contract(CALC_PATH)

    workbook, _ = build_workbook(spec, contract, drivers, structure, calc)
    path = directory / "PCCM_stageA.xlsx"
    workbook.save(path)
    workbook.close()
    artifacts = emit_calc_artifacts(directory, spec, calc)

    _ARTIFACTS.update(
        directory=directory, path=path, spec=spec, contract=contract, drivers=drivers,
        structure=structure, calc=calc,
        module_text=artifacts.module_path.read_text(encoding="utf-8"),
        cases=json.loads(artifacts.cases_path.read_text(encoding="utf-8")),
        module_path=artifacts.module_path, cases_path=artifacts.cases_path,
    )
    return _ARTIFACTS


def _sheet():
    workbook = load_workbook(_built()["path"])
    return workbook, workbook["_Calc"]


def _module_constants() -> dict[str, str]:
    """`name -> literal text` parsed out of the generated .bas, as VBA would see it."""
    found: dict[str, str] = {}
    for line in _built()["module_text"].splitlines():
        stripped = line.strip()
        if not stripped.startswith("Public Const "):
            continue
        declaration = stripped[len("Public Const "):]
        name, _, rest = declaration.partition(" As ")
        _, _, value = rest.partition(" = ")
        found[name.strip()] = value.split("    ' ")[0].strip()
    return found


def _const_number(name: str) -> float:
    return float(_module_constants()[name])


def _const_string(name: str) -> str:
    raw = _module_constants()[name]
    assert raw.startswith('"') and raw.endswith('"'), f"{name} is not a String literal"
    return raw[1:-1].replace('""', '"')


# ---------------------------------------------------------------------------
# 1. the calculation contract is a real build input
# ---------------------------------------------------------------------------
def test_the_build_consumes_the_calculation_contract() -> None:
    """`--calc-contract` exists, defaults to the project spec, and is reported."""
    completed = subprocess.run(
        [sys.executable, str(BUILD_SCRIPT), "--help"],
        capture_output=True, text=True, check=True,
    )
    assert "--calc-contract" in completed.stdout
    assert "calc_contract.yaml" in completed.stdout


def test_a_malformed_calculation_contract_fails_the_build_with_exit_code_two() -> None:
    """A calculation-contract-specific error, and a non-zero exit.

    The rule that rejects the mutation lives in the accepted Step-1 loader; what
    this proves is that the BUILDER consults it before emitting anything.
    """
    directory = Path(tempfile.mkdtemp(prefix="pccm-step3-bad-"))
    try:
        broken = directory / "calc_contract.yaml"
        text = CALC_PATH.read_text(encoding="utf-8")
        # A locked header spelling. The Step-1 loader owns the rule; what is proved
        # here is that the BUILDER runs it before emitting anything.
        broken.write_text(text.replace("header_row: 15", "header_row: 16", 1),
                          encoding="utf-8")
        completed = subprocess.run(
            [sys.executable, str(BUILD_SCRIPT), "--quiet",
             "--calc-contract", str(broken),
             "--out", str(directory / "out.xlsx")],
            capture_output=True, text=True, check=False,
        )
        assert completed.returncode == 2, completed.stdout + completed.stderr
        assert "CALCULATION CONTRACT ERROR" in completed.stderr, completed.stderr
        assert not (directory / "out.xlsx").exists(), (
            "a workbook was emitted despite an invalid calculation contract"
        )
    finally:
        shutil.rmtree(directory, ignore_errors=True)


def test_the_workbook_now_describes_itself_as_phase_five() -> None:
    spec = _built()["spec"]
    assert spec.model["model_version"] == "0.5.0"
    assert "Phase 5" in spec.model["build_phase"], spec.model["build_phase"]
    assert (PCCM_ROOT / "VERSION").read_text(encoding="utf-8").strip() == "0.5.0"


# ---------------------------------------------------------------------------
# 2. the physical _Calc anchors
# ---------------------------------------------------------------------------
def test_the_five_calculation_tables_exist_at_their_locked_physical_anchors() -> None:
    """Read out of the generated artifact, against literals restated here.

    Not "the contract says H:J and the renderer ran": the workbook is opened and
    its actual ListObject references are compared with the anchors the accepted
    design locks.
    """
    workbook, worksheet = _sheet()
    try:
        tables = worksheet.tables
        assert set(tables) == set(LOCKED_TABLE_ANCHORS), sorted(tables)
        for name, (header_row, first, last, width) in LOCKED_TABLE_ANCHORS.items():
            reference = tables[name].ref
            assert reference == f"{first}{header_row}:{last}{header_row + 1}", (
                f"{name} is at {reference}"
            )
            headers = [
                cell.value
                for cell in worksheet[f"{first}{header_row}:{last}{header_row}"][0]
            ]
            assert len(headers) == width, f"{name} is {len(headers)} columns wide"
            assert all(isinstance(h, str) and h for h in headers), headers
    finally:
        workbook.close()


def test_every_table_header_matches_the_contract_spelling_and_order() -> None:
    workbook, worksheet = _sheet()
    calc = _built()["calc"]
    try:
        for table in calc.all_tables:
            actual = [
                worksheet.cell(row=table.header_row, column=table.first_column_index + i).value
                for i in range(len(table.columns))
            ]
            assert actual == table.headers, f"{table.table_name}: {actual}"
    finally:
        workbook.close()


def test_the_calculation_workspace_has_zero_semantic_rows() -> None:
    """The physical body row is exactly one, and it is entirely blank.

    No project index, no calendar year, no SAR audit row, no dummy driver, no zero
    annual row and no Base-Year factor row: all of those are calculation outputs.
    """
    workbook, worksheet = _sheet()
    calc = _built()["calc"]
    try:
        for table in calc.all_tables:
            body = placeholder_row(table)
            assert table_ref(table).endswith(f"{body}")
            for index in range(len(table.columns)):
                cell = worksheet.cell(row=body, column=table.first_column_index + index)
                assert cell.value is None, (
                    f"{table.table_name} body cell {cell.coordinate} holds {cell.value!r}"
                )
            below = worksheet.cell(row=body + 1, column=table.first_column_index)
            assert below.value is None
    finally:
        workbook.close()


def test_the_scalar_blocks_are_at_their_locked_rows_with_their_locked_values() -> None:
    workbook, worksheet = _sheet()
    calc = _built()["calc"]
    try:
        assert (calc.calc_state.first_row, calc.calc_state.last_row) == (13, 20)
        assert (calc.calc_totals.first_row, calc.calc_totals.last_row) == (23, 32)
        for row, expected in LOCKED_CALC_STATE_INITIAL.items():
            assert worksheet[f"C{row}"].value == expected, (
                f"C{row} holds {worksheet[f'C{row}'].value!r}, expected {expected!r}"
            )
            assert worksheet[f"B{row}"].value, f"B{row} has no label"
        for row in LOCKED_CALC_TOTALS_ROWS:
            assert worksheet[f"C{row}"].value is None, (
                f"C{row} is seeded with {worksheet[f'C{row}'].value!r}; blank means no "
                "calculation has committed and zero would mean a total of zero"
            )
            assert worksheet[f"C{row}"].number_format == "#,##0.00"
            assert "—" in worksheet[f"B{row}"].value, worksheet[f"B{row}"].value
    finally:
        workbook.close()


def test_the_fingerprint_version_cell_ships_blank() -> None:
    """C15 stays blank even though the contract declares FP_VERSION = 1.

    The stamp records which algorithm produced the STORED digest, and there is no
    stored digest until a successful commit writes both together.
    """
    workbook, worksheet = _sheet()
    try:
        assert _built()["calc"].fingerprint_version == 1
        assert worksheet["C15"].value is None
        assert worksheet["C15"].number_format == "0"
    finally:
        workbook.close()


def test_phase_four_territory_on_calc_is_untouched() -> None:
    """Rows 1-11 are Phase-4 property. Phase 5 starts at row 13, not 12."""
    workbook, worksheet = _sheet()
    calc = _built()["calc"]
    try:
        assert worksheet["C10"].value == 0 and worksheet["C10"].number_format == "0"
        assert worksheet["C11"].value == 0 and worksheet["C11"].number_format == "0"
        assert worksheet["B10"].value == "Cost Line ID Counter"
        assert worksheet["B11"].value == "Risk ID Counter"
        assert calc.phase4_last_row == 11
        assert calc.calc_state.first_row == 13, "row 12 is a deliberate gap"
        for row in range(1, 13):
            for column in range(6, 60):
                assert worksheet.cell(row=row, column=column).value is None, (
                    f"Phase-5 content at row {row}, column {column}"
                )
    finally:
        workbook.close()


def test_the_calculation_workspace_carries_no_formula_and_no_validation() -> None:
    workbook, worksheet = _sheet()
    try:
        for row in worksheet.iter_rows():
            for cell in row:
                assert not (
                    isinstance(cell.value, str) and cell.value.startswith("=")
                ), f"formula at _Calc!{cell.coordinate}: {cell.value!r}"
        for validation in worksheet.data_validations.dataValidation:
            assert not str(validation.sqref).strip(), (
                f"data validation {validation.sqref} on the calculation workspace"
            )
    finally:
        workbook.close()


def test_the_sheet_inventory_and_visibility_are_unchanged() -> None:
    workbook, worksheet = _sheet()
    spec = _built()["spec"]
    try:
        assert workbook.sheetnames == spec.sheet_names
        assert len(workbook.sheetnames) == 14
        assert worksheet.sheet_state == "hidden"
        assert workbook["_SimData"].sheet_state == "veryHidden"
        assert worksheet.sheet_view.showGridLines
        assert workbook.active.title == spec.active_sheet
    finally:
        workbook.close()


def test_the_table_inventory_is_the_prior_set_plus_exactly_five() -> None:
    """The "only contract-declared Tables exist" gate is EXTENDED, not relaxed."""
    workbook, _ = _sheet()
    built = _built()
    try:
        found = {
            name for sheet in workbook.worksheets for name in getattr(sheet, "tables", {})
        }
        prior = {t.table_name for t in built["contract"].all_tables}
        prior |= {r.table_name for r in built["drivers"].all_registers}
        prior |= {g.table_name for g in built["structure"].all_grids}
        assert found == prior | set(LOCKED_TABLE_ANCHORS)
        assert len(found - prior) == 5
    finally:
        workbook.close()


# ---------------------------------------------------------------------------
# 3. modCalcContract.bas
# ---------------------------------------------------------------------------
def test_the_generated_module_has_the_required_preamble() -> None:
    text = _built()["module_text"]
    lines = text.splitlines()
    assert lines[0] == f'Attribute VB_Name = "{CALC_MODULE_NAME}"'
    assert lines[1] == "Option Explicit"
    assert "GENERATED FILE - DO NOT EDIT." in text
    assert "CONSTANTS ONLY" in text


def test_the_generated_module_declares_no_procedure_and_no_recurrence() -> None:
    """A constants module. No Sub, no Function, no hash loop, no formula."""
    text = _built()["module_text"]
    code = "\n".join(
        line for line in text.splitlines() if not line.strip().startswith("'")
    )
    for banned in ("Sub ", "Function ", "For ", "While ", "Mod ", "Fix(", "Rnd", "Randomize"):
        assert banned not in code, f"{banned!r} appears in generated code"


def test_the_projected_geometry_is_the_contracts_geometry() -> None:
    """Table names, header rows, first columns, widths and per-column ordinals."""
    calc = _built()["calc"]
    constants = _module_constants()
    for table in calc.all_tables:
        prefix = table.key.upper()
        assert _const_string(f"TBL_{prefix}") == table.table_name
        assert _const_number(f"TBL_{prefix}_HEADER_ROW") == table.header_row
        assert _const_string(f"TBL_{prefix}_FIRST_COLUMN") == table.first_column
        assert _const_string(f"TBL_{prefix}_LAST_COLUMN") == table.last_column
        assert _const_number(f"TBL_{prefix}_FIRST_COLUMN_INDEX") == table.first_column_index
        assert _const_number(f"TBL_{prefix}_COLUMN_COUNT") == len(table.columns)
        assert _const_string(f"TBL_{prefix}_EMPTY_REF") == table_ref(table)
        assert _const_number(f"TBL_{prefix}_FIRST_BODY_ROW") == placeholder_row(table)
        for ordinal, column in enumerate(table.columns, start=1):
            name = f"COL_{prefix}_{column.key.upper()}"
            assert name in constants, f"{name} was not projected"
            assert float(constants[name]) == ordinal


def test_the_projected_block_geometry_and_labels_are_the_contracts() -> None:
    calc = _built()["calc"]
    for block in (calc.calc_state, calc.calc_totals):
        prefix = block.key.upper()
        assert _const_string(f"{prefix}_VALUE_COLUMN") == block.value_column
        assert _const_number(f"{prefix}_FIRST_ROW") == block.first_row
        assert _const_number(f"{prefix}_LAST_ROW") == block.last_row
        assert _const_string(f"{prefix}_VALUE_RANGE") == block.value_range()
        for entry in block.fields:
            assert _const_number(f"{prefix}_ROW_{entry.key.upper()}") == entry.row
    for label in calc.derived_status_labels:
        assert _const_string(f"CALC_STATUS_{label.replace(' ', '_')}") == label
    for label in calc.attempt_result_labels:
        assert _const_string(f"CALC_ATTEMPT_{label}") == label


def test_the_projected_tolerances_are_the_contracts_and_the_locked_numbers() -> None:
    calc = _built()["calc"]
    assert _const_number("TOL_PROFILING_SUM_ABSOLUTE") == calc.tolerances.profiling_sum_absolute
    assert _const_number("TOL_IDENTITY_ABSOLUTE_FLOOR") == calc.tolerances.identity_absolute_floor
    assert _const_number("TOL_IDENTITY_RELATIVE_COEFFICIENT") == (
        calc.tolerances.identity_relative_coefficient
    )
    assert _const_number("TOL_CONDITIONING_SCALE_FLOOR") == (
        calc.tolerances.conditioning_scale_floor
    )
    # ... and against literals restated here, so a change to both the contract and
    # the projection at once is still visible.
    assert _const_number("TOL_PROFILING_SUM_ABSOLUTE") == LOCKED_TOLERANCES["profiling_sum_absolute"]
    assert _const_number("TOL_IDENTITY_ABSOLUTE_FLOOR") == LOCKED_TOLERANCES["identity_absolute_floor"]
    assert _const_number("TOL_IDENTITY_RELATIVE_COEFFICIENT") == (
        LOCKED_TOLERANCES["identity_relative_coefficient"]
    )
    assert _const_number("TOL_CONDITIONING_SCALE_FLOOR") == (
        LOCKED_TOLERANCES["conditioning_scale_floor"]
    )


def test_the_projected_fingerprint_version_comes_from_the_calculation_contract() -> None:
    assert _const_number("FP_VERSION") == _built()["calc"].fingerprint_version == 1


def test_the_projected_hash_constants_come_from_the_python_authority() -> None:
    """FP_BASE and the moduli are NOT in the YAML and must not be.

    `calc_fingerprint.py` is the reference implementation and owns the hash
    mathematics, so the generator imports it. Checked against the module's own
    attributes AND against the locked literals of plan section 11.4.
    """
    from pccm_builder import calc_fingerprint

    for name, locked in LOCKED_HASH_CONSTANTS.items():
        assert _const_number(name) == getattr(calc_fingerprint, name)
        assert _const_number(name) == locked
    assert _const_string("FP_STREAM_TAG") == calc_fingerprint.STREAM_TAG == "PCCM-FP"
    for index, section in enumerate(calc_fingerprint.SECTION_ORDER, start=1):
        assert _const_string(f"FP_SECTION_{index}") == section
    assert (
        CALC_PATH.read_text(encoding="utf-8").count("2147483647") == 0
    ), "a hash modulus leaked into the calculation contract, creating a second authority"


def test_mutating_the_hash_authority_changes_the_projection() -> None:
    """NO SECOND SOURCE OF TRUTH, proved by moving the source.

    The generator is re-run against a patched `calc_fingerprint` module; if the
    emitted constant did not follow, the .bas would be carrying its own literal.
    """
    from pccm_builder import calc_emit, calc_fingerprint

    built = _built()
    original = calc_fingerprint.FP_BASE
    try:
        calc_fingerprint.FP_BASE = 137
        text = calc_emit.render_calc_contract_module(built["spec"], built["calc"])
        assert "Public Const FP_BASE As Long = 137" in text
    finally:
        calc_fingerprint.FP_BASE = original
    assert "Public Const FP_BASE As Long = 131" in (
        calc_emit.render_calc_contract_module(built["spec"], built["calc"])
    )


def test_mutating_the_contract_changes_the_projected_geometry() -> None:
    """The same proof for the YAML-owned side."""
    import dataclasses

    from pccm_builder import calc_emit

    built = _built()
    calc = built["calc"]
    moved = dataclasses.replace(
        calc,
        tables={
            key: (dataclasses.replace(table, header_row=99) if key == "calc_years" else table)
            for key, table in calc.tables.items()
        },
    )
    text = calc_emit.render_calc_contract_module(built["spec"], moved)
    assert "Public Const TBL_CALC_YEARS_HEADER_ROW As Long = 99" in text
    assert "Public Const TBL_CALC_YEARS_HEADER_ROW As Long = 15" in built["module_text"]


# ---------------------------------------------------------------------------
# 4. phase5_cases.json - shape and independence
# ---------------------------------------------------------------------------
def test_the_case_corpus_covers_the_plan_matrix() -> None:
    cases = _built()["cases"]["plan_cases"]
    assert [case["id"] for case in cases] == list(range(1, 38))
    kinds = {case["id"]: case["kind"] for case in cases}
    assert {kinds[i] for i in (32, 33, 34, 37)} == {"runtime_only"}
    assert {kinds[i] for i in (26, 27, 35, 36)} == {"fingerprint"}
    for identifier in (32, 33, 34, 37):
        case = next(c for c in cases if c["id"] == identifier)
        assert "expected" not in case and "model" not in case, (
            f"case {identifier} is workbook-state behaviour; Python must not claim it"
        )
        assert case["why"]


def test_no_runtime_only_case_carries_a_fabricated_result() -> None:
    document = _built()["cases"]
    text = json.dumps(document)
    assert "Infinity" not in text and "NaN" not in text
    for case in document["plan_cases"]:
        if case["kind"] == "runtime_only":
            assert set(case) == {"id", "kind", "title", "why"}, case


def test_the_corpus_metadata_and_tolerance_header_are_exact() -> None:
    """The acceptance artifact proves its own header.

    These sit outside the expectation-path ledger, which is defined specifically as
    expected-RESULT evidence, but a harness reading the corpus has to be able to
    trust which contract and which authorities produced it.
    """
    document = _built()["cases"]
    assert document["schema_version"] == 1
    assert document["tolerances"] == LOCKED_TOLERANCES
    assert document["provenance"] == {
        "model_version": "0.5.0",
        "calc_contract_version": "1.0.0",
        "fingerprint_version": 1,
        "oracle": "builder/pccm_builder/calc_oracle.py",
        "numerical_kernel": "builder/pccm_builder/calc_numeric.py",
        "fingerprint_authority": "builder/pccm_builder/calc_fingerprint.py",
    }
    # ... and the header agrees with the authorities it names.
    calc = _built()["calc"]
    assert document["provenance"]["calc_contract_version"] == calc.version
    assert document["provenance"]["fingerprint_version"] == calc.fingerprint_version
    assert document["provenance"]["model_version"] == _built()["spec"].model["model_version"]
    assert document["tolerances"]["profiling_sum_absolute"] == (
        calc.tolerances.profiling_sum_absolute
    )
    assert document["tolerances"]["identity_absolute_floor"] == (
        calc.tolerances.identity_absolute_floor
    )
    assert document["tolerances"]["identity_relative_coefficient"] == (
        calc.tolerances.identity_relative_coefficient
    )
    assert document["tolerances"]["conditioning_scale_floor"] == (
        calc.tolerances.conditioning_scale_floor
    )
    for named in document["provenance"].values():
        if isinstance(named, str) and named.endswith(".py"):
            assert (PCCM_ROOT / named).is_file(), named


def test_the_emitted_fingerprint_evidence_matches_the_locked_literals() -> None:
    """Case 26, 27, 35 and 36, against literals restated in THIS file."""
    section = _built()["cases"]["fingerprint"]
    assert section["reference"]["stream"] == REFERENCE_STREAM
    assert section["reference"]["code_units"] == REFERENCE_CODE_UNITS == 366
    assert section["reference"]["digest"] == REFERENCE_DIGEST == "50B6EB0E26857EA7"

    digests = [probe["digest"] for probe in section["collision_probes"]]
    assert digests == list(LOCKED_PROBE_DIGESTS)
    assert len(set(digests)) == 8, "the probes must stay distinct"

    for vector in section["decimal_separator"]["vectors"]:
        assert vector["point"] == vector["comma"].replace(",", "."), vector
        assert vector["comma"].count(",") <= 1

    remainders = [entry["remainder"] for entry in section["reduction_vectors"]]
    assert remainders == list(LOCKED_REDUCTION_REMAINDERS)
    for entry in section["reduction_vectors"]:
        assert entry["double_only_remainder"] == entry["remainder"]
    assert section["reduction_vectors"][0]["x"] == 281320423161
    assert section["constants"] == {
        **LOCKED_HASH_CONSTANTS, "FP_VERSION": 1, "STREAM_TAG": "PCCM-FP",
        "SECTION_ORDER": ["HEADER", "COST", "RISK"],
    }


def test_the_emitted_plan_case_values_match_the_hand_derived_literals() -> None:
    """Plan section 23's own numbers, restated here, against the emitted corpus."""
    cases = {case["id"]: case for case in _built()["cases"]["plan_cases"]}
    for identifier, expected in PLAN_LITERALS.items():
        case = cases[identifier]
        assert case["kind"] == "analytical", identifier
        payload = case["expected"]
        driver = payload["drivers"][0]
        for key, value in expected.items():
            if key in payload["totals"]:
                _close(payload["totals"][key], value, f"case {identifier} {key}")
            else:
                _close(driver[key], value, f"case {identifier} {key}")


def test_every_declared_refusal_case_is_actually_refused() -> None:
    """The corpus says a model must be refused; the oracle must agree, and the
    refusal CLASS is part of the expectation."""
    cases = _built()["cases"]["plan_cases"]
    refusals = {case["id"]: case["expected_refusal"]
                for case in cases if case["kind"] == "refusal"}
    assert refusals == {
        14: "ModelInputRefusal", 15: "ModelInputRefusal", 16: "ModelInputRefusal",
        17: "ModelInputRefusal", 18: "ModelInputRefusal", 20: "ModelInputRefusal",
        23: "ModelInputRefusal", 24: "NumericalRangeRefusal",
        29: "NumericalRangeRefusal",
    }


def test_case_28_statistics_are_the_locked_stable_form_results() -> None:
    case = next(c for c in _built()["cases"]["plan_cases"] if c["id"] == 28)
    values = {(item["statistic"], tuple(item["points"])): item["expected"]
              for item in case["statistics"]}
    assert values[("triangular_mean", (1e308, 1e308, 1e308))] == 1e308
    assert values[("beta_pert_mean", (1e308, 1e308, 1e308))] == 1e308
    assert values[("midpoint", (1.5e308, 1.5e308))] == 1.5e308


def test_case_31_emits_the_base_year_factor_row() -> None:
    """Base 2026, Start 2028: a 2026 row with a blank rate and a factor of exactly 1."""
    case = next(c for c in _built()["cases"]["plan_cases"] if c["id"] == 31)
    rows = case["expected"]["inflation_factors"]
    base = next(row for row in rows if row["calendar_year"] == 2026)
    assert base["annual_rate"] is None, base
    assert base["cumulative_factor"] == 1.0, base
    assert {row["calendar_year"] for row in rows} >= {2026, 2027, 2028}


# ---------------------------------------------------------------------------
# 5. THE INDEPENDENT REFERENCE, AND THE PATH LEDGER
# ---------------------------------------------------------------------------
# `phase5_cases.json` is generated BY the accepted oracle, so comparing it back to
# that oracle proves nothing. Everything below re-derives the corpus a second time,
# from the plan's rules, using only `Fraction`, plain Double arithmetic and locked
# literals written out in this file. It calls neither `calc_oracle.calculate`, nor
# `calc_cases.evaluate`, nor any production rescue helper.
#
# THE INVARIANT: no expected value may enter the Windows acceptance corpus without
# an independent Gate-A proof. That is enforced by a LEDGER rather than by a
# numeric floor - every expectation leaf in the JSON is enumerated, every check
# records the path it validated, and the two sets must be identical. A corpus that
# grows a new expected field without a matching check fails.
class _Ledger:
    """Records which expectation paths were independently validated."""

    def __init__(self) -> None:
        self.checked: set[str] = set()

    def mark(self, path: str) -> None:
        self.checked.add(path)

    def equal(self, path: str, actual, expected) -> None:
        assert actual == expected, f"{path}: emitted {actual!r}, independently {expected!r}"
        self.mark(path)

    def number(self, path: str, actual, expected) -> None:
        """A Double the corpus emitted, against the independently derived value.

        EXACT EQUALITY, with no tolerance and no scale. The independent reference
        deliberately reproduces the ACCEPTED EVALUATION SEMANTICS - tier 1's
        ordinary Double path where it succeeds, the exact rescue where it does
        not, the materialization boundaries, canonical driver order and the stable
        statistic forms - so it produces the very Double the corpus is expected to
        contain, not an idealised real number it should be near.

        THE EARLIER VERSION OF THIS METHOD WAS A DEFECT. It carried a `scale`
        taken from the largest magnitude anywhere in the payload and applied it to
        every field, so in a fixture with an annual row near `MAX_DOUBLE` the
        allowance was about `1.8e297` and `mean_value = 1e200` was accepted in
        place of `1.0`. Path coverage without discrimination proves nothing, and a
        C1-style conditioning scale belongs to RECONCILIATION - the question of
        whether two independently accumulated totals agree - never to the question
        of whether one emitted field equals its independently derived value.

        `None` (a field that does not apply to a driver kind) compares by equality
        too, so a blank can never be satisfied by a number or the reverse.
        """
        assert actual == expected, f"{path}: emitted {actual!r}, independently {expected!r}"
        self.mark(path)


def _leaf_paths(node, prefix: str):
    if isinstance(node, dict):
        for key in node:
            yield from _leaf_paths(node[key], f"{prefix}.{key}")
    elif isinstance(node, list):
        for index, item in enumerate(node):
            yield from _leaf_paths(item, f"{prefix}[{index}]")
    else:
        yield prefix


def _expectation_paths(document: dict) -> set[str]:
    """Every leaf the corpus asserts as an EXPECTATION.

    Model inputs (`model`, `terms`, `factors`, `points`), titles and prose are not
    expectations and are excluded; the whole `fingerprint` subtree is included,
    because every leaf under it is a locked value.
    """
    paths: set[str] = set()
    for index, case in enumerate(document["plan_cases"]):
        base = f"plan_cases[{index}]"
        if "expected" in case:
            paths |= set(_leaf_paths(case["expected"], f"{base}.expected"))
        if "expected_refusal" in case:
            paths.add(f"{base}.expected_refusal")
        for ordinal in range(len(case.get("statistics", []))):
            paths.add(f"{base}.statistics[{ordinal}].expected")
    for key in document["regression_vectors"]:
        for index, entry in enumerate(document["regression_vectors"][key]):
            base = f"regression_vectors.{key}[{index}]"
            if "expected" in entry:
                paths |= set(_leaf_paths(entry["expected"], f"{base}.expected"))
            if "expected_refusal" in entry:
                paths.add(f"{base}.expected_refusal")
    paths |= set(_leaf_paths(document["fingerprint"], "fingerprint"))
    return paths


# --- independent Double and exact-rational primitives -----------------------
_MAX_DOUBLE = 1.7976931348623157e308
_EXACT_MAX = Fraction(_MAX_DOUBLE)


def _rounded(value: Fraction):
    """The correctly rounded Double of an exact value, or `None` when there is
    none - out of range, or a non-zero value that rounds to zero."""
    if abs(value) > _EXACT_MAX:
        return None
    result = float(value)
    if result == 0.0 and value != 0:
        return None
    return result


def _double_product(factors):
    """Tier 1 of a product: left to right, refusing overflow and a non-zero
    collapse to zero. `None` means tier 1 produced no value."""
    result = 1.0
    for factor in factors:
        previous = result
        result = result * factor
        if not math.isfinite(result):
            return None
        if result == 0.0 and previous != 0.0 and factor != 0.0:
            return None
    return result


def _double_sum(terms):
    """Tier 1 of a sum: canonical order, left to right. `None` means it overflowed."""
    total = 0.0
    for term in terms:
        total = total + term
        if not math.isfinite(total):
            return None
    return total


def _exact_product(factors) -> Fraction:
    exact = Fraction(1)
    for factor in factors:
        exact = exact * Fraction(factor)
    return exact


def _value_of(factors):
    """One materialized product, under the accepted two tiers."""
    staged = _double_product(factors)
    if staged is not None:
        return staged
    return _rounded(_exact_product(factors))


def _series_of(groups):
    """One published series: the staged path, then the exact compound form.

    This is the accepted materialization rule written out from the specification -
    a per-driver contribution is not a published value, so the series falls back to
    one exact expression rather than refusing.
    """
    staged = [_double_product(group) for group in groups]
    if all(term is not None for term in staged):
        total = _double_sum(staged)
        if total is not None:
            return total
    exact = sum((_exact_product(group) for group in groups), Fraction(0))
    return _rounded(exact)


def _statistic_of(distribution: str, minimum, most_likely, maximum):
    """The plan's mandated stable forms, and the exact statistic they approximate.

    Returns `(double, exact)`: the stable form's own Double, and the exact rational
    the corpus is allowed to differ from by ordinary rounding.
    """
    low, high = float(minimum), float(maximum)
    if distribution == "Uniform":
        exact = (Fraction(low) + Fraction(high)) / 2
        if low == high:
            return low, exact                       # degenerate: exact by invariant
        return low / 2.0 + high / 2.0, exact
    middle = float(most_likely)
    if distribution == "Triangular":
        exact = (Fraction(low) + Fraction(middle) + Fraction(high)) / 3
        if low == middle == high:
            return low, exact
        return low / 3.0 + middle / 3.0 + high / 3.0, exact
    if distribution == "Beta-PERT":
        exact = (Fraction(low) + 4 * Fraction(middle) + Fraction(high)) / 6
        if low == middle == high:
            return low, exact
        return low / 6.0 + middle * (2.0 / 3.0) + high / 6.0, exact
    raise AssertionError(distribution)


_CENTRAL_BASIS = {"Triangular": "ML", "Beta-PERT": "ML", "Uniform": "Midpoint"}


def _reference_payload(model: dict) -> dict:
    """The COMPLETE expected payload of one analytical model, derived independently.

    Every field the corpus emits: the resolved FX map, the inflation factor rows,
    the discount series, all twenty-one driver fields plus the weights, all eight
    annual fields, and all ten headline totals.
    """
    timeline = model["timeline"]
    base, start, duration = (
        timeline["base_year"], timeline["start_year"], timeline["duration"]
    )
    years = [start + offset for offset in range(duration)]
    last = years[-1]

    # --- referenced-only resolution -----------------------------------------
    entries = sorted(model["cost_lines"] + model["risks"],
                     key=lambda d: d["permanent_id"])
    # REFERENCED-ONLY, strictly: a currency nothing points at is not resolved, and
    # the reporting currency is no exception when no driver uses it.
    referenced_currencies = {entry["currency"] for entry in entries}
    referenced_profiles = {entry["inflation_profile"] for entry in entries}
    rates = {row["currency"]: row["rate"] for row in model["fx"]}
    resolved_fx = {
        currency: float(rates[currency])
        for currency in sorted(referenced_currencies)
    }

    factors: dict[str, dict[int, float]] = {}
    inflation_rows: list[dict] = []
    for profile in sorted(referenced_profiles):
        declared = model["inflation"][profile]
        running = 1.0
        table = {base: 1.0}
        inflation_rows.append({"profile": profile, "calendar_year": base,
                               "annual_rate": None, "cumulative_factor": 1.0})
        for year in range(base + 1, last + 1):
            rate = float(declared[str(year)])
            running = running * (1.0 + rate)
            table[year] = running
            inflation_rows.append({"profile": profile, "calendar_year": year,
                                   "annual_rate": rate, "cumulative_factor": running})
        factors[profile] = table

    discount_rate = float(model["discount_rate"])
    discount = {1: 1.0}
    for index in range(2, duration + 1):
        discount[index] = discount[index - 1] / (1.0 + discount_rate)

    # --- per driver ----------------------------------------------------------
    drivers: list[dict] = []
    for entry in entries:
        is_risk = "probability" in entry
        weights = [float(w) for w in entry["profile_weights"]]
        table = factors[entry["inflation_profile"]]
        fx_rate = resolved_fx[entry["currency"]]

        nominal_terms = [[weights[i], table[years[i]]] for i in range(duration)]
        present_terms = [
            [weights[i], table[years[i]], discount[i + 1]] for i in range(duration)
        ]

        def factor(staged_groups, compound_groups):
            terms = [_double_product(group) for group in staged_groups]
            if all(term is not None for term in terms):
                total = _double_sum(terms)
                if total is not None:
                    scaled = total * fx_rate
                    if math.isfinite(scaled) and not (
                        scaled == 0.0 and total != 0.0 and fx_rate != 0.0
                    ):
                        return scaled
            exact = sum((_exact_product(group) for group in compound_groups),
                        Fraction(0))
            return _rounded(exact)

        knom = factor(nominal_terms, [[fx_rate] + group for group in nominal_terms])
        kpv = factor(present_terms, [[fx_rate] + group for group in present_terms])

        central, central_exact = _statistic_of(
            entry["distribution"], entry["min_value"],
            entry.get("most_likely"), entry["max_value"],
        )
        if entry["distribution"] != "Uniform":
            central, central_exact = float(entry["most_likely"]), Fraction(
                entry["most_likely"]
            )
            _, mean_exact = _statistic_of(
                entry["distribution"], entry["min_value"],
                entry["most_likely"], entry["max_value"],
            )
            mean, _ = _statistic_of(
                entry["distribution"], entry["min_value"],
                entry["most_likely"], entry["max_value"],
            )
        else:
            mean, mean_exact = central, central_exact

        multiplier = float(entry["probability"] if is_risk else entry["quantity"])
        shift = mean - central

        drivers.append({
            "permanent_id": entry["permanent_id"],
            "driver_kind": "Risk" if is_risk else "Cost Line",
            "distribution": entry["distribution"],
            "central_basis": _CENTRAL_BASIS[entry["distribution"]],
            "currency": entry["currency"],
            "fx_to_sar": fx_rate,
            "inflation_profile": entry["inflation_profile"],
            "quantity": None if is_risk else multiplier,
            "probability": multiplier if is_risk else None,
            "central_value": None if is_risk else central,
            "mean_value": mean,
            "knom": knom,
            "kpv": kpv,
            "deterministic_nominal":
                None if is_risk else _value_of([central, multiplier, knom]),
            "deterministic_pv":
                None if is_risk else _value_of([central, multiplier, kpv]),
            "mean_basis_nominal":
                None if is_risk else _value_of([mean, multiplier, knom]),
            "mean_basis_pv":
                None if is_risk else _value_of([mean, multiplier, kpv]),
            "uncertainty_mean_shift_nominal":
                None if is_risk else _value_of([shift, multiplier, knom]),
            "uncertainty_mean_shift_pv":
                None if is_risk else _value_of([shift, multiplier, kpv]),
            "expected_risk_nominal":
                _value_of([multiplier, mean, knom]) if is_risk else None,
            "expected_risk_pv":
                _value_of([multiplier, mean, kpv]) if is_risk else None,
            "weights": weights,
            "_exact_mean": mean_exact,
            "_exact_central": central_exact,
            "_multiplier": multiplier,
            "_fx": fx_rate,
            "_table": table,
        })

    # --- annual --------------------------------------------------------------
    annual: list[dict] = []
    for offset, year in enumerate(years):
        factor_of = discount[offset + 1]

        def groups(risk: bool, discounted: bool):
            built = []
            for driver in drivers:
                if (driver["driver_kind"] == "Risk") is not risk:
                    continue
                base_group = [
                    driver["mean_value"], driver["_multiplier"], driver["_fx"],
                    driver["weights"][offset], driver["_table"][year],
                ]
                built.append(base_group + [factor_of] if discounted else base_group)
            return built

        def staged_pv(risk: bool):
            """PV's tier 1 forms `nominal * discount` from the MATERIALIZED nominal."""
            terms = []
            for group in groups(risk, False):
                nominal = _double_product(group)
                if nominal is None:
                    return None
                present = _double_product([nominal, factor_of])
                if present is None:
                    return None
                terms.append(present)
            total = _double_sum(terms)
            return total

        def series(risk: bool, discounted: bool):
            if discounted:
                staged = staged_pv(risk)
                if staged is not None:
                    return staged
                exact = sum(
                    (_exact_product(group) for group in groups(risk, True)), Fraction(0)
                )
                return _rounded(exact)
            return _series_of(groups(risk, False))

        def total_series(discounted: bool):
            combined = groups(False, discounted) + groups(True, discounted)
            if discounted:
                terms = []
                for group in groups(False, False) + groups(True, False):
                    nominal = _double_product(group)
                    if nominal is None:
                        terms = None
                        break
                    present = _double_product([nominal, factor_of])
                    if present is None:
                        terms = None
                        break
                    terms.append(present)
                if terms is not None:
                    total = _double_sum(terms)
                    if total is not None:
                        return total
                exact = sum((_exact_product(group) for group in combined), Fraction(0))
                return _rounded(exact)
            return _series_of(combined)

        annual.append({
            "project_index": offset + 1,
            "calendar_year": year,
            "base_cost_nominal": series(False, False),
            "expected_risk_nominal": series(True, False),
            "total_nominal": total_series(False),
            "base_cost_pv": series(False, True),
            "expected_risk_pv": series(True, True),
            "total_pv": total_series(True),
        })

    # --- headline totals, accumulated in canonical driver order --------------
    def headline(key: str, risk: bool):
        terms = [d[key] for d in drivers
                 if (d["driver_kind"] == "Risk") is risk and d[key] is not None]
        total = _double_sum(terms)
        if total is not None:
            return total
        exact = sum((Fraction(term) for term in terms), Fraction(0))
        return _rounded(exact)

    a_nom, a_pv = headline("deterministic_nominal", False), headline("deterministic_pv", False)
    b_nom, b_pv = (headline("uncertainty_mean_shift_nominal", False),
                   headline("uncertainty_mean_shift_pv", False))
    c_nom, c_pv = headline("mean_basis_nominal", False), headline("mean_basis_pv", False)
    d_nom, d_pv = headline("expected_risk_nominal", True), headline("expected_risk_pv", True)

    def combined(cost_key: str, risk_key: str):
        terms = [d[cost_key] if d["driver_kind"] != "Risk" else d[risk_key]
                 for d in drivers]
        total = _double_sum([t for t in terms if t is not None])
        if total is not None:
            return total
        return _rounded(sum((Fraction(t) for t in terms if t is not None), Fraction(0)))

    return {
        "resolved_fx": resolved_fx,
        "inflation_factors": inflation_rows,
        "discount_factors": {str(k): v for k, v in sorted(discount.items())},
        "drivers": drivers,
        "annual": annual,
        "totals": {
            "a_nom": a_nom, "a_pv": a_pv, "b_nom": b_nom, "b_pv": b_pv,
            "c_nom": c_nom, "c_pv": c_pv, "d_nom": d_nom, "d_pv": d_pv,
            "e_nom": combined("mean_basis_nominal", "expected_risk_nominal"),
            "e_pv": combined("mean_basis_pv", "expected_risk_pv"),
        },
    }


_DRIVER_TEXT_FIELDS = (
    "permanent_id", "driver_kind", "distribution", "central_basis", "currency",
    "inflation_profile",
)
_DRIVER_NUMBER_FIELDS = (
    "fx_to_sar", "quantity", "probability", "central_value", "mean_value",
    "knom", "kpv", "deterministic_nominal", "deterministic_pv",
    "mean_basis_nominal", "mean_basis_pv", "uncertainty_mean_shift_nominal",
    "uncertainty_mean_shift_pv", "expected_risk_nominal", "expected_risk_pv",
)
_ANNUAL_NUMBER_FIELDS = (
    "base_cost_nominal", "expected_risk_nominal", "total_nominal",
    "base_cost_pv", "expected_risk_pv", "total_pv",
)


def _check_payload(ledger: _Ledger, base: str, emitted: dict, model: dict) -> None:
    """Validate a COMPLETE emitted expected payload against the independent one."""
    reference = _reference_payload(model)

    assert set(emitted["resolved_fx"]) == set(reference["resolved_fx"]), (
        f"{base}.resolved_fx: emitted {sorted(emitted['resolved_fx'])}, "
        f"independently {sorted(reference['resolved_fx'])}"
    )
    for currency, rate in reference["resolved_fx"].items():
        ledger.number(f"{base}.resolved_fx.{currency}",
                      emitted["resolved_fx"][currency], rate)

    assert len(emitted["inflation_factors"]) == len(reference["inflation_factors"]), base
    for index, row in enumerate(reference["inflation_factors"]):
        path = f"{base}.inflation_factors[{index}]"
        ledger.equal(f"{path}.profile", emitted["inflation_factors"][index]["profile"],
                     row["profile"])
        ledger.equal(f"{path}.calendar_year",
                     emitted["inflation_factors"][index]["calendar_year"],
                     row["calendar_year"])
        ledger.number(f"{path}.annual_rate",
                      emitted["inflation_factors"][index]["annual_rate"], row["annual_rate"])
        ledger.number(f"{path}.cumulative_factor",
                      emitted["inflation_factors"][index]["cumulative_factor"],
                      row["cumulative_factor"])

    assert set(emitted["discount_factors"]) == set(reference["discount_factors"]), base
    for key, value in reference["discount_factors"].items():
        ledger.number(f"{base}.discount_factors.{key}",
                      emitted["discount_factors"][key], value)

    assert len(emitted["drivers"]) == len(reference["drivers"]), base
    for index, driver in enumerate(reference["drivers"]):
        path = f"{base}.drivers[{index}]"
        for field in _DRIVER_TEXT_FIELDS:
            ledger.equal(f"{path}.{field}", emitted["drivers"][index][field], driver[field])
        for field in _DRIVER_NUMBER_FIELDS:
            ledger.number(f"{path}.{field}", emitted["drivers"][index][field],
                          driver[field])
        assert len(emitted["drivers"][index]["weights"]) == len(driver["weights"])
        for ordinal, weight in enumerate(driver["weights"]):
            ledger.number(f"{path}.weights[{ordinal}]",
                          emitted["drivers"][index]["weights"][ordinal], weight)

    assert len(emitted["annual"]) == len(reference["annual"]), base
    for index, row in enumerate(reference["annual"]):
        path = f"{base}.annual[{index}]"
        ledger.equal(f"{path}.project_index", emitted["annual"][index]["project_index"],
                     row["project_index"])
        ledger.equal(f"{path}.calendar_year", emitted["annual"][index]["calendar_year"],
                     row["calendar_year"])
        for field in _ANNUAL_NUMBER_FIELDS:
            ledger.number(f"{path}.{field}", emitted["annual"][index][field], row[field])

    for field, value in reference["totals"].items():
        ledger.number(f"{base}.totals.{field}", emitted["totals"][field], value)


# --- helper-level vectors, classified from exact arithmetic ------------------
def _classify(exact: Fraction):
    """`(kind, correctly rounded Double)` for an exact value, range-tested EXACTLY.

    `abs(exact) <= Fraction(MAX_DOUBLE)` is tested before `float(exact)`, because a
    value can exceed `MAX_DOUBLE` and still round down to it.
    """
    if abs(exact) > _EXACT_MAX:
        return "out-of-range", None
    target = float(exact)
    if exact != 0 and target == 0.0:
        return "collapsed", None
    return "value", target


def _check_helper_vector(
    ledger: _Ledger, path: str, entry: dict, exact: Fraction,
    tier_one=None, classify_zero: bool = False,
) -> None:
    """One helper-level vector, judged by the accepted two-tier rule.

    TIER 1 OWNS ITS RESULT. `[1e16, 1, -1e16]` sums to `0.0` in canonical order and
    to `1.0` in exact arithmetic, and `0.0` is the required answer - the corpus
    would be wrong to carry the exact value there. So the reference is tier 1 where
    tier 1 produced a value, and the exact classification only where it did not.

    `classify_zero` is the one extra rule the convex statistics carry: a
    NON-DEGENERATE statistic that evaluates to exactly zero is not accepted on
    sight, because the exact value may be non-zero with no usable Double.
    """
    if tier_one is not None and not (classify_zero and tier_one == 0.0):
        kind, target = "value", tier_one
    else:
        kind, target = _classify(exact)

    if "expected_refusal" in entry:
        assert kind != "value", (
            f"{path}: the corpus expects a refusal, but the value is {target!r}"
        )
        ledger.equal(f"{path}.expected_refusal", entry["expected_refusal"],
                     "NumericalRangeRefusal")
    else:
        assert kind == "value", (
            f"{path}: the corpus expects {entry['expected']!r}, but the value is {kind}"
        )
        ledger.number(f"{path}.expected", entry["expected"], target)


def _stable_form(statistic: str, points):
    """Tier 1 of a convex statistic: divide before accumulating, refusing a
    non-zero collapse to zero exactly as the accepted primitives do."""
    def divide(value: float, denominator: float):
        result = value / denominator
        if result == 0.0 and value != 0.0:
            return None
        return result

    if statistic == "midpoint":
        left, right = divide(points[0], 2.0), divide(points[1], 2.0)
        if left is None or right is None:
            return None
        total = left + right
    elif statistic == "triangular_mean":
        parts = [divide(point, 3.0) for point in points]
        if any(part is None for part in parts):
            return None
        total = parts[0] + parts[1] + parts[2]
    else:
        left, right = divide(points[0], 6.0), divide(points[2], 6.0)
        if left is None or right is None:
            return None
        total = left + points[1] * (2.0 / 3.0) + right
    return total if math.isfinite(total) else None


# ---------------------------------------------------------------------------
# 5a. the locked fingerprint corpus, hand-written
# ---------------------------------------------------------------------------
# Every leaf of the emitted `fingerprint` section, restated here from plan
# sections 11.3 to 11.7 and from the round-3 review's locked UTF-16 facts. This is
# the "separately hard-coded accepted literal" half of the evidence chain; the
# production generator derives its half from `calc_fingerprint.py`.
LOCKED_NUMERIC_ENCODINGS = (
    ("0", 0.0, "0.0000000000000000E+00"),
    ("-0", -0.0, "0.0000000000000000E+00"),
    ("1", 1.0, "1.0000000000000000E+00"),
    ("-1", -1.0, "-1.0000000000000000E+00"),
    ("0.1", 0.1, "1.0000000000000001E-01"),
    ("1e-20", 1e-20, "9.9999999999999995E-21"),
    ("1e+20", 1e20, "1.0000000000000000E+20"),
    ("0.1 + 0.2", 0.30000000000000004, "3.0000000000000004E-01"),
    ("MAX_DOUBLE", 1.7976931348623157e308, "1.7976931348623157E+308"),
    ("minimum subnormal", 5e-324, "4.9406564584124654E-324"),
)

LOCKED_SEPARATOR_EXTRA = (("-9.87e-5", -9.87e-5, "-9.8700000000000000E-05"),)

LOCKED_UTF16_VECTORS = (
    {"key": "bmp_above_7fff", "text": "高", "code_point_count": 1,
     "utf16_length": 1, "code_units": [39640], "signed_ascw": [-25896],
     "canonical_text_field": "S1:高"},
    {"key": "non_bmp", "text": "\U0001f600", "code_point_count": 1,
     "utf16_length": 2, "code_units": [55357, 56832], "signed_ascw": [-10179, -8704],
     "canonical_text_field": "S2:\U0001f600"},
    {"key": "mixed_length_prefix", "text": "A\U0001f600", "code_point_count": 2,
     "utf16_length": 3, "code_units": [65, 55357, 56832],
     "signed_ascw": [65, -10179, -8704], "canonical_text_field": "S3:A\U0001f600"},
)

LOCKED_PROBE_INPUTS = (
    ("A:B", "C"),
    ("A", "B:C"),
    ("AB", "C"),
    ("A", "B", "C"),
    ("A\u001fB", "C"),
    ("A\u0000B", "C"),
    ("A\u000aB", "C"),
    ("A", "\u001f", "C"),
)

LOCKED_REDUCTION_VECTORS = (
    ("FP_MOD_1", 2147483647, 2147483646, 65535, 281320423161, 65404),
    ("FP_MOD_2", 2147483629, 2147483628, 65535, 281320420803, 65404),
    ("FP_MOD_1", 2147483647, 1234567890, 41, 161728393631, 667120106),
    ("FP_MOD_2", 2147483629, 1234567890, 41, 161728393631, 667121456),
)


def _check_fingerprint(ledger: _Ledger, section: dict) -> None:
    """Every fingerprint leaf, against the literals above."""
    constants = section["constants"]
    for name, value in LOCKED_HASH_CONSTANTS.items():
        ledger.equal(f"fingerprint.constants.{name}", constants[name], value)
    ledger.equal("fingerprint.constants.FP_VERSION", constants["FP_VERSION"], 1)
    ledger.equal("fingerprint.constants.STREAM_TAG", constants["STREAM_TAG"], "PCCM-FP")
    for index, name in enumerate(("HEADER", "COST", "RISK")):
        ledger.equal(f"fingerprint.constants.SECTION_ORDER[{index}]",
                     constants["SECTION_ORDER"][index], name)
    assert set(constants) == set(LOCKED_HASH_CONSTANTS) | {
        "FP_VERSION", "STREAM_TAG", "SECTION_ORDER"
    }

    ledger.equal("fingerprint.reference.case", section["reference"]["case"], 26)
    ledger.equal("fingerprint.reference.stream", section["reference"]["stream"],
                 REFERENCE_STREAM)
    ledger.equal("fingerprint.reference.code_units",
                 section["reference"]["code_units"], REFERENCE_CODE_UNITS)
    ledger.equal("fingerprint.reference.digest", section["reference"]["digest"],
                 REFERENCE_DIGEST)

    assert len(section["collision_probes"]) == 8
    for index, probe in enumerate(section["collision_probes"]):
        path = f"fingerprint.collision_probes[{index}]"
        ledger.equal(f"{path}.case", probe["case"], 27)
        assert len(probe["values"]) == len(LOCKED_PROBE_INPUTS[index])
        for ordinal, value in enumerate(LOCKED_PROBE_INPUTS[index]):
            ledger.equal(f"{path}.values[{ordinal}]", probe["values"][ordinal], value)
        ledger.equal(f"{path}.digest", probe["digest"], LOCKED_PROBE_DIGESTS[index])
    assert len({p["digest"] for p in section["collision_probes"]}) == 8

    encodings = section["numeric_encodings"]
    ledger.equal("fingerprint.numeric_encodings.case", encodings["case"], 26)
    assert len(encodings["vectors"]) == len(LOCKED_NUMERIC_ENCODINGS) == 10
    for index, (label, value, expected) in enumerate(LOCKED_NUMERIC_ENCODINGS):
        path = f"fingerprint.numeric_encodings.vectors[{index}]"
        ledger.equal(f"{path}.label", encodings["vectors"][index]["label"], label)
        ledger.equal(f"{path}.value", encodings["vectors"][index]["value"], value)
        ledger.equal(f"{path}.expected", encodings["vectors"][index]["expected"], expected)
    # `-0` and `0` share an encoding but must remain distinguishable as records.
    assert encodings["vectors"][0]["label"] != encodings["vectors"][1]["label"]
    assert math.copysign(1.0, encodings["vectors"][1]["value"]) == -1.0

    utf16 = section["utf16_vectors"]
    ledger.equal("fingerprint.utf16_vectors.case", utf16["case"], 26)
    assert len(utf16["vectors"]) == len(LOCKED_UTF16_VECTORS) == 3
    for index, locked in enumerate(LOCKED_UTF16_VECTORS):
        path = f"fingerprint.utf16_vectors.vectors[{index}]"
        emitted = utf16["vectors"][index]
        for field in ("key", "text", "code_point_count", "utf16_length",
                      "canonical_text_field"):
            ledger.equal(f"{path}.{field}", emitted[field], locked[field])
        for field in ("code_units", "signed_ascw"):
            assert len(emitted[field]) == len(locked[field]), path
            for ordinal, value in enumerate(locked[field]):
                ledger.equal(f"{path}.{field}[{ordinal}]", emitted[field][ordinal], value)
        # the two locked behaviours, restated as properties rather than as data
        assert emitted["utf16_length"] == len(emitted["code_units"])
        for signed, unit in zip(emitted["signed_ascw"], emitted["code_units"]):
            assert (signed + 65536 if signed < 0 else signed) == unit, path
        assert emitted["canonical_text_field"] == (
            f"S{emitted['utf16_length']}:{emitted['text']}"
        )

    separator = section["decimal_separator"]
    ledger.equal("fingerprint.decimal_separator.case", separator["case"], 35)
    locked_separator = LOCKED_NUMERIC_ENCODINGS + LOCKED_SEPARATOR_EXTRA
    assert len(separator["vectors"]) == len(locked_separator) == 11
    for index, (label, value, expected) in enumerate(locked_separator):
        path = f"fingerprint.decimal_separator.vectors[{index}]"
        emitted = separator["vectors"][index]
        ledger.equal(f"{path}.label", emitted["label"], label)
        ledger.equal(f"{path}.value", emitted["value"], value)
        ledger.equal(f"{path}.expected", emitted["expected"], expected)
        # Both forms are compared with the LOCKED literal, not merely with each
        # other: `point == comma` proves invariance and nothing about correctness.
        # The canonical form always uses "." - a host separator of "," is
        # normalised away, which is exactly what case 35 locks - so BOTH must equal
        # the same locked literal.
        ledger.equal(f"{path}.point", emitted["point"], expected)
        ledger.equal(f"{path}.comma", emitted["comma"], expected)

    assert len(section["reduction_vectors"]) == 4
    for index, locked in enumerate(LOCKED_REDUCTION_VECTORS):
        name, modulus, h, u, x, remainder = locked
        path = f"fingerprint.reduction_vectors[{index}]"
        emitted = section["reduction_vectors"][index]
        ledger.equal(f"{path}.case", emitted["case"], 36)
        ledger.equal(f"{path}.modulus_name", emitted["modulus_name"], name)
        ledger.equal(f"{path}.modulus", emitted["modulus"], modulus)
        ledger.equal(f"{path}.h", emitted["h"], h)
        ledger.equal(f"{path}.u", emitted["u"], u)
        ledger.equal(f"{path}.x", emitted["x"], x)
        ledger.equal(f"{path}.remainder", emitted["remainder"], remainder)
        ledger.equal(f"{path}.double_only_remainder",
                     emitted["double_only_remainder"], remainder)
        # independently: x really is h * 131 + u, and the remainder really is x mod m
        assert x == h * 131 + u, path
        assert remainder == x % modulus, path
        assert x > 2147483647, "the vector must exceed Long.MaxValue or it proves nothing"


# ---------------------------------------------------------------------------
# 5b. the exhaustive independence test
# ---------------------------------------------------------------------------
_LOCKED_STATISTICS = {
    ("triangular_mean", (1e308, 1e308, 1e308)): 1e308,
    ("beta_pert_mean", (1e308, 1e308, 1e308)): 1e308,
    ("midpoint", (1.5e308, 1.5e308)): 1.5e308,
}

_LOCKED_REFUSALS = {
    14: "ModelInputRefusal", 15: "ModelInputRefusal", 16: "ModelInputRefusal",
    17: "ModelInputRefusal", 18: "ModelInputRefusal", 20: "ModelInputRefusal",
    23: "ModelInputRefusal", 24: "NumericalRangeRefusal", 29: "NumericalRangeRefusal",
}


def _validate_corpus(ledger: _Ledger, document: dict) -> None:
    for index, case in enumerate(document["plan_cases"]):
        base = f"plan_cases[{index}]"
        if case["kind"] == "analytical":
            _check_payload(ledger, f"{base}.expected", case["expected"], case["model"])
        elif case["kind"] == "refusal":
            ledger.equal(f"{base}.expected_refusal", case["expected_refusal"],
                         _LOCKED_REFUSALS[case["id"]])
        elif case["kind"] == "statistics":
            for ordinal, item in enumerate(case["statistics"]):
                key = (item["statistic"], tuple(item["points"]))
                ledger.equal(f"{base}.statistics[{ordinal}].expected",
                             item["expected"], _LOCKED_STATISTICS[key])

    vectors = document["regression_vectors"]
    for index, entry in enumerate(vectors["signed_sum"]):
        _check_helper_vector(
            ledger, f"regression_vectors.signed_sum[{index}]", entry,
            sum((Fraction(term) for term in entry["terms"]), Fraction(0)),
            tier_one=_double_sum(entry["terms"]),
        )
    for index, entry in enumerate(vectors["product"]):
        _check_helper_vector(
            ledger, f"regression_vectors.product[{index}]", entry,
            _exact_product(entry["factors"]),
            tier_one=_double_product(entry["factors"]),
        )
    for index, entry in enumerate(vectors["convex_statistics"]):
        points = entry["points"]
        weights = {"triangular_mean": (Fraction(1, 3),) * 3,
                   "beta_pert_mean": (Fraction(1, 6), Fraction(2, 3), Fraction(1, 6)),
                   "midpoint": (Fraction(1, 2), Fraction(1, 2))}[entry["statistic"]]
        exact = sum((w * Fraction(p) for w, p in zip(weights, points)), Fraction(0))
        if len(set(points)) == 1:
            # A zero-uncertainty distribution returns its point EXACTLY, which is a
            # stronger statement than "correctly rounded" for a subnormal point.
            assert entry["expected"] == points[0], entry["name"]
            ledger.mark(f"regression_vectors.convex_statistics[{index}].expected")
        else:
            _check_helper_vector(
                ledger, f"regression_vectors.convex_statistics[{index}]", entry, exact,
                tier_one=_stable_form(entry["statistic"], points), classify_zero=True,
            )
    for key in ("materialization", "conditioning", "row_order"):
        for index, entry in enumerate(vectors[key]):
            base = f"regression_vectors.{key}[{index}]"
            if "expected_refusal" in entry:
                _check_materialization_refusal(ledger, base, entry)
            else:
                _check_payload(ledger, f"{base}.expected", entry["expected"],
                               entry["model"])

    _check_fingerprint(ledger, document["fingerprint"])


def _check_materialization_refusal(ledger: _Ledger, base: str, entry: dict) -> None:
    """Independently prove the refusal is correct.

    The published boundary is a per-driver audit amount, so the proof is that
    CL-001's own Mean-Basis Nominal exceeds `MAX_DOUBLE` in exact arithmetic - even
    though the headline it feeds cancels to zero, which is exactly why the model
    still has to be refused.
    """
    model = entry["model"]
    driver = min(model["cost_lines"], key=lambda d: d["permanent_id"])
    profile = model["inflation"][driver["inflation_profile"]]
    base_year = model["timeline"]["base_year"]
    start = model["timeline"]["start_year"]
    factor = Fraction(1)
    for year in range(base_year + 1, start + model["timeline"]["duration"]):
        factor = factor * (1 + Fraction(profile[str(year)]))
    knom = factor * sum(
        (Fraction(w) for w in driver["profile_weights"]), Fraction(0)
    )
    amount = Fraction(driver["max_value"]) * Fraction(driver["quantity"]) * knom
    assert abs(amount) > _EXACT_MAX, (
        f"{base}: the published amount is {float(amount)!r}, which IS representable, "
        "so a refusal would be wrong"
    )
    headline = sum(
        (Fraction(d["max_value"]) * Fraction(d["quantity"]) * knom
         for d in model["cost_lines"]), Fraction(0)
    )
    assert headline == 0, f"{base}: the fixture must cancel in the headline"
    ledger.equal(f"{base}.expected_refusal", entry["expected_refusal"],
                 "NumericalRangeRefusal")


def test_every_emitted_expectation_is_independently_validated() -> None:
    """THE GOLDEN-INDEPENDENCE PROOF, accounted path by path.

    Enumerates every expectation leaf in `phase5_cases.json`, validates each one
    against an independently derived value or a hand-written locked literal, and
    requires the two SETS to be identical. A magic floor like `checked > 400` can
    pass while hundreds of values go untested; set equality cannot, and a corpus
    that grows a new expected field without a matching check fails immediately.
    """
    document = _built()["cases"]
    ledger = _Ledger()
    _validate_corpus(ledger, document)

    expected = _expectation_paths(document)
    missing = sorted(expected - ledger.checked)
    extra = sorted(ledger.checked - expected)
    assert not missing, (
        f"{len(missing)} emitted expectations were never independently validated, "
        f"for example {missing[:5]}"
    )
    assert not extra, f"the ledger recorded paths the corpus does not contain: {extra[:5]}"
    assert len(expected) > 1900, len(expected)


def test_the_independent_reference_disagrees_when_the_corpus_is_wrong() -> None:
    """The independence proof would be worthless if it could not fail."""
    document = json.loads(json.dumps(_built()["cases"]))
    case = next(c for c in document["plan_cases"]
                if c["kind"] == "analytical" and c["id"] == 1)
    case["expected"]["totals"]["a_nom"] = 1001.0
    try:
        _validate_corpus(_Ledger(), document)
    except AssertionError:
        return
    raise AssertionError("a tampered headline total passed the independence check")


def test_a_new_expected_field_cannot_escape_independent_validation() -> None:
    """The path ledger, working: an added expectation with no check fails."""
    document = json.loads(json.dumps(_built()["cases"]))
    target = next(entry for entry in document["regression_vectors"]["materialization"]
                  if "expected" in entry)
    target["expected"]["totals"]["f_nom"] = 1.0

    ledger = _Ledger()
    _validate_corpus(ledger, document)
    missing = _expectation_paths(document) - ledger.checked
    assert any(path.endswith("totals.f_nom") for path in missing), sorted(missing)[:5]


def test_a_tampered_non_spot_checked_regression_value_is_caught() -> None:
    """A value no earlier spot check ever looked at: an annual PV deep inside a
    materialization payload."""
    document = json.loads(json.dumps(_built()["cases"]))
    target = next(entry for entry in document["regression_vectors"]["materialization"]
                  if entry["name"].startswith("Reproducer B"))
    assert target["expected"]["annual"][2]["total_pv"] == 0.0
    target["expected"]["annual"][2]["total_pv"] = 1e-9
    try:
        _validate_corpus(_Ledger(), document)
    except AssertionError:
        return
    raise AssertionError("a tampered annual PV passed the independence check")


# ---------------------------------------------------------------------------
# 6. Stage A consumes, but does not calculate
# ---------------------------------------------------------------------------
def test_stage_a_renders_the_workspace_without_calling_the_oracle() -> None:
    """THE DISTINCTION THIS STEP TURNS ON.

    The workbook build must consume the calculation contract and must NOT call
    `calculate`. The oracle is replaced by one that raises, and the build still
    succeeds - proving no cell is populated by a calculation. The CASES generator
    is a separate artifact and is allowed to call it.
    """
    from pccm_builder import calc_oracle

    built = _built()
    genuine = calc_oracle.calculate

    def forbidden(*args, **kwargs):
        raise AssertionError("Stage-A workbook emission called the analytical oracle")

    calc_oracle.calculate = forbidden
    try:
        workbook, _ = build_workbook(
            built["spec"], built["contract"], built["drivers"], built["structure"],
            built["calc"],
        )
        directory = Path(tempfile.mkdtemp(prefix="pccm-step3-nocalc-"))
        try:
            path = directory / "out.xlsx"
            workbook.save(path)
            workbook.close()
            result = verify_workbook(
                path, built["spec"], built["contract"], built["drivers"],
                built["structure"], built["calc"],
            )
            assert result.ok, result.report()
        finally:
            shutil.rmtree(directory, ignore_errors=True)
    finally:
        calc_oracle.calculate = genuine


def test_the_renderer_does_not_import_the_analytical_oracle() -> None:
    """A structural guard: representation must not depend on calculation.

    Read from the AST, not from the text: this module's own docstring explains
    that it never imports the oracle, and a textual search would find that
    sentence and call it a violation.
    """
    import ast

    tree = ast.parse(
        (PCCM_ROOT / "builder" / "pccm_builder" / "calc_render.py").read_text(
            encoding="utf-8"
        )
    )
    imported: set[str] = set()
    called: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imported |= {alias.name for alias in node.names}
        elif isinstance(node, ast.ImportFrom):
            imported.add(node.module or "")
            imported |= {alias.name for alias in node.names}
        elif isinstance(node, ast.Call) and isinstance(node.func, ast.Name):
            called.add(node.func.id)
    for banned in ("calc_oracle", ".calc_oracle", "calculate", "CalculationModel",
                   "calc_numeric"):
        assert banned not in imported, f"calc_render.py imports {banned}"
    assert "calculate" not in called


def test_no_simulation_field_reaches_the_calculation_emission() -> None:
    """Phase 5 introduces no RNG and reads no Monte Carlo input."""
    for name in ("calc_render.py", "calc_emit.py", "calc_cases.py"):
        source = (PCCM_ROOT / "builder" / "pccm_builder" / name).read_text(encoding="utf-8")
        for banned in ("inpMonteCarloIterations", "inpRandomSeed",
                       "inpSelectedConfidenceLevel", "MRG32k3a", "Randomize",
                       "random", "seed"):
            assert banned not in source, f"{name} references {banned}"
    built = _built()
    without, _ = build_workbook(
        built["spec"], built["contract"], built["drivers"], built["structure"], None
    )
    with_calc, _ = build_workbook(
        built["spec"], built["contract"], built["drivers"], built["structure"],
        built["calc"],
    )
    try:
        before = [
            (cell.coordinate, cell.value)
            for row in without["_SimData"].iter_rows() for cell in row
            if cell.value is not None
        ]
        after = [
            (cell.coordinate, cell.value)
            for row in with_calc["_SimData"].iter_rows() for cell in row
            if cell.value is not None
        ]
        assert before == after, "_SimData changed when the calculation contract was added"
        assert not getattr(with_calc["_SimData"], "tables", {})
    finally:
        without.close()
        with_calc.close()


# ---------------------------------------------------------------------------
# 7. determinism
# ---------------------------------------------------------------------------
def test_the_generated_artifacts_are_byte_identical_across_builds() -> None:
    built = _built()
    first_module = render_calc_contract_module(built["spec"], built["calc"])
    second_module = render_calc_contract_module(built["spec"], built["calc"])
    assert first_module == second_module == built["module_text"]

    first_json = render_cases_json(built["spec"], built["calc"])
    second_json = render_cases_json(built["spec"], built["calc"])
    assert first_json == second_json
    assert json.loads(first_json) == built["cases"]


def test_the_generated_artifacts_carry_no_timestamp_or_machine_path() -> None:
    built = _built()
    for text in (built["module_text"], json.dumps(built["cases"])):
        for banned in ("/home/", "/tmp/", "C:\\", str(PCCM_ROOT)):
            assert banned not in text, f"{banned!r} leaked into a generated artifact"
    document = built["cases"]
    assert "generated_at" not in document and "timestamp" not in document
    assert set(document["provenance"]) == {
        "model_version", "calc_contract_version", "fingerprint_version",
        "oracle", "numerical_kernel", "fingerprint_authority",
    }


def test_the_build_script_produces_the_two_phase_five_artifacts_on_disk() -> None:
    """End to end, through the real entry point, reading the files from disk."""
    directory = Path(tempfile.mkdtemp(prefix="pccm-step3-cli-"))
    try:
        environment = dict(os.environ, PCCM_BUILD_TIMESTAMP="1970-01-01 00:00:00 UTC")
        completed = subprocess.run(
            [sys.executable, str(BUILD_SCRIPT), "--quiet",
             "--out", str(directory / "PCCM_stageA.xlsx")],
            capture_output=True, text=True, check=False, env=environment,
        )
        assert completed.returncode == 0, completed.stdout + completed.stderr
        module = directory / "vba" / "modCalcContract.bas"
        cases = directory / "phase5_cases.json"
        assert module.is_file() and cases.is_file()
        assert module.read_text(encoding="utf-8").startswith(
            'Attribute VB_Name = "modCalcContract"'
        )
        document = json.loads(cases.read_text(encoding="utf-8"))
        assert document["schema_version"] == 1
        assert len(document["plan_cases"]) == 37

        second = Path(tempfile.mkdtemp(prefix="pccm-step3-cli2-"))
        try:
            subprocess.run(
                [sys.executable, str(BUILD_SCRIPT), "--quiet",
                 "--out", str(second / "PCCM_stageA.xlsx")],
                capture_output=True, text=True, check=True, env=environment,
            )
            assert (second / "vba" / "modCalcContract.bas").read_bytes() == module.read_bytes()
            assert (second / "phase5_cases.json").read_bytes() == cases.read_bytes()
        finally:
            shutil.rmtree(second, ignore_errors=True)
    finally:
        shutil.rmtree(directory, ignore_errors=True)


def test_the_stage_a_xlsm_and_vba_boundary_is_unchanged() -> None:
    """`modCalcContract.bas` is a Stage-A artifact, not workbook content."""
    import zipfile

    with zipfile.ZipFile(_built()["path"]) as archive:
        names = archive.namelist()
    assert not any("vba" in name.lower() for name in names), names
    assert not any(name.endswith(".bas") for name in names)


def test_no_phase_five_vba_module_was_added_to_the_stage_b_manifest() -> None:
    """Step 3 emits generated constants only. The Phase-5 module inventory belongs
    to the later VBA implementation steps."""
    manifest = json.loads(
        (PCCM_ROOT / "build" / "stage_b_manifest.json").read_text(encoding="utf-8")
    ) if (PCCM_ROOT / "build" / "stage_b_manifest.json").is_file() else None
    if manifest is None:
        return
    text = json.dumps(manifest)
    for forbidden in ("modCalcFactors", "modCalcAnalytical", "modCalcFingerprint",
                      "modCalcResolve", "modCalcCheck", "modCalcReport",
                      "PCCM_Calculate"):
        assert forbidden not in text, f"{forbidden} appeared in the Stage-B manifest"


def test_the_stage_a_verification_is_extended_and_nothing_was_dropped() -> None:
    """THE COUNT, PROVED RATHER THAN ASSERTED.

    Step 3 extends post-build verification, so the number must go up. What must
    NOT happen is an old check being replaced by a broader one to keep the total
    small, so every prior check is matched by description and the new ones are
    counted as an addition.

    Run WITHOUT the calculation contract, one prior check legitimately fails - the
    "only contract-declared Excel Tables exist" gate, because the artifact now
    carries five tables the caller did not declare. That is the gate working, not
    a regression, and it is why the comparison is on the check SET rather than on
    the pass count.
    """
    built = _built()
    before = verify_workbook(
        built["path"], built["spec"], built["contract"], built["drivers"],
        built["structure"],
    )
    after = verify_workbook(
        built["path"], built["spec"], built["contract"], built["drivers"],
        built["structure"], built["calc"],
    )

    def names(result) -> list[str]:
        return result.passed + [f.split(" -- ", 1)[0] for f in result.failures]

    prior, extended = names(before), names(after)
    assert len(prior) == 181, f"the Phase-4 baseline moved: {len(prior)}"
    assert set(prior) <= set(extended), sorted(set(prior) - set(extended))[:5]
    assert after.ok, after.report()
    assert len(extended) == 351, len(extended)
    assert len(extended) - len(prior) == 170


# ---------------------------------------------------------------------------
# 8. NEGATIVE CONTROLS - the generated artifact is what is checked
# ---------------------------------------------------------------------------
def _verify_mutated(mutate) -> list[str]:
    """Build, mutate the saved workbook, re-verify. Returns the failures."""
    built = _built()
    directory = Path(tempfile.mkdtemp(prefix="pccm-step3-neg-"))
    try:
        workbook, _ = build_workbook(
            built["spec"], built["contract"], built["drivers"], built["structure"],
            built["calc"],
        )
        mutate(workbook["_Calc"], workbook)
        path = directory / "mutated.xlsx"
        workbook.save(path)
        workbook.close()
        result = verify_workbook(
            path, built["spec"], built["contract"], built["drivers"],
            built["structure"], built["calc"],
        )
        return result.failures
    finally:
        shutil.rmtree(directory, ignore_errors=True)


def _moved_table(name: str, reference: str):
    def mutate(worksheet, workbook):
        worksheet.tables[name].ref = reference
    return mutate


def test_the_verifier_catches_a_table_moved_one_column() -> None:
    failures = _verify_mutated(_moved_table("tblCalcYears", "I15:K16"))
    assert any("tblCalcYears" in f for f in failures), failures


def test_the_verifier_catches_a_table_widened_one_column() -> None:
    failures = _verify_mutated(_moved_table("tblCalcFX", "S15:V16"))
    assert any("tblCalcFX" in f for f in failures), failures


def test_the_verifier_catches_a_changed_header() -> None:
    def mutate(worksheet, workbook):
        worksheet["H15"] = "Project Idx"
    assert any("tblCalcYears" in f for f in _verify_mutated(mutate))


def test_the_verifier_catches_a_renamed_table() -> None:
    def mutate(worksheet, workbook):
        table = worksheet.tables["tblCalcAnnual"]
        del worksheet.tables["tblCalcAnnual"]
        table.name = table.displayName = "tblCalcAnnualX"
        worksheet.add_table(table)
    failures = _verify_mutated(mutate)
    assert any("Excel Tables" in f or "tblCalcAnnual" in f for f in failures), failures


def test_the_verifier_catches_a_moved_calc_state_row() -> None:
    def mutate(worksheet, workbook):
        worksheet["C17"] = None
        worksheet["C21"] = "NONE"
    assert any("calc_state" in f for f in _verify_mutated(mutate))


def test_the_verifier_catches_a_seeded_fingerprint_version() -> None:
    def mutate(worksheet, workbook):
        worksheet["C15"] = 1
    failures = _verify_mutated(mutate)
    assert any("fingerprint version" in f for f in failures), failures


def test_the_verifier_catches_a_calc_total_seeded_with_zero() -> None:
    def mutate(worksheet, workbook):
        worksheet["C27"] = 0
    failures = _verify_mutated(mutate)
    assert any("zero" in f or "calc_totals" in f for f in failures), failures


def test_the_verifier_catches_an_inserted_calculation_formula() -> None:
    def mutate(worksheet, workbook):
        worksheet["C23"] = "=SUM(AU16:AU20)"
    failures = _verify_mutated(mutate)
    assert any("formula" in f or "calc_totals" in f for f in failures), failures


def test_the_verifier_catches_an_overwritten_phase_four_counter() -> None:
    def mutate(worksheet, workbook):
        worksheet["C10"] = 7
    failures = _verify_mutated(mutate)
    assert any("Phase-4 counter" in f for f in failures), failures


def test_the_verifier_catches_a_fabricated_semantic_table_row() -> None:
    def mutate(worksheet, workbook):
        worksheet["H16"] = 1
        worksheet["I16"] = 2026
    failures = _verify_mutated(mutate)
    assert any("ZERO semantic rows" in f for f in failures), failures


def test_a_mutated_projected_tolerance_is_caught() -> None:
    """A projected constant that stops matching its authority fails the check."""
    import dataclasses

    from pccm_builder import calc_emit

    built = _built()
    calc = built["calc"]
    tampered = dataclasses.replace(
        calc, tolerances=dataclasses.replace(
            calc.tolerances, profiling_sum_absolute=1e-8
        )
    )
    text = calc_emit.render_calc_contract_module(built["spec"], tampered)
    value = next(
        line for line in text.splitlines()
        if line.startswith("Public Const TOL_PROFILING_SUM_ABSOLUTE")
    )
    assert "1e-08" in value
    assert value != next(
        line for line in built["module_text"].splitlines()
        if line.startswith("Public Const TOL_PROFILING_SUM_ABSOLUTE")
    )


def test_a_mutated_projected_hash_modulus_is_caught() -> None:
    from pccm_builder import calc_emit, calc_fingerprint

    built = _built()
    original = calc_fingerprint.FP_MOD_2
    try:
        calc_fingerprint.FP_MOD_2 = 2147483587
        text = calc_emit.render_calc_contract_module(built["spec"], built["calc"])
        assert "Public Const FP_MOD_2 As Long = 2147483587" in text
        assert "Public Const FP_MOD_2 As Long = 2147483629" in built["module_text"]
    finally:
        calc_fingerprint.FP_MOD_2 = original


def test_a_catastrophically_wrong_corpus_value_is_rejected() -> None:
    """DISCRIMINATION, not just coverage.

    Reproducer A publishes values near `MAX_DOUBLE` alongside values of `1.0`,
    `0.5` and `0.0`. An earlier version of this file scaled the comparison
    allowance by the largest magnitude anywhere in the payload, which made the
    allowance about `1.8e297` and accepted every one of the mutations below - each
    wrong by roughly two hundred orders of magnitude - while the path ledger still
    reported 1979 checked, 0 missing, 0 extra.

    Coverage without discrimination proves nothing, so each mutation is asserted
    to fail. The values are chosen to be the small ones sitting beside a huge one.
    """
    document = _built()["cases"]
    original = next(entry for entry in document["regression_vectors"]["materialization"]
                    if entry["name"].startswith("Reproducer A"))
    assert original["expected"]["drivers"][0]["mean_value"] == 1.0
    assert original["expected"]["drivers"][0]["central_value"] == 1.0
    assert original["expected"]["drivers"][0]["fx_to_sar"] == 0.5
    assert original["expected"]["totals"]["b_nom"] == 0.0
    assert original["expected"]["drivers"][0]["knom"] == _MAX_DOUBLE / 2, (
        "the fixture must still contain a value near MAX_DOUBLE, or the control "
        "no longer tests what it was written for"
    )

    mutations = (
        ("drivers[0].mean_value", lambda e: e["drivers"][0].__setitem__("mean_value", 1e200)),
        ("drivers[0].central_value",
         lambda e: e["drivers"][0].__setitem__("central_value", -1e200)),
        ("drivers[0].fx_to_sar", lambda e: e["drivers"][0].__setitem__("fx_to_sar", 1e200)),
        ("totals.b_nom", lambda e: e["totals"].__setitem__("b_nom", 1e200)),
    )
    for label, mutate in mutations:
        tampered = json.loads(json.dumps(document))
        target = next(entry for entry in tampered["regression_vectors"]["materialization"]
                      if entry["name"].startswith("Reproducer A"))
        mutate(target["expected"])
        try:
            _validate_corpus(_Ledger(), tampered)
        except AssertionError:
            continue
        raise AssertionError(f"a catastrophically wrong {label} passed the corpus check")


def test_a_blank_field_cannot_be_satisfied_by_a_number() -> None:
    """A field that does not apply to a driver kind is blank, and blank is not 0."""
    document = json.loads(json.dumps(_built()["cases"]))
    case = next(c for c in document["plan_cases"] if c["id"] == 8)
    assert case["expected"]["drivers"][0]["central_value"] is None
    case["expected"]["drivers"][0]["central_value"] = 0.0
    try:
        _validate_corpus(_Ledger(), document)
    except AssertionError:
        return
    raise AssertionError("a blank driver field was satisfied by zero")


def test_a_mutated_golden_expected_value_is_caught() -> None:
    """The independence check fails when the corpus and the independent reference
    disagree — the same proof as §5b, kept here beside the other negative controls."""
    document = json.loads(json.dumps(_built()["cases"]))
    case = next(c for c in document["plan_cases"] if c["id"] == 3)
    case["expected"]["drivers"][0]["knom"] = 1.11
    try:
        _validate_corpus(_Ledger(), document)
    except AssertionError:
        return
    raise AssertionError("a tampered golden value passed the independence check")


# ---------------------------------------------------------------------------
# runner
# ---------------------------------------------------------------------------
def _run_all() -> int:
    tests = sorted(
        (name, fn) for name, fn in globals().items()
        if name.startswith("test_") and callable(fn)
    )
    failures = 0
    print("PCCM Phase 5 Gate-A Step-3 Stage-A emission tests")
    print("=" * 70)
    for name, fn in tests:
        try:
            fn()
        except AssertionError as error:
            failures += 1
            print(f"  [FAIL] {name}\n         {error}")
        except Exception as error:  # noqa: BLE001
            failures += 1
            print(f"  [ERROR] {name}\n          {type(error).__name__}: {error}")
        else:
            print(f"  [PASS] {name}")
    print("=" * 70)
    print(f"  {len(tests) - failures} passed, {failures} failed")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(_run_all())
