#!/usr/bin/env python3
"""PCCM Phase 5 Gate-A Step-3 tests: Stage-A calculation workspace emission.

REPRESENTATION, NOT CALCULATION. Step 3 puts the physical `_Calc` workspace into
the generated workbook, projects the contract's runtime literals into
`modCalcContract.bas`, and emits the acceptance corpus `phase5_cases.json`.
Nothing in the build calculates a model into a cell.

--------------------------------------------------------------------------------
WHAT THIS FILE CHECKS, AND WHERE IT LOOKS
--------------------------------------------------------------------------------
The generated ARTIFACT, read back from disk. Proving that the contract says
`H:J` and that the renderer was called proves nothing about what shipped, so the
workbook is opened and its actual ListObject refs, cells, formats and validations
are asserted. The same for the two generated files: they are read as text and as
JSON, not as in-memory objects.

--------------------------------------------------------------------------------
GOLDEN INDEPENDENCE
--------------------------------------------------------------------------------
    hand-derived literal  ->  Python oracle  ->  phase5_cases.json  ->  later VBA

`phase5_cases.json` is generated BY the accepted oracle, so comparing it back to
that oracle would prove nothing. Every emitted number is therefore re-derived here
by a second, independently written route:

  * the plan's own section-23 literals, restated in this file;
  * `_exact_case`, an exact `Fraction` evaluator written from the plan's formulas
    and sharing no code with `calc_oracle.py`;
  * the fingerprint reference stream, its 366-code-unit length, its digest and the
    eight probe digests, restated here as literals.

PROOF SCOPE: Linux, Python, openpyxl. NO VBA IS EXECUTED. NO WINDOWS TEST IS RUN.

Runs standalone or under pytest.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import tempfile
from fractions import Fraction
from pathlib import Path

from openpyxl import load_workbook

PCCM_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PCCM_ROOT / "builder"))

from pccm_builder import (  # noqa: E402
    build_workbook,
    emit_calc_artifacts,
    load_calc_contract,
    load_contract,
    load_driver_contract,
    load_spec,
    load_structure_contract,
    verify_workbook,
)
from pccm_builder.calc_emit import (  # noqa: E402
    CALC_MODULE_NAME,
    render_calc_contract_module,
    render_cases_json,
)
from pccm_builder.calc_render import placeholder_row, table_ref  # noqa: E402

SPEC_PATH = PCCM_ROOT / "spec" / "workbook.yaml"
CONTRACT_PATH = PCCM_ROOT / "spec" / "input_contract.yaml"
DRIVERS_PATH = PCCM_ROOT / "spec" / "driver_contract.yaml"
STRUCTURE_PATH = PCCM_ROOT / "spec" / "structure_contract.yaml"
CALC_PATH = PCCM_ROOT / "spec" / "calc_contract.yaml"
BUILD_SCRIPT = PCCM_ROOT / "builder" / "build_stage_a.py"

# ---------------------------------------------------------------------------
# Locked literals - restated here so the emitted values have something
# independent to be wrong against.
# ---------------------------------------------------------------------------
LOCKED_TABLE_ANCHORS = {
    "tblCalcYears": (15, "H", "J", 3),
    "tblCalcInflationFactors": (15, "M", "P", 4),
    "tblCalcFX": (15, "S", "U", 3),
    "tblCalcDrivers": (15, "X", "AR", 21),
    "tblCalcAnnual": (15, "AU", "BB", 8),
}

LOCKED_CALC_STATE_INITIAL = {
    13: None, 14: None, 15: None, 16: None,
    17: "NONE", 18: None, 19: "NOT CALCULATED", 20: None,
}
LOCKED_CALC_TOTALS_ROWS = tuple(range(23, 33))

REFERENCE_STREAM = (
    "S7:PCCM-FPI1:1S6:HEADERI1:1I1:4"
    "N22:2.0260000000000000E+03N22:2.0260000000000000E+03"
    "N22:1.0000000000000000E+00N22:1.0000000000000001E-01"
    "S4:COSTI1:1I1:9S6:CL-001S10:Triangular"
    "N22:1.0000000000000000E+01N22:8.0000000000000000E+01"
    "N22:1.5000000000000000E+02N22:1.0000000000000000E+02"
    "N22:1.0000000000000000E+00N22:1.0000000000000000E+00"
    "N22:1.0000000000000000E+00"
    "S4:RISKI1:0"
)
REFERENCE_CODE_UNITS = 366
REFERENCE_DIGEST = "50B6EB0E26857EA7"

LOCKED_PROBE_DIGESTS = (
    "041ACBD05C7BF72C", "52704E9A542869CA", "0C8A057A0BE7EB51", "7674F1C35E639F98",
    "7D26D4C95587DE0C", "0821AFB0608291C8", "5B4CA2E133AD91A2", "101504AC7803B226",
)

LOCKED_REDUCTION_REMAINDERS = (65404, 65404, 667120106, 667121456)

LOCKED_TOLERANCES = {
    "profiling_sum_absolute": 1e-9,
    "identity_absolute_floor": 1e-6,
    "identity_relative_coefficient": 1e-12,
    "conditioning_scale_floor": 1.0,
}

LOCKED_HASH_CONSTANTS = {
    "FP_BASE": 131, "FP_MOD_1": 2147483647, "FP_MOD_2": 2147483629,
    "FP_INIT_1": 1, "FP_INIT_2": 1,
}

# Plan section 23, hand-derived. The design oracle for the cases it states.
PLAN_LITERALS = {
    1: {"knom": 1.0, "kpv": 1.0, "a_nom": 1000.0, "c_nom": 1100.0, "b_nom": 100.0},
    2: {"knom": 3.75, "a_nom": 1500.0},
    3: {"knom": 1.1085375, "a_nom": 1108.5375},
    4: {"kpv": 0.998150826446, "a_pv": 998.150826446, "c_pv": 1097.965909091},
    5: {"c_nom": 1219.39125, "b_nom": 110.85375},
    6: {"central_value": 100.0, "mean_value": 105.0},
    7: {"central_value": 115.0, "mean_value": 115.0, "b_nom": 0.0},
    8: {"mean_value": 250.0, "d_nom": 75.0},
    9: {"d_nom": 83.1403125, "d_pv": 74.8613119835},
    22: {"central_value": 115.0, "mean_value": 115.0},
}

REL = 1e-11


def _close(actual: float, expected: float, note: str = "", rel: float = REL) -> None:
    allowance = abs(expected) * rel + 1e-9
    assert abs(actual - expected) <= allowance, (
        f"{note or 'value'}: got {actual!r}, expected {expected!r}"
    )


# ---------------------------------------------------------------------------
# shared build
# ---------------------------------------------------------------------------
_ARTIFACTS: dict[str, object] = {}


def _built() -> dict:
    """One real build, reused. Every assertion reads it back from DISK."""
    if _ARTIFACTS:
        return _ARTIFACTS
    directory = Path(tempfile.mkdtemp(prefix="pccm-step3-"))
    spec = load_spec(SPEC_PATH)
    contract = load_contract(CONTRACT_PATH)
    drivers = load_driver_contract(DRIVERS_PATH)
    structure = load_structure_contract(STRUCTURE_PATH)
    calc = load_calc_contract(CALC_PATH)

    workbook, _ = build_workbook(spec, contract, drivers, structure, calc)
    path = directory / "PCCM_stageA.xlsx"
    workbook.save(path)
    workbook.close()
    artifacts = emit_calc_artifacts(directory, spec, calc)

    _ARTIFACTS.update(
        directory=directory, path=path, spec=spec, contract=contract, drivers=drivers,
        structure=structure, calc=calc,
        module_text=artifacts.module_path.read_text(encoding="utf-8"),
        cases=json.loads(artifacts.cases_path.read_text(encoding="utf-8")),
        module_path=artifacts.module_path, cases_path=artifacts.cases_path,
    )
    return _ARTIFACTS


def _sheet():
    workbook = load_workbook(_built()["path"])
    return workbook, workbook["_Calc"]


def _module_constants() -> dict[str, str]:
    """`name -> literal text` parsed out of the generated .bas, as VBA would see it."""
    found: dict[str, str] = {}
    for line in _built()["module_text"].splitlines():
        stripped = line.strip()
        if not stripped.startswith("Public Const "):
            continue
        declaration = stripped[len("Public Const "):]
        name, _, rest = declaration.partition(" As ")
        _, _, value = rest.partition(" = ")
        found[name.strip()] = value.split("    ' ")[0].strip()
    return found


def _const_number(name: str) -> float:
    return float(_module_constants()[name])


def _const_string(name: str) -> str:
    raw = _module_constants()[name]
    assert raw.startswith('"') and raw.endswith('"'), f"{name} is not a String literal"
    return raw[1:-1].replace('""', '"')


# ---------------------------------------------------------------------------
# 1. the calculation contract is a real build input
# ---------------------------------------------------------------------------
def test_the_build_consumes_the_calculation_contract() -> None:
    """`--calc-contract` exists, defaults to the project spec, and is reported."""
    completed = subprocess.run(
        [sys.executable, str(BUILD_SCRIPT), "--help"],
        capture_output=True, text=True, check=True,
    )
    assert "--calc-contract" in completed.stdout
    assert "calc_contract.yaml" in completed.stdout


def test_a_malformed_calculation_contract_fails_the_build_with_exit_code_two() -> None:
    """A calculation-contract-specific error, and a non-zero exit.

    The rule that rejects the mutation lives in the accepted Step-1 loader; what
    this proves is that the BUILDER consults it before emitting anything.
    """
    directory = Path(tempfile.mkdtemp(prefix="pccm-step3-bad-"))
    try:
        broken = directory / "calc_contract.yaml"
        text = CALC_PATH.read_text(encoding="utf-8")
        # A locked header spelling. The Step-1 loader owns the rule; what is proved
        # here is that the BUILDER runs it before emitting anything.
        broken.write_text(text.replace("header_row: 15", "header_row: 16", 1),
                          encoding="utf-8")
        completed = subprocess.run(
            [sys.executable, str(BUILD_SCRIPT), "--quiet",
             "--calc-contract", str(broken),
             "--out", str(directory / "out.xlsx")],
            capture_output=True, text=True, check=False,
        )
        assert completed.returncode == 2, completed.stdout + completed.stderr
        assert "CALCULATION CONTRACT ERROR" in completed.stderr, completed.stderr
        assert not (directory / "out.xlsx").exists(), (
            "a workbook was emitted despite an invalid calculation contract"
        )
    finally:
        shutil.rmtree(directory, ignore_errors=True)


def test_the_workbook_now_describes_itself_as_phase_five() -> None:
    spec = _built()["spec"]
    assert spec.model["model_version"] == "0.5.0"
    assert "Phase 5" in spec.model["build_phase"], spec.model["build_phase"]
    assert (PCCM_ROOT / "VERSION").read_text(encoding="utf-8").strip() == "0.5.0"


# ---------------------------------------------------------------------------
# 2. the physical _Calc anchors
# ---------------------------------------------------------------------------
def test_the_five_calculation_tables_exist_at_their_locked_physical_anchors() -> None:
    """Read out of the generated artifact, against literals restated here.

    Not "the contract says H:J and the renderer ran": the workbook is opened and
    its actual ListObject references are compared with the anchors the accepted
    design locks.
    """
    workbook, worksheet = _sheet()
    try:
        tables = worksheet.tables
        assert set(tables) == set(LOCKED_TABLE_ANCHORS), sorted(tables)
        for name, (header_row, first, last, width) in LOCKED_TABLE_ANCHORS.items():
            reference = tables[name].ref
            assert reference == f"{first}{header_row}:{last}{header_row + 1}", (
                f"{name} is at {reference}"
            )
            headers = [
                cell.value
                for cell in worksheet[f"{first}{header_row}:{last}{header_row}"][0]
            ]
            assert len(headers) == width, f"{name} is {len(headers)} columns wide"
            assert all(isinstance(h, str) and h for h in headers), headers
    finally:
        workbook.close()


def test_every_table_header_matches_the_contract_spelling_and_order() -> None:
    workbook, worksheet = _sheet()
    calc = _built()["calc"]
    try:
        for table in calc.all_tables:
            actual = [
                worksheet.cell(row=table.header_row, column=table.first_column_index + i).value
                for i in range(len(table.columns))
            ]
            assert actual == table.headers, f"{table.table_name}: {actual}"
    finally:
        workbook.close()


def test_the_calculation_workspace_has_zero_semantic_rows() -> None:
    """The physical body row is exactly one, and it is entirely blank.

    No project index, no calendar year, no SAR audit row, no dummy driver, no zero
    annual row and no Base-Year factor row: all of those are calculation outputs.
    """
    workbook, worksheet = _sheet()
    calc = _built()["calc"]
    try:
        for table in calc.all_tables:
            body = placeholder_row(table)
            assert table_ref(table).endswith(f"{body}")
            for index in range(len(table.columns)):
                cell = worksheet.cell(row=body, column=table.first_column_index + index)
                assert cell.value is None, (
                    f"{table.table_name} body cell {cell.coordinate} holds {cell.value!r}"
                )
            below = worksheet.cell(row=body + 1, column=table.first_column_index)
            assert below.value is None
    finally:
        workbook.close()


def test_the_scalar_blocks_are_at_their_locked_rows_with_their_locked_values() -> None:
    workbook, worksheet = _sheet()
    calc = _built()["calc"]
    try:
        assert (calc.calc_state.first_row, calc.calc_state.last_row) == (13, 20)
        assert (calc.calc_totals.first_row, calc.calc_totals.last_row) == (23, 32)
        for row, expected in LOCKED_CALC_STATE_INITIAL.items():
            assert worksheet[f"C{row}"].value == expected, (
                f"C{row} holds {worksheet[f'C{row}'].value!r}, expected {expected!r}"
            )
            assert worksheet[f"B{row}"].value, f"B{row} has no label"
        for row in LOCKED_CALC_TOTALS_ROWS:
            assert worksheet[f"C{row}"].value is None, (
                f"C{row} is seeded with {worksheet[f'C{row}'].value!r}; blank means no "
                "calculation has committed and zero would mean a total of zero"
            )
            assert worksheet[f"C{row}"].number_format == "#,##0.00"
            assert "—" in worksheet[f"B{row}"].value, worksheet[f"B{row}"].value
    finally:
        workbook.close()


def test_the_fingerprint_version_cell_ships_blank() -> None:
    """C15 stays blank even though the contract declares FP_VERSION = 1.

    The stamp records which algorithm produced the STORED digest, and there is no
    stored digest until a successful commit writes both together.
    """
    workbook, worksheet = _sheet()
    try:
        assert _built()["calc"].fingerprint_version == 1
        assert worksheet["C15"].value is None
        assert worksheet["C15"].number_format == "0"
    finally:
        workbook.close()


def test_phase_four_territory_on_calc_is_untouched() -> None:
    """Rows 1-11 are Phase-4 property. Phase 5 starts at row 13, not 12."""
    workbook, worksheet = _sheet()
    calc = _built()["calc"]
    try:
        assert worksheet["C10"].value == 0 and worksheet["C10"].number_format == "0"
        assert worksheet["C11"].value == 0 and worksheet["C11"].number_format == "0"
        assert worksheet["B10"].value == "Cost Line ID Counter"
        assert worksheet["B11"].value == "Risk ID Counter"
        assert calc.phase4_last_row == 11
        assert calc.calc_state.first_row == 13, "row 12 is a deliberate gap"
        for row in range(1, 13):
            for column in range(6, 60):
                assert worksheet.cell(row=row, column=column).value is None, (
                    f"Phase-5 content at row {row}, column {column}"
                )
    finally:
        workbook.close()


def test_the_calculation_workspace_carries_no_formula_and_no_validation() -> None:
    workbook, worksheet = _sheet()
    try:
        for row in worksheet.iter_rows():
            for cell in row:
                assert not (
                    isinstance(cell.value, str) and cell.value.startswith("=")
                ), f"formula at _Calc!{cell.coordinate}: {cell.value!r}"
        for validation in worksheet.data_validations.dataValidation:
            assert not str(validation.sqref).strip(), (
                f"data validation {validation.sqref} on the calculation workspace"
            )
    finally:
        workbook.close()


def test_the_sheet_inventory_and_visibility_are_unchanged() -> None:
    workbook, worksheet = _sheet()
    spec = _built()["spec"]
    try:
        assert workbook.sheetnames == spec.sheet_names
        assert len(workbook.sheetnames) == 14
        assert worksheet.sheet_state == "hidden"
        assert workbook["_SimData"].sheet_state == "veryHidden"
        assert worksheet.sheet_view.showGridLines
        assert workbook.active.title == spec.active_sheet
    finally:
        workbook.close()


def test_the_table_inventory_is_the_prior_set_plus_exactly_five() -> None:
    """The "only contract-declared Tables exist" gate is EXTENDED, not relaxed."""
    workbook, _ = _sheet()
    built = _built()
    try:
        found = {
            name for sheet in workbook.worksheets for name in getattr(sheet, "tables", {})
        }
        prior = {t.table_name for t in built["contract"].all_tables}
        prior |= {r.table_name for r in built["drivers"].all_registers}
        prior |= {g.table_name for g in built["structure"].all_grids}
        assert found == prior | set(LOCKED_TABLE_ANCHORS)
        assert len(found - prior) == 5
    finally:
        workbook.close()


# ---------------------------------------------------------------------------
# 3. modCalcContract.bas
# ---------------------------------------------------------------------------
def test_the_generated_module_has_the_required_preamble() -> None:
    text = _built()["module_text"]
    lines = text.splitlines()
    assert lines[0] == f'Attribute VB_Name = "{CALC_MODULE_NAME}"'
    assert lines[1] == "Option Explicit"
    assert "GENERATED FILE - DO NOT EDIT." in text
    assert "CONSTANTS ONLY" in text


def test_the_generated_module_declares_no_procedure_and_no_recurrence() -> None:
    """A constants module. No Sub, no Function, no hash loop, no formula."""
    text = _built()["module_text"]
    code = "\n".join(
        line for line in text.splitlines() if not line.strip().startswith("'")
    )
    for banned in ("Sub ", "Function ", "For ", "While ", "Mod ", "Fix(", "Rnd", "Randomize"):
        assert banned not in code, f"{banned!r} appears in generated code"


def test_the_projected_geometry_is_the_contracts_geometry() -> None:
    """Table names, header rows, first columns, widths and per-column ordinals."""
    calc = _built()["calc"]
    constants = _module_constants()
    for table in calc.all_tables:
        prefix = table.key.upper()
        assert _const_string(f"TBL_{prefix}") == table.table_name
        assert _const_number(f"TBL_{prefix}_HEADER_ROW") == table.header_row
        assert _const_string(f"TBL_{prefix}_FIRST_COLUMN") == table.first_column
        assert _const_string(f"TBL_{prefix}_LAST_COLUMN") == table.last_column
        assert _const_number(f"TBL_{prefix}_FIRST_COLUMN_INDEX") == table.first_column_index
        assert _const_number(f"TBL_{prefix}_COLUMN_COUNT") == len(table.columns)
        assert _const_string(f"TBL_{prefix}_EMPTY_REF") == table_ref(table)
        assert _const_number(f"TBL_{prefix}_FIRST_BODY_ROW") == placeholder_row(table)
        for ordinal, column in enumerate(table.columns, start=1):
            name = f"COL_{prefix}_{column.key.upper()}"
            assert name in constants, f"{name} was not projected"
            assert float(constants[name]) == ordinal


def test_the_projected_block_geometry_and_labels_are_the_contracts() -> None:
    calc = _built()["calc"]
    for block in (calc.calc_state, calc.calc_totals):
        prefix = block.key.upper()
        assert _const_string(f"{prefix}_VALUE_COLUMN") == block.value_column
        assert _const_number(f"{prefix}_FIRST_ROW") == block.first_row
        assert _const_number(f"{prefix}_LAST_ROW") == block.last_row
        assert _const_string(f"{prefix}_VALUE_RANGE") == block.value_range()
        for entry in block.fields:
            assert _const_number(f"{prefix}_ROW_{entry.key.upper()}") == entry.row
    for label in calc.derived_status_labels:
        assert _const_string(f"CALC_STATUS_{label.replace(' ', '_')}") == label
    for label in calc.attempt_result_labels:
        assert _const_string(f"CALC_ATTEMPT_{label}") == label


def test_the_projected_tolerances_are_the_contracts_and_the_locked_numbers() -> None:
    calc = _built()["calc"]
    assert _const_number("TOL_PROFILING_SUM_ABSOLUTE") == calc.tolerances.profiling_sum_absolute
    assert _const_number("TOL_IDENTITY_ABSOLUTE_FLOOR") == calc.tolerances.identity_absolute_floor
    assert _const_number("TOL_IDENTITY_RELATIVE_COEFFICIENT") == (
        calc.tolerances.identity_relative_coefficient
    )
    assert _const_number("TOL_CONDITIONING_SCALE_FLOOR") == (
        calc.tolerances.conditioning_scale_floor
    )
    # ... and against literals restated here, so a change to both the contract and
    # the projection at once is still visible.
    assert _const_number("TOL_PROFILING_SUM_ABSOLUTE") == LOCKED_TOLERANCES["profiling_sum_absolute"]
    assert _const_number("TOL_IDENTITY_ABSOLUTE_FLOOR") == LOCKED_TOLERANCES["identity_absolute_floor"]
    assert _const_number("TOL_IDENTITY_RELATIVE_COEFFICIENT") == (
        LOCKED_TOLERANCES["identity_relative_coefficient"]
    )
    assert _const_number("TOL_CONDITIONING_SCALE_FLOOR") == (
        LOCKED_TOLERANCES["conditioning_scale_floor"]
    )


def test_the_projected_fingerprint_version_comes_from_the_calculation_contract() -> None:
    assert _const_number("FP_VERSION") == _built()["calc"].fingerprint_version == 1


def test_the_projected_hash_constants_come_from_the_python_authority() -> None:
    """FP_BASE and the moduli are NOT in the YAML and must not be.

    `calc_fingerprint.py` is the reference implementation and owns the hash
    mathematics, so the generator imports it. Checked against the module's own
    attributes AND against the locked literals of plan section 11.4.
    """
    from pccm_builder import calc_fingerprint

    for name, locked in LOCKED_HASH_CONSTANTS.items():
        assert _const_number(name) == getattr(calc_fingerprint, name)
        assert _const_number(name) == locked
    assert _const_string("FP_STREAM_TAG") == calc_fingerprint.STREAM_TAG == "PCCM-FP"
    for index, section in enumerate(calc_fingerprint.SECTION_ORDER, start=1):
        assert _const_string(f"FP_SECTION_{index}") == section
    assert (
        CALC_PATH.read_text(encoding="utf-8").count("2147483647") == 0
    ), "a hash modulus leaked into the calculation contract, creating a second authority"


def test_mutating_the_hash_authority_changes_the_projection() -> None:
    """NO SECOND SOURCE OF TRUTH, proved by moving the source.

    The generator is re-run against a patched `calc_fingerprint` module; if the
    emitted constant did not follow, the .bas would be carrying its own literal.
    """
    from pccm_builder import calc_emit, calc_fingerprint

    built = _built()
    original = calc_fingerprint.FP_BASE
    try:
        calc_fingerprint.FP_BASE = 137
        text = calc_emit.render_calc_contract_module(built["spec"], built["calc"])
        assert "Public Const FP_BASE As Long = 137" in text
    finally:
        calc_fingerprint.FP_BASE = original
    assert "Public Const FP_BASE As Long = 131" in (
        calc_emit.render_calc_contract_module(built["spec"], built["calc"])
    )


def test_mutating_the_contract_changes_the_projected_geometry() -> None:
    """The same proof for the YAML-owned side."""
    import dataclasses

    from pccm_builder import calc_emit

    built = _built()
    calc = built["calc"]
    moved = dataclasses.replace(
        calc,
        tables={
            key: (dataclasses.replace(table, header_row=99) if key == "calc_years" else table)
            for key, table in calc.tables.items()
        },
    )
    text = calc_emit.render_calc_contract_module(built["spec"], moved)
    assert "Public Const TBL_CALC_YEARS_HEADER_ROW As Long = 99" in text
    assert "Public Const TBL_CALC_YEARS_HEADER_ROW As Long = 15" in built["module_text"]


# ---------------------------------------------------------------------------
# 4. phase5_cases.json - shape and independence
# ---------------------------------------------------------------------------
def test_the_case_corpus_covers_the_plan_matrix() -> None:
    cases = _built()["cases"]["plan_cases"]
    assert [case["id"] for case in cases] == list(range(1, 38))
    kinds = {case["id"]: case["kind"] for case in cases}
    assert {kinds[i] for i in (32, 33, 34, 37)} == {"runtime_only"}
    assert {kinds[i] for i in (26, 27, 35, 36)} == {"fingerprint"}
    for identifier in (32, 33, 34, 37):
        case = next(c for c in cases if c["id"] == identifier)
        assert "expected" not in case and "model" not in case, (
            f"case {identifier} is workbook-state behaviour; Python must not claim it"
        )
        assert case["why"]


def test_no_runtime_only_case_carries_a_fabricated_result() -> None:
    document = _built()["cases"]
    text = json.dumps(document)
    assert "Infinity" not in text and "NaN" not in text
    for case in document["plan_cases"]:
        if case["kind"] == "runtime_only":
            assert set(case) == {"id", "kind", "title", "why"}, case


def test_the_emitted_fingerprint_evidence_matches_the_locked_literals() -> None:
    """Case 26, 27, 35 and 36, against literals restated in THIS file."""
    section = _built()["cases"]["fingerprint"]
    assert section["reference"]["stream"] == REFERENCE_STREAM
    assert section["reference"]["code_units"] == REFERENCE_CODE_UNITS == 366
    assert section["reference"]["digest"] == REFERENCE_DIGEST == "50B6EB0E26857EA7"

    digests = [probe["digest"] for probe in section["collision_probes"]]
    assert digests == list(LOCKED_PROBE_DIGESTS)
    assert len(set(digests)) == 8, "the probes must stay distinct"

    for vector in section["decimal_separator"]["vectors"]:
        assert vector["point"] == vector["comma"].replace(",", "."), vector
        assert vector["comma"].count(",") <= 1

    remainders = [entry["remainder"] for entry in section["reduction_vectors"]]
    assert remainders == list(LOCKED_REDUCTION_REMAINDERS)
    for entry in section["reduction_vectors"]:
        assert entry["double_only_remainder"] == entry["remainder"]
    assert section["reduction_vectors"][0]["x"] == 281320423161
    assert section["constants"] == {
        **LOCKED_HASH_CONSTANTS, "FP_VERSION": 1, "STREAM_TAG": "PCCM-FP",
        "SECTION_ORDER": ["HEADER", "COST", "RISK"],
    }


def test_the_emitted_plan_case_values_match_the_hand_derived_literals() -> None:
    """Plan section 23's own numbers, restated here, against the emitted corpus."""
    cases = {case["id"]: case for case in _built()["cases"]["plan_cases"]}
    for identifier, expected in PLAN_LITERALS.items():
        case = cases[identifier]
        assert case["kind"] == "analytical", identifier
        payload = case["expected"]
        driver = payload["drivers"][0]
        for key, value in expected.items():
            if key in payload["totals"]:
                _close(payload["totals"][key], value, f"case {identifier} {key}")
            else:
                _close(driver[key], value, f"case {identifier} {key}")


def test_every_declared_refusal_case_is_actually_refused() -> None:
    """The corpus says a model must be refused; the oracle must agree, and the
    refusal CLASS is part of the expectation."""
    cases = _built()["cases"]["plan_cases"]
    refusals = {case["id"]: case["expected_refusal"]
                for case in cases if case["kind"] == "refusal"}
    assert refusals == {
        14: "ModelInputRefusal", 15: "ModelInputRefusal", 16: "ModelInputRefusal",
        17: "ModelInputRefusal", 18: "ModelInputRefusal", 20: "ModelInputRefusal",
        23: "ModelInputRefusal", 24: "NumericalRangeRefusal",
        29: "NumericalRangeRefusal",
    }


def test_case_28_statistics_are_the_locked_stable_form_results() -> None:
    case = next(c for c in _built()["cases"]["plan_cases"] if c["id"] == 28)
    values = {(item["statistic"], tuple(item["points"])): item["expected"]
              for item in case["statistics"]}
    assert values[("triangular_mean", (1e308, 1e308, 1e308))] == 1e308
    assert values[("beta_pert_mean", (1e308, 1e308, 1e308))] == 1e308
    assert values[("midpoint", (1.5e308, 1.5e308))] == 1.5e308


def test_case_31_emits_the_base_year_factor_row() -> None:
    """Base 2026, Start 2028: a 2026 row with a blank rate and a factor of exactly 1."""
    case = next(c for c in _built()["cases"]["plan_cases"] if c["id"] == 31)
    rows = case["expected"]["inflation_factors"]
    base = next(row for row in rows if row["calendar_year"] == 2026)
    assert base["annual_rate"] is None, base
    assert base["cumulative_factor"] == 1.0, base
    assert {row["calendar_year"] for row in rows} >= {2026, 2027, 2028}


def test_the_regression_corpus_carries_the_load_bearing_c1_and_c2_vectors() -> None:
    vectors = _built()["cases"]["regression_vectors"]
    assert set(vectors) == {
        "conditioning", "convex_statistics", "materialization", "product",
        "row_order", "signed_sum",
    }
    signed = {entry["name"]: entry for entry in vectors["signed_sum"]}
    assert signed["canonical order is preserved when it succeeds"]["expected"] == 0.0
    assert signed["rounding residual of the cancellation is the answer"]["expected"] == -1e292
    assert "expected_refusal" in signed["genuinely outside Double range"]

    product = {entry["name"]: entry for entry in vectors["product"]}
    assert product["representable product below the smallest normal"]["expected"] == 5e-324
    assert "expected_refusal" in product["genuinely outside Double range by under one ulp"]

    convex = {entry["name"]: entry for entry in vectors["convex_statistics"]}
    assert convex["degenerate Beta-PERT at MAX_DOUBLE"]["expected"] == 1.7976931348623157e308
    assert "expected_refusal" in convex["non-zero statistic that collapses to zero"]

    materialization = {entry["name"]: entry for entry in vectors["materialization"]}
    a = materialization["Reproducer A: Knom refused on a pre-FX intermediate"]
    assert a["expected"]["drivers"][0]["knom"] == 1.7976931348623157e308 / 2
    b = materialization["Reproducer B: annual row refused on a per-driver contribution"]
    assert [row["base_cost_nominal"] for row in b["expected"]["annual"]] == [0.0, 0.0, 0.0]
    c = materialization["Reproducer C: annual row refused on a contribution that underflows"]
    assert [row["base_cost_nominal"] for row in c["expected"]["annual"]] == [5e-324, 2.0]
    boundary = materialization[
        "a published driver audit amount outside range still refuses"
    ]
    assert boundary["expected_refusal"] == "NumericalRangeRefusal"

    assert len(vectors["conditioning"]) == 2
    assert len(vectors["row_order"]) == 1


# ---------------------------------------------------------------------------
# 5. THE INDEPENDENT ORACLE
# ---------------------------------------------------------------------------
# Exact rational arithmetic, written here from the plan's formulas. It shares no
# code with `calc_oracle.py`: it re-derives inflation factors, discount factors,
# Knom, Kpv, every driver amount, the annual series and the ten headline totals
# from the case's INPUT DATA alone. `Fraction` is exact and is test-only.
def _exact_statistic(distribution: str, minimum, most_likely, maximum):
    low, high = Fraction(minimum), Fraction(maximum)
    if distribution == "Uniform":
        central = mean = (low + high) / 2
    elif distribution == "Triangular":
        middle = Fraction(most_likely)
        central, mean = middle, (low + middle + high) / 3
    elif distribution == "Beta-PERT":
        middle = Fraction(most_likely)
        central, mean = middle, (low + 4 * middle + high) / 6
    else:
        raise AssertionError(distribution)
    return central, mean


def _exact_case(model: dict) -> dict:
    """Every published value of one case, in exact rationals."""
    timeline = model["timeline"]
    base, start, duration = (
        timeline["base_year"], timeline["start_year"], timeline["duration"]
    )
    years = [start + offset for offset in range(duration)]
    last = years[-1]

    factors: dict[str, dict[int, Fraction]] = {}
    for profile, rates in model["inflation"].items():
        running = Fraction(1)
        table = {base: Fraction(1)}
        for year in range(base + 1, last + 1):
            running = running * (1 + Fraction(rates[str(year)]))
            table[year] = running
        factors[profile] = table

    rate = Fraction(model["discount_rate"])
    discount = {1: Fraction(1)}
    for index in range(2, duration + 1):
        discount[index] = discount[index - 1] / (1 + rate)

    fx = {row["currency"]: Fraction(row["rate"])
          for row in model["fx"] if row["rate"] is not None}

    drivers = []
    for entry in sorted(model["cost_lines"] + model["risks"],
                        key=lambda d: d["permanent_id"]):
        is_risk = "probability" in entry
        weights = [Fraction(w) for w in entry["profile_weights"]]
        table = factors[entry["inflation_profile"]]
        rate_fx = fx[entry["currency"]]
        knom = rate_fx * sum(
            (weights[i] * table[years[i]] for i in range(duration)), Fraction(0)
        )
        kpv = rate_fx * sum(
            (weights[i] * table[years[i]] * discount[i + 1] for i in range(duration)),
            Fraction(0),
        )
        central, mean = _exact_statistic(
            entry["distribution"], entry["min_value"],
            entry.get("most_likely"), entry["max_value"],
        )
        multiplier = (
            Fraction(entry["probability"]) if is_risk else Fraction(entry["quantity"])
        )
        drivers.append({
            "permanent_id": entry["permanent_id"],
            "is_risk": is_risk,
            "central_value": central,
            "mean_value": mean,
            "knom": knom,
            "kpv": kpv,
            "weights": weights,
            "multiplier": multiplier,
            "table": table,
            "fx": rate_fx,
            "deterministic_nominal": Fraction(0) if is_risk else central * multiplier * knom,
            "deterministic_pv": Fraction(0) if is_risk else central * multiplier * kpv,
            "mean_basis_nominal": Fraction(0) if is_risk else mean * multiplier * knom,
            "mean_basis_pv": Fraction(0) if is_risk else mean * multiplier * kpv,
            "expected_risk_nominal": mean * multiplier * knom if is_risk else Fraction(0),
            "expected_risk_pv": mean * multiplier * kpv if is_risk else Fraction(0),
        })

    def total(key: str, risk: bool) -> Fraction:
        return sum((d[key] for d in drivers if d["is_risk"] is risk), Fraction(0))

    a_nom, a_pv = total("deterministic_nominal", False), total("deterministic_pv", False)
    c_nom, c_pv = total("mean_basis_nominal", False), total("mean_basis_pv", False)
    d_nom, d_pv = total("expected_risk_nominal", True), total("expected_risk_pv", True)

    annual = []
    for offset, year in enumerate(years):
        base_nom = sum(
            (d["mean_value"] * d["multiplier"] * d["fx"] * d["weights"][offset]
             * d["table"][year] for d in drivers if not d["is_risk"]),
            Fraction(0),
        )
        risk_nom = sum(
            (d["mean_value"] * d["multiplier"] * d["fx"] * d["weights"][offset]
             * d["table"][year] for d in drivers if d["is_risk"]),
            Fraction(0),
        )
        factor = discount[offset + 1]
        annual.append({
            "base_cost_nominal": base_nom, "expected_risk_nominal": risk_nom,
            "total_nominal": base_nom + risk_nom,
            "base_cost_pv": base_nom * factor, "expected_risk_pv": risk_nom * factor,
            "total_pv": (base_nom + risk_nom) * factor,
        })

    return {
        "drivers": drivers,
        "annual": annual,
        "totals": {
            "a_nom": a_nom, "a_pv": a_pv,
            "b_nom": c_nom - a_nom, "b_pv": c_pv - a_pv,
            "c_nom": c_nom, "c_pv": c_pv,
            "d_nom": d_nom, "d_pv": d_pv,
            "e_nom": c_nom + d_nom, "e_pv": c_pv + d_pv,
        },
    }


def test_every_emitted_number_is_confirmed_by_an_independent_exact_oracle() -> None:
    """THE GOLDEN-INDEPENDENCE PROOF.

    For every analytical case, every driver amount, every annual column and every
    headline total emitted into `phase5_cases.json` is re-derived here in exact
    rational arithmetic from the case's inputs, and compared. The emitted values
    came from `calc_oracle.py`; these came from the plan's formulas written out
    again. A defect in either shows up as a disagreement.
    """
    checked = 0
    for case in _built()["cases"]["plan_cases"]:
        if case["kind"] != "analytical":
            continue
        exact = _exact_case(case["model"])
        payload = case["expected"]

        assert len(payload["drivers"]) == len(exact["drivers"]), case["id"]
        for emitted, reference in zip(payload["drivers"], exact["drivers"]):
            assert emitted["permanent_id"] == reference["permanent_id"]
            # A field that does not apply to a driver kind is BLANK, never zero -
            # the same rule the contract states for the runtime table - so the
            # comparison asserts absence rather than a fabricated 0.
            cost_only = ("central_value", "deterministic_nominal", "deterministic_pv",
                         "mean_basis_nominal", "mean_basis_pv")
            risk_only = ("expected_risk_nominal", "expected_risk_pv")
            for key in ("mean_value", "knom", "kpv") + cost_only + risk_only:
                applies = not (
                    (reference["is_risk"] and key in cost_only)
                    or (not reference["is_risk"] and key in risk_only)
                )
                if not applies:
                    assert emitted[key] is None, (
                        f"case {case['id']} {emitted['permanent_id']} {key} is "
                        f"{emitted[key]!r}; a field that does not apply must be blank"
                    )
                    continue
                _close(emitted[key], float(reference[key]),
                       f"case {case['id']} {emitted['permanent_id']} {key}")
                checked += 1
            if not reference["is_risk"]:
                _close(
                    emitted["uncertainty_mean_shift_nominal"],
                    float(reference["mean_basis_nominal"]
                          - reference["deterministic_nominal"]),
                    f"case {case['id']} B nominal",
                )
                checked += 1

        assert len(payload["annual"]) == len(exact["annual"]), case["id"]
        for emitted, reference in zip(payload["annual"], exact["annual"]):
            for key in ("base_cost_nominal", "expected_risk_nominal", "total_nominal",
                        "base_cost_pv", "expected_risk_pv", "total_pv"):
                _close(emitted[key], float(reference[key]),
                       f"case {case['id']} year {emitted['calendar_year']} {key}")
                checked += 1

        for key, value in exact["totals"].items():
            _close(payload["totals"][key], float(value), f"case {case['id']} {key}")
            checked += 1

    assert checked > 400, f"only {checked} emitted numbers were independently checked"


def test_the_independent_oracle_disagrees_when_the_corpus_is_wrong() -> None:
    """The independence proof would be worthless if it could not fail."""
    case = next(c for c in _built()["cases"]["plan_cases"] if c["id"] == 1)
    exact = _exact_case(case["model"])
    assert float(exact["totals"]["a_nom"]) == 1000.0
    try:
        _close(1000.0 * 1.001, float(exact["totals"]["a_nom"]), "sabotaged")
    except AssertionError:
        return
    raise AssertionError("the comparison accepted a wrong value")


# ---------------------------------------------------------------------------
# 6. Stage A consumes, but does not calculate
# ---------------------------------------------------------------------------
def test_stage_a_renders_the_workspace_without_calling_the_oracle() -> None:
    """THE DISTINCTION THIS STEP TURNS ON.

    The workbook build must consume the calculation contract and must NOT call
    `calculate`. The oracle is replaced by one that raises, and the build still
    succeeds - proving no cell is populated by a calculation. The CASES generator
    is a separate artifact and is allowed to call it.
    """
    from pccm_builder import calc_oracle

    built = _built()
    genuine = calc_oracle.calculate

    def forbidden(*args, **kwargs):
        raise AssertionError("Stage-A workbook emission called the analytical oracle")

    calc_oracle.calculate = forbidden
    try:
        workbook, _ = build_workbook(
            built["spec"], built["contract"], built["drivers"], built["structure"],
            built["calc"],
        )
        directory = Path(tempfile.mkdtemp(prefix="pccm-step3-nocalc-"))
        try:
            path = directory / "out.xlsx"
            workbook.save(path)
            workbook.close()
            result = verify_workbook(
                path, built["spec"], built["contract"], built["drivers"],
                built["structure"], built["calc"],
            )
            assert result.ok, result.report()
        finally:
            shutil.rmtree(directory, ignore_errors=True)
    finally:
        calc_oracle.calculate = genuine


def test_the_renderer_does_not_import_the_analytical_oracle() -> None:
    """A structural guard: representation must not depend on calculation.

    Read from the AST, not from the text: this module's own docstring explains
    that it never imports the oracle, and a textual search would find that
    sentence and call it a violation.
    """
    import ast

    tree = ast.parse(
        (PCCM_ROOT / "builder" / "pccm_builder" / "calc_render.py").read_text(
            encoding="utf-8"
        )
    )
    imported: set[str] = set()
    called: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imported |= {alias.name for alias in node.names}
        elif isinstance(node, ast.ImportFrom):
            imported.add(node.module or "")
            imported |= {alias.name for alias in node.names}
        elif isinstance(node, ast.Call) and isinstance(node.func, ast.Name):
            called.add(node.func.id)
    for banned in ("calc_oracle", ".calc_oracle", "calculate", "CalculationModel",
                   "calc_numeric"):
        assert banned not in imported, f"calc_render.py imports {banned}"
    assert "calculate" not in called


def test_no_simulation_field_reaches_the_calculation_emission() -> None:
    """Phase 5 introduces no RNG and reads no Monte Carlo input."""
    for name in ("calc_render.py", "calc_emit.py", "calc_cases.py"):
        source = (PCCM_ROOT / "builder" / "pccm_builder" / name).read_text(encoding="utf-8")
        for banned in ("inpMonteCarloIterations", "inpRandomSeed",
                       "inpSelectedConfidenceLevel", "MRG32k3a", "Randomize",
                       "random", "seed"):
            assert banned not in source, f"{name} references {banned}"
    built = _built()
    without, _ = build_workbook(
        built["spec"], built["contract"], built["drivers"], built["structure"], None
    )
    with_calc, _ = build_workbook(
        built["spec"], built["contract"], built["drivers"], built["structure"],
        built["calc"],
    )
    try:
        before = [
            (cell.coordinate, cell.value)
            for row in without["_SimData"].iter_rows() for cell in row
            if cell.value is not None
        ]
        after = [
            (cell.coordinate, cell.value)
            for row in with_calc["_SimData"].iter_rows() for cell in row
            if cell.value is not None
        ]
        assert before == after, "_SimData changed when the calculation contract was added"
        assert not getattr(with_calc["_SimData"], "tables", {})
    finally:
        without.close()
        with_calc.close()


# ---------------------------------------------------------------------------
# 7. determinism
# ---------------------------------------------------------------------------
def test_the_generated_artifacts_are_byte_identical_across_builds() -> None:
    built = _built()
    first_module = render_calc_contract_module(built["spec"], built["calc"])
    second_module = render_calc_contract_module(built["spec"], built["calc"])
    assert first_module == second_module == built["module_text"]

    first_json = render_cases_json(built["spec"], built["calc"])
    second_json = render_cases_json(built["spec"], built["calc"])
    assert first_json == second_json
    assert json.loads(first_json) == built["cases"]


def test_the_generated_artifacts_carry_no_timestamp_or_machine_path() -> None:
    built = _built()
    for text in (built["module_text"], json.dumps(built["cases"])):
        for banned in ("/home/", "/tmp/", "C:\\", str(PCCM_ROOT)):
            assert banned not in text, f"{banned!r} leaked into a generated artifact"
    document = built["cases"]
    assert "generated_at" not in document and "timestamp" not in document
    assert set(document["provenance"]) == {
        "model_version", "calc_contract_version", "fingerprint_version",
        "oracle", "numerical_kernel", "fingerprint_authority",
    }


def test_the_build_script_produces_the_two_phase_five_artifacts_on_disk() -> None:
    """End to end, through the real entry point, reading the files from disk."""
    directory = Path(tempfile.mkdtemp(prefix="pccm-step3-cli-"))
    try:
        environment = dict(os.environ, PCCM_BUILD_TIMESTAMP="1970-01-01 00:00:00 UTC")
        completed = subprocess.run(
            [sys.executable, str(BUILD_SCRIPT), "--quiet",
             "--out", str(directory / "PCCM_stageA.xlsx")],
            capture_output=True, text=True, check=False, env=environment,
        )
        assert completed.returncode == 0, completed.stdout + completed.stderr
        module = directory / "vba" / "modCalcContract.bas"
        cases = directory / "phase5_cases.json"
        assert module.is_file() and cases.is_file()
        assert module.read_text(encoding="utf-8").startswith(
            'Attribute VB_Name = "modCalcContract"'
        )
        document = json.loads(cases.read_text(encoding="utf-8"))
        assert document["schema_version"] == 1
        assert len(document["plan_cases"]) == 37

        second = Path(tempfile.mkdtemp(prefix="pccm-step3-cli2-"))
        try:
            subprocess.run(
                [sys.executable, str(BUILD_SCRIPT), "--quiet",
                 "--out", str(second / "PCCM_stageA.xlsx")],
                capture_output=True, text=True, check=True, env=environment,
            )
            assert (second / "vba" / "modCalcContract.bas").read_bytes() == module.read_bytes()
            assert (second / "phase5_cases.json").read_bytes() == cases.read_bytes()
        finally:
            shutil.rmtree(second, ignore_errors=True)
    finally:
        shutil.rmtree(directory, ignore_errors=True)


def test_the_stage_a_xlsm_and_vba_boundary_is_unchanged() -> None:
    """`modCalcContract.bas` is a Stage-A artifact, not workbook content."""
    import zipfile

    with zipfile.ZipFile(_built()["path"]) as archive:
        names = archive.namelist()
    assert not any("vba" in name.lower() for name in names), names
    assert not any(name.endswith(".bas") for name in names)


def test_no_phase_five_vba_module_was_added_to_the_stage_b_manifest() -> None:
    """Step 3 emits generated constants only. The Phase-5 module inventory belongs
    to the later VBA implementation steps."""
    manifest = json.loads(
        (PCCM_ROOT / "build" / "stage_b_manifest.json").read_text(encoding="utf-8")
    ) if (PCCM_ROOT / "build" / "stage_b_manifest.json").is_file() else None
    if manifest is None:
        return
    text = json.dumps(manifest)
    for forbidden in ("modCalcFactors", "modCalcAnalytical", "modCalcFingerprint",
                      "modCalcResolve", "modCalcCheck", "modCalcReport",
                      "PCCM_Calculate"):
        assert forbidden not in text, f"{forbidden} appeared in the Stage-B manifest"


def test_the_stage_a_verification_is_extended_and_nothing_was_dropped() -> None:
    """THE COUNT, PROVED RATHER THAN ASSERTED.

    Step 3 extends post-build verification, so the number must go up. What must
    NOT happen is an old check being replaced by a broader one to keep the total
    small, so every prior check is matched by description and the new ones are
    counted as an addition.

    Run WITHOUT the calculation contract, one prior check legitimately fails - the
    "only contract-declared Excel Tables exist" gate, because the artifact now
    carries five tables the caller did not declare. That is the gate working, not
    a regression, and it is why the comparison is on the check SET rather than on
    the pass count.
    """
    built = _built()
    before = verify_workbook(
        built["path"], built["spec"], built["contract"], built["drivers"],
        built["structure"],
    )
    after = verify_workbook(
        built["path"], built["spec"], built["contract"], built["drivers"],
        built["structure"], built["calc"],
    )

    def names(result) -> list[str]:
        return result.passed + [f.split(" -- ", 1)[0] for f in result.failures]

    prior, extended = names(before), names(after)
    assert len(prior) == 181, f"the Phase-4 baseline moved: {len(prior)}"
    assert set(prior) <= set(extended), sorted(set(prior) - set(extended))[:5]
    assert after.ok, after.report()
    assert len(extended) == 351, len(extended)
    assert len(extended) - len(prior) == 170


# ---------------------------------------------------------------------------
# 8. NEGATIVE CONTROLS - the generated artifact is what is checked
# ---------------------------------------------------------------------------
def _verify_mutated(mutate) -> list[str]:
    """Build, mutate the saved workbook, re-verify. Returns the failures."""
    built = _built()
    directory = Path(tempfile.mkdtemp(prefix="pccm-step3-neg-"))
    try:
        workbook, _ = build_workbook(
            built["spec"], built["contract"], built["drivers"], built["structure"],
            built["calc"],
        )
        mutate(workbook["_Calc"], workbook)
        path = directory / "mutated.xlsx"
        workbook.save(path)
        workbook.close()
        result = verify_workbook(
            path, built["spec"], built["contract"], built["drivers"],
            built["structure"], built["calc"],
        )
        return result.failures
    finally:
        shutil.rmtree(directory, ignore_errors=True)


def _moved_table(name: str, reference: str):
    def mutate(worksheet, workbook):
        worksheet.tables[name].ref = reference
    return mutate


def test_the_verifier_catches_a_table_moved_one_column() -> None:
    failures = _verify_mutated(_moved_table("tblCalcYears", "I15:K16"))
    assert any("tblCalcYears" in f for f in failures), failures


def test_the_verifier_catches_a_table_widened_one_column() -> None:
    failures = _verify_mutated(_moved_table("tblCalcFX", "S15:V16"))
    assert any("tblCalcFX" in f for f in failures), failures


def test_the_verifier_catches_a_changed_header() -> None:
    def mutate(worksheet, workbook):
        worksheet["H15"] = "Project Idx"
    assert any("tblCalcYears" in f for f in _verify_mutated(mutate))


def test_the_verifier_catches_a_renamed_table() -> None:
    def mutate(worksheet, workbook):
        table = worksheet.tables["tblCalcAnnual"]
        del worksheet.tables["tblCalcAnnual"]
        table.name = table.displayName = "tblCalcAnnualX"
        worksheet.add_table(table)
    failures = _verify_mutated(mutate)
    assert any("Excel Tables" in f or "tblCalcAnnual" in f for f in failures), failures


def test_the_verifier_catches_a_moved_calc_state_row() -> None:
    def mutate(worksheet, workbook):
        worksheet["C17"] = None
        worksheet["C21"] = "NONE"
    assert any("calc_state" in f for f in _verify_mutated(mutate))


def test_the_verifier_catches_a_seeded_fingerprint_version() -> None:
    def mutate(worksheet, workbook):
        worksheet["C15"] = 1
    failures = _verify_mutated(mutate)
    assert any("fingerprint version" in f for f in failures), failures


def test_the_verifier_catches_a_calc_total_seeded_with_zero() -> None:
    def mutate(worksheet, workbook):
        worksheet["C27"] = 0
    failures = _verify_mutated(mutate)
    assert any("zero" in f or "calc_totals" in f for f in failures), failures


def test_the_verifier_catches_an_inserted_calculation_formula() -> None:
    def mutate(worksheet, workbook):
        worksheet["C23"] = "=SUM(AU16:AU20)"
    failures = _verify_mutated(mutate)
    assert any("formula" in f or "calc_totals" in f for f in failures), failures


def test_the_verifier_catches_an_overwritten_phase_four_counter() -> None:
    def mutate(worksheet, workbook):
        worksheet["C10"] = 7
    failures = _verify_mutated(mutate)
    assert any("Phase-4 counter" in f for f in failures), failures


def test_the_verifier_catches_a_fabricated_semantic_table_row() -> None:
    def mutate(worksheet, workbook):
        worksheet["H16"] = 1
        worksheet["I16"] = 2026
    failures = _verify_mutated(mutate)
    assert any("ZERO semantic rows" in f for f in failures), failures


def test_a_mutated_projected_tolerance_is_caught() -> None:
    """A projected constant that stops matching its authority fails the check."""
    import dataclasses

    from pccm_builder import calc_emit

    built = _built()
    calc = built["calc"]
    tampered = dataclasses.replace(
        calc, tolerances=dataclasses.replace(
            calc.tolerances, profiling_sum_absolute=1e-8
        )
    )
    text = calc_emit.render_calc_contract_module(built["spec"], tampered)
    value = next(
        line for line in text.splitlines()
        if line.startswith("Public Const TOL_PROFILING_SUM_ABSOLUTE")
    )
    assert "1e-08" in value
    assert value != next(
        line for line in built["module_text"].splitlines()
        if line.startswith("Public Const TOL_PROFILING_SUM_ABSOLUTE")
    )


def test_a_mutated_projected_hash_modulus_is_caught() -> None:
    from pccm_builder import calc_emit, calc_fingerprint

    built = _built()
    original = calc_fingerprint.FP_MOD_2
    try:
        calc_fingerprint.FP_MOD_2 = 2147483587
        text = calc_emit.render_calc_contract_module(built["spec"], built["calc"])
        assert "Public Const FP_MOD_2 As Long = 2147483587" in text
        assert "Public Const FP_MOD_2 As Long = 2147483629" in built["module_text"]
    finally:
        calc_fingerprint.FP_MOD_2 = original


def test_a_mutated_golden_expected_value_is_caught() -> None:
    """The independence check fails when the corpus and the plan disagree."""
    cases = {case["id"]: case for case in _built()["cases"]["plan_cases"]}
    tampered = json.loads(json.dumps(cases[1]))
    tampered["expected"]["totals"]["a_nom"] = 1001.0
    exact = _exact_case(tampered["model"])
    try:
        _close(tampered["expected"]["totals"]["a_nom"], float(exact["totals"]["a_nom"]))
    except AssertionError:
        return
    raise AssertionError("a tampered golden value passed the independence check")


# ---------------------------------------------------------------------------
# runner
# ---------------------------------------------------------------------------
def _run_all() -> int:
    tests = sorted(
        (name, fn) for name, fn in globals().items()
        if name.startswith("test_") and callable(fn)
    )
    failures = 0
    print("PCCM Phase 5 Gate-A Step-3 Stage-A emission tests")
    print("=" * 70)
    for name, fn in tests:
        try:
            fn()
        except AssertionError as error:
            failures += 1
            print(f"  [FAIL] {name}\n         {error}")
        except Exception as error:  # noqa: BLE001
            failures += 1
            print(f"  [ERROR] {name}\n          {type(error).__name__}: {error}")
        else:
            print(f"  [PASS] {name}")
    print("=" * 70)
    print(f"  {len(tests) - failures} passed, {failures} failed")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(_run_all())
