"""Render the Phase-4 structural runtime surfaces.

Three surfaces, all driven from ``structure_contract.yaml``:

  * the applied-timeline block and structural-state indicator appended to Setup
  * the permanent-ID counter block on _Calc
  * the Cost Profiling, Risk Profiling and Inflation grids

Stage A renders each grid with its FIXED columns only. Project-year and
calendar-year columns are generated by Stage-B structural runtime once a timeline
has actually been applied; fabricating them here would invent a timeline the user
never entered.

The only formulas written are structural-state displays enumerated by the contract
(``StructureContract.formula_cells``). No cost, risk, escalation, FX or simulation
value is computed anywhere in this module.
"""

from __future__ import annotations

from openpyxl.worksheet.table import Table, TableStyleInfo
from openpyxl.worksheet.worksheet import Worksheet

from .structure_loader import Grid, StructureContract
from .styling import StyleBook


def render_applied_timeline(
    worksheet: Worksheet, structure: StructureContract, styles: StyleBook
) -> None:
    """Append the structural-state indicator and applied timeline block to Setup."""
    state = structure.structural_state
    _write(worksheet, state.label_cell, state.label, styles.label)
    cell = worksheet[state.cell]
    cell.value = state.formula
    cell.number_format = state.number_format
    styles.apply_locked(cell)
    if state.note:
        _write(worksheet, f"{state.note_column}{_row_of(state.cell)}", state.note, styles.note)

    block = structure.applied_block
    label_column = block["label_column"]
    note_column = block["note_column"]

    _write(worksheet, f"{label_column}{block['section_row']}", block["section"], styles.section)
    worksheet.row_dimensions[block["section_row"]].height = styles.row_height("section")
    if block.get("note_row"):
        _write(worksheet, f"{label_column}{block['note_row']}", block["note"], styles.note)

    for field in structure.structural_fields:
        _write(worksheet, field.label_cell, field.label, styles.label)
        cell = worksheet[field.cell]
        # An applied value is model-written state and stays genuinely blank until the
        # first successful apply. A derived cell carries its structural formula.
        cell.value = field.formula
        cell.number_format = field.number_format
        styles.apply_locked(cell)
        if field.note:
            _write(worksheet, f"{note_column}{_row_of(field.cell)}", field.note, styles.note)


def render_identity(
    worksheet: Worksheet, structure: StructureContract, styles: StyleBook
) -> None:
    """The persistent permanent-ID counters on _Calc."""
    block = structure.identity_block
    label_column = block["label_column"]
    note_column = block["note_column"]

    if block.get("intro_row"):
        _write(worksheet, f"{label_column}{block['intro_row']}", block["intro"], styles.note)
    _write(worksheet, f"{label_column}{block['section_row']}", block["section"], styles.section)
    worksheet.row_dimensions[block["section_row"]].height = styles.row_height("section")

    for counter in structure.counters:
        _write(worksheet, counter.label_cell, counter.label, styles.label)
        cell = worksheet[counter.cell]
        cell.value = counter.initial
        cell.number_format = counter.number_format
        styles.apply_locked(cell)
        if counter.note:
            _write(worksheet, f"{note_column}{_row_of(counter.cell)}", counter.note, styles.note)


def render_grid(
    worksheet: Worksheet, grid: Grid, structure: StructureContract, styles: StyleBook
) -> None:
    """One structural grid: headings, the state message, and the fixed-column table."""
    if grid.intro and grid.intro_row:
        _write(worksheet, f"B{grid.intro_row}", grid.intro, styles.note)
    _write(worksheet, f"B{grid.section_row}", grid.section, styles.section)
    worksheet.row_dimensions[grid.section_row].height = styles.row_height("section")
    if grid.note and grid.note_row:
        _write(worksheet, f"B{grid.note_row}", grid.note, styles.note)

    # A formula, so the message clears itself the moment a timeline is applied and
    # returns if the applied state is ever cleared. Nothing maintains it at runtime.
    key = "inflation_formula" if grid.kind == "inflation" else "profiling_formula"
    _write(worksheet, f"B{grid.state_message_row}", structure.state_messages[key], styles.note)

    for index, column in enumerate(grid.fixed_columns):
        letter = grid.column_letter(index)
        worksheet.column_dimensions[letter].width = column.width

        header = worksheet[f"{letter}{grid.header_row}"]
        header.value = column.header
        styles.apply_table_header(header)

        for row in range(grid.first_data_row, grid.last_data_row + 1):
            cell = worksheet[f"{letter}{row}"]
            cell.number_format = column.number_format
            # Every fixed column is model-controlled: a permanent key, or a trace copy
            # the register owns. The user edits neither here.
            styles.apply_locked(cell)

    excel_table = Table(displayName=grid.table_name, ref=grid.ref)
    excel_table.tableStyleInfo = TableStyleInfo(
        name=styles.table_style_name,
        showFirstColumn=False,
        showLastColumn=False,
        showRowStripes=False,
        showColumnStripes=False,
    )
    worksheet.add_table(excel_table)

    if grid.freeze_panes:
        worksheet.freeze_panes = grid.freeze_panes


def _write(worksheet: Worksheet, address: str, value, font) -> None:
    cell = worksheet[address]
    cell.value = value
    cell.font = font


def _row_of(cell: str) -> int:
    return int("".join(ch for ch in cell if ch.isdigit()))
